### ISSUE TITLE
Potential for extent miscalculation in obscure circumstances

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#1020]
Due to how extent caching is implemented, and the addition of type-coercion in #1019, there is a potential for scale extent caching to break in a subtle way. Particularly, if you have the same data with the same accessor being passed into two different scales, where the scales have different type coercers, then it will inappropriately get a cache hit when the output actually winds up being different. This is difficult to fix due to how the cache is implemented (by strict equality testing on the accessor). We can't just wrap the accessor and type-coercer together because then the array will technically be a new object every time. We could probably solve it with a 2-layer cache, it will just require some time and attention. I don't think this is a high priority bug because it only comes about in very particular & strange circumstances.

**Comment by aicioara** [comment]
Such a bug has not been filed yet. Also the architecture has changed. Unless a repro is provided, won't fix.
