### ISSUE TITLE
[Pie] Add labels to pie plots

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1039]
Moving forward, we will need to think about how to label each section with an appropriate label such as percentage, value, etc.  Popular opinion wants to place the values in the legend, but the possibly more philosophically correct opinion is to place the labels directly on the plot so there's more modularity.  A solution to achieve the popular opinion is to use a scale possibly for values.

- [ ] Figure out default labels
- [ ] Place labels
- [ ] Format the labels
- [ ] Toggle labels
- [ ] label api point
  - [ ] Default "label" (figured out from above)

**Comment by rcchen** [comment]
Fixed in #2346
