### ISSUE TITLE
[Pie] - innerRadius / outerRadius should take percentages

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1069]
Right now the project innerRadius / outerRadius calls on pie plots take in raw pixel values to draw the plot.  A significantly easier API usage could be to take in percentage values instead, which would agree with the overarching idea of thinking less in terms of pixels.

However, there is discussion surrounding needing the exact pixel value for a pie plot.  However the counter argument came out to be that if an exact pixel value is needed, the percentage can be calculated out in that case.

**Comment by jtlan** [comment]
`outerRadius()` and `innerRadius()` now take `Scale`s whose ranges are set to the maximum possible radius within the space the Plot has been allocated, which should satisfy this request:

```Javascript
var radiusScale = new Plottable.Scales.Linear();
radiusScale.domain([0, 100]); // percentages
piePlot.outerRadius(90, radiusScale);
```
