### ISSUE TITLE
Projection of string values is awkward.

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1075]
Right now when strings are used as the second argument to project, the string is used for an accessor into the data.  However, there are many times to use the string value itself and the current workaround we have is to wrap the string value into a function.  I propose that we have a function like projectValue or projectString that takes a primitive/string and just projects the given value.

**Comment by jtlan** [comment]
If we want to change it so that constant values are always directly applied, we should decide soon.

**Comment by jtlan** [comment]
--> #1909.
