### ISSUE TITLE
Automated integration testing

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1083]
#1059 (and the discussion on #1080) revealed the need for tests that check the total functionality of a Plottable use-case, in addition to the unit tests. We should figure out what is a good way to do this, and ideally automate it. Some of the behavior being checked in the 2-up tests probably belongs here.

**Comment by aicioara** [comment]
Integration testing = unit tests & travis. Done.

End-to-end testing is done manually now via the overlaying tests. One way to automate those is to use some pixel diff tool, but it is not a priority now. @terekim might have some input about this at some point

Closing.
