### ISSUE TITLE
Figure out why plottable_multifile.js doesn't load correctly.

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1093]
Previously, tests were run using **plottable_multifile.js**, which split up the source code to make it easier to identify where code was executing during the tests. However, for reasons still unknown, on @endrjuskr 's computer loading the unit tests page with the multifile version of Plottable chokes.

The multifile version of Plottable simplifies debugging tests, so it would be nice to restore it. On the other hand, the single-file version is a more realistic test scenario.

**Comment by aicioara** [comment]
It does not seem to be an issue anymore.
In any case, plottable_multifile.js is still generated for some reason.

Opened https://github.com/palantir/plottable/issues/2445

**Comment by aicioara** [comment]
Reopening to make it more visible that this is still an issue
