### ISSUE TITLE
Tick labels can be positioned badly under constrained circumstances

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1118]
![screen shot 2014-09-29 at 1 54 36 pm](https://cloud.githubusercontent.com/assets/1440449/4449257/dc1f58f4-481a-11e4-93ae-13ff7aff04c2.png)

http://jsfiddle.net/dFf3s/7/

**Comment by crmorford** [comment]
Surprisingly still happening http://jsfiddle.net/dywyfpj2/2/
