### ISSUE TITLE
Add style() to Component

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1150]
It would be helpful to be able to set the style directly on `Component`, in addition to setting the CSS class with `classed()`. I propose adding a `style()` call with a syntax similar to D3's.

It's unclear if this would satisfy the Slate request to be able to set the color on an `Axis`, as the styling may not propagate all the way down (I believe `style` only sets the style attribute on the current `Selection` in D3).

**Comment by aicioara** [comment]
Unless there is a newer request for this, I don't see the need for the endpoint. Style should in general be attached by CSS classes. Closing, unless more requests for this feature are coming in.
