### ISSUE TITLE
API point for errors / Plottable error logger

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#1194]
Slate would like a consistent error delivery mechanism, maybe an error bus, maybe exception handling.

We could probably wire this into `Warn` so that errors are simultaneously reported through a well-defined API point and put to console; Slate could configure it to reroute away from console and just go through the API.

Maybe developer provides a function, and that function gets called with all the errors/warnings that occur? There are definitely some control flow / async / API design things to think about here, we should rope in slate for feedback

**Comment by aicioara** [comment]
This was solved a while ago. We use `Utils.Window.warn()` for warnings and `Plottable.Configs.SHOW_WARNINGS` for setting/unsetting this
