### ISSUE TITLE
Uneven Behavior of Tick Labels Appearing/Disappearing in Negative and Positive

### ISSUE THREAD

**Issue by terekim** [palantir/plottable#1196]
SLATE issue 1111
Plottable repro: http://jsfiddle.net/tkim/k1gxzp1L/3/
(In the screenshot, 500000 shows up on the right when on the left -500000 doesn't, vice versa)
![screen shot 2014-10-14 at 11 50 24 am](https://cloud.githubusercontent.com/assets/8551049/4634738/03c613e8-53d3-11e4-90a5-e2c4207d07d2.png)

**Comment by crmorford** [comment]
Weird to comment in response to a comment that's 3 months old, but I think Dan's idea of an approach sounds pretty nice, from a user perspective.

**Comment by rcchen** [comment]
Yeah I mostly have that strategy in place now, the tricky part is trying to figure out a way to evaluate the different strategies with respect to each other and where the sweet spot is in terms of axis label density.
