### ISSUE TITLE
Better path string testing framework

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1216]
In the testing code, a common way to test if a path element renders correctly is to strictEqual the path strings.  This is completely fragile as floating point errors can easily occur as well as it does not really test the path other than "did this thing render exactly as i thought it would render?".  Ideally we have a testing framework that can be flexible for floating point errors as well as have a better expression of the test as in "does the path contain this point?" or "does this path not contain this point?"

**Comment by aicioara** [comment]
Part of https://github.com/palantir/plottable/issues/2446
