### ISSUE TITLE
Interaction.Dragbox.setupZoomCallback() does not work

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1236]
At all. Repro:
 1. Go to http://jsfiddle.net/7z6s4oyv/1/
 2. Attempt to click and drag inside the plot area.

Expected: Zooms in on drag area after releasing the mouse button.
Actual: Zooms wildly on beginning drag.

**Comment by crmorford** [comment]
This is going to go on my list for things to assign soon, too. How many hours of dev time is expected to take care of this?

**Comment by jtlan** [comment]
Probably going to remove this feature as part of the Dragbox refactor.
