### ISSUE TITLE
StackedBar on Dataset Change Does Not Scale Properly 

### ISSUE THREAD

**Issue by terekim** [palantir/plottable#1246]
Repro steps:
1. Observe initial state of stackedbar
2. Click on the chart to see changes in the first dataset with animation
3. StackedBar plot should have scaled properly in terms of y.
4. Click again to see the plot adjust itself properly

http://jsfiddle.net/tkim/xLrfhkzu/

![screen shot 2014-10-24 at 12 10 35 pm](https://cloud.githubusercontent.com/assets/8551049/4774842/7916e204-5bb1-11e4-94e1-ce1c6cab8dc9.png)

**Comment by jtlan** [comment]
Bump to P1; this is pretty fundamental.
