### ISSUE TITLE
Scales in bar plots don't account for bar width

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1280]
If a bar was placed on the edge of the scale, part of the bar could extend past the edge of the scale, causing that part of the bar to clip.  The scale should be extended to account for the bar.

**Comment by bluong** [comment]
We found that this is a hard problem due to not a good foundation on how to predict domain scrunching when incorporating a value in range space.

Since this does not seem to be marked as a huge priority, I'm bumping down the priority

**Comment by aicioara** [comment]
@bluong Can you give a repro?

**Comment by aicioara** [comment]
Probably [this](http://jsfiddle.net/x52jL23n/1/) or [this](http://jsfiddle.net/x52jL23n/2/) instead of extending the domain on `autoDomain()`

**Comment by aicioara** [comment]
Solving as part of #2558

**Comment by jtlan** [comment]
New repro: http://jsfiddle.net/h36uobz2/
