### ISSUE TITLE
Panzoom Interaction Performance for StackedBar with Auto Bar Width

### ISSUE THREAD

**Issue by terekim** [palantir/plottable#1284]
In this repro, I have dataset length of 50, and here you can definitely see performance changes in PanZooming. Compare this with modified auto barwidth plot in v0.34.0.

current -> http://jsfiddle.net/tkim/pboc0st2/36/
old, hacky auto-barwidth -> http://jsfiddle.net/tkim/pboc0st2/37/

**Comment by aicioara** [comment]
Slow version: http://jsfiddle.net/aycxz2ap/1/
Fast version: http://jsfiddle.net/aycxz2ap/2/

**Comment by aicioara** [comment]
I was hoping it will be caught by this https://github.com/palantir/plottable/pull/2337 but it seems like it is not the case. Will investigate further.

**Comment by aicioara** [comment]
It seems like the flush() method has to be improved. In the fast version it takes 13 ms, in the current version it takes 121 ms. Working on that...

**Comment by aicioara** [comment]
`_getBarPixelWidth()` is the bottleneck. In particular it is called about 80+ times during a `flush()` procedure, which does not seem right, especially considering its complexity

**Comment by aicioara** [comment]
Improved this to `10 ms` by caching the `barPixelWidth` value and updating it only where necessary

**Comment by bluong** [comment]
Progress looks good so far :smiley:
