### ISSUE TITLE
Labels hidden on Horizontal Bar Chart, incorrectly determined to be too wide

### ISSUE THREAD

**Issue by bavardage** [palantir/plottable#1300]
Visually the labels are not too wide, yet they are being detected as being too wide (drawer has _someLabelsTooWide = true) and thus they get hidden.

![too wide](https://hipchat.palantir.com/files/1/769/dy2V8kLQ2yA4Bb3/upload.png)

**Comment by bavardage** [comment]
I'm afraid I don't have a repro somewhere you can access

**Comment by aicioara** [comment]
The flag no longer exists. There is no repro. Might be related to https://github.com/palantir/plottable/issues/2210

Closing
