### ISSUE TITLE
Add short-scale formatter

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1353]
http://en.wikipedia.org/wiki/Long_and_short_scales

The current formatter for large numbers, `Formatters.siSuffix`, produces some unintuitive output for small numbers (0.1 --> "100m") and large numbers (10^9 --> "1.00G") for people who are used to the short scale. Here's probably what would be expected:

* 0.1 --> "0.1" (maybe the same behavior as the fixed formatter)
* 1 000 000 --> "1 M" (one million)
* 1 000 000 000 --> "1 B" (one billion)
* 1 000 000 000 000 --> "1 T" (one trillion)

Not sure if we should go above this to "quadrillion"

**Comment by dbt** [comment]
Hmm.  I wrote a version of this, but it's not actually obvious to me this should be a separate formatter from the currency one.  If you're interested in voicing an opinion, please get in touch with me shortly.

**Comment by christinaforney** [comment]
@dbt  can you clarify what you wrote as a version of this? Did something relevant get merged?

**Comment by aicioara** [comment]
Nothing relevant got merged. Taking over this and documenting the issue soon.
