### ISSUE TITLE
Can't project custom label text

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1377]
http://jsfiddle.net/r9ks2hLo/

Expected: Labels read "1", "2", "3"
Actual: Y-values are displayed

Inside `AbstractBarPlot`'s `_generateAttrToProjector` call:
```Typescript
var primaryAccessor = this._projections[primaryAttr].accessor;
if (this.barLabelsEnabled && this.barLabelFormatter) {
  attrToProjector["label"] = (d: any, i: number, u: any, m: PlotMetadata) => {
    return this._barLabelFormatter(primaryAccessor(d, i, u, m));
  };
  attrToProjector["positive"] = (d: any, i: number, u: any, m: PlotMetadata) =>
    originalPositionFn(d, i, u, m) <= scaledBaseline;
}
return attrToProjector;
```

multiple bugs here:
* Should be checking `this._barLabelsEnabled`, not `this.barLabelsEnabled`
* If the user tries to set the label text by `project()`ing "label", it gets overridden by the `primaryAccessor` value.

We might consider implementing a more general solution to the label problem.

**Comment by aicioara** [comment]
We no longer have these API endpoints. Closing
