### ISSUE TITLE
Error Bars

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1379]
Implement error bars:

![screen shot 2014-11-21 at 2 43 42 pm](https://cloud.githubusercontent.com/assets/1440449/5150990/2a1143d8-718d-11e4-9bad-39145357ab1f.png)

Things to watch out for:
- Upper and lower bound might not be the same distance away from the data point
- Error bars might not be the same size between data points
- How does this work for stacked plots?

**Comment by rcchen** [comment]
Conversation notes:
* Create the error bars as a different sort of plot, then have the error bars merged in. 
* Make sure that horizontal/vertical are both addressed

**Comment by christinaforney** [comment]
![7fa1ff70-6389-47a2-9d55-023acd396d9f](https://cloud.githubusercontent.com/assets/1559622/8286746/2e470160-18c0-11e5-8d22-e3887c80ada9.png)

**Comment by rcchen** [comment]
@christinaforney I filed a separate issue for that image at #2394

**Comment by aicioara** [comment]
@rcchen Was this solved by https://github.com/palantir/plottable/issues/2394 ?

**Comment by rcchen** [comment]
Kind of...I asked the original requested about the original error bars and they didn't remember why they wanted them but expressed interest in it anyways. Leave it open for now.

**Comment by aicioara** [comment]
Why can't we just use the Segment Plot for this?

**Comment by rcchen** [comment]
We can use `Plots.Segment` to convey the core information for this (the middle bar), but the top and bottom bars are an open question. We kind of dodged the issue of composite drawers (how they should be designed, what value they take on, what `.entityAt()` would mean for them) by introducing `Plots.Segment`, and there's an open conversation about introducing factory methods to Plottable.

That being said, we could close this issue because nobody really knows who wants these things anyways..

**Comment by aicioara** [comment]
I'd prefer closing it. The functionality can be achieved and the spec is not clearly defined.

**Comment by adrienrenaud** [comment]
It's an awesome feature @aicioara. I can't find any example anywhere on the web. Could you provide additional informations for plotting error bars? Could we reopen the issue?

**Comment by aicioara** [comment]
I wish I could provide additional information about how I was planning to do that back in 2015, but I can't remember and have not worked on Plottable since. I believe I was thinking of overlaying a segment plot on top of your bar plot. Best of luck, maybe one of the current developers can help.
