### ISSUE TITLE
PanZoomInteraction: resetZoom when scale is changed externally

### ISSUE THREAD

**Issue by thelastnode** [palantir/plottable#1388]
I know there's a planned rewrite of PZIs, but I've seen at least 3 different implementations of extending PZIs to do this.

Could we add a resetZoom on domain change as a stopgap till interactions are rewritten?

Related: #753 #254

**Comment by jtlan** [comment]
Short repro that shows the problem:
http://jsfiddle.net/r9fpovoe/
