### ISSUE TITLE
Interactions should have destruction call

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1442]
Currently, `Interaction`s don't have a destruction call. Since they maintain references to the `Component` they're attached to, and vice versa, the circular reference may interfere with garbage collection. Adding a destructor or some sort of cleanup call allows us to disconnect / destroy the interaction when the Component is `remove()`d.

**Comment by aicioara** [comment]
We have `detachFrom` now. Added in https://github.com/palantir/plottable/pull/1997

**Comment by aicioara** [comment]
However, it seems like when the component is removed, the interaction is still around. We need a `component.offAnchor` callback for this

**Comment by aicioara** [comment]
Duplicate of the better documented https://github.com/palantir/plottable/issues/2334
