### ISSUE TITLE
DragBox Interaction becomes Godzilla when registered in group

### ISSUE THREAD

**Issue by terekim** [palantir/plottable#1445]
repro steps:
1. start a dragbox somewhere in the center of the plot and drag it all the way down
2. try resizing the sides
3. watch dragbox grow
4. hover over its sides to see some interesting points where it can/cannot be resized
5. be mindblown

http://jsfiddle.net/k1gxzp1L/94/

![screen shot 2014-12-10 at 5 41 15 pm](https://cloud.githubusercontent.com/assets/8551049/5387724/a69632b4-8093-11e4-82c2-8a73d576bc3b.png)

**Comment by crmorford** [comment]
http://jsfiddle.net/k1gxzp1L/109/

**Comment by crmorford** [comment]
So this seems alright, but I'm gonna see if sonny can make me a slate build with this version so that i can test it out on their actual bug before saying it works. 
Because slate is a little unpredictable based on quicktests and jsfiddles.
