### ISSUE TITLE
Fewer Legend entries showing than before (sadface)

### ISSUE THREAD

**Issue by terekim** [palantir/plottable#1482]
derp derpitty derp derpie derpitty
http://jsfiddle.net/pboc0st2/45/

![screen shot 2014-12-19 at 4 47 27 pm](https://cloud.githubusercontent.com/assets/8551049/5513174/7fc1134a-879e-11e4-8bdc-76f2688a76be.png)

**Comment by rcchen** [comment]
@terekim vertical legends are typically placed on the sides of charts, as opposed to directly above them (http://jsfiddle.net/mstnnt8r/1/). If you want to add a horizontal legend on top of the chart, just place them accordingly in the table layout and set maxEntriesPerRow on the legend (http://jsfiddle.net/105vb9s4/1/)
