### ISSUE TITLE
Word Wrapping on Legend Text

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1493]
Requested by Slate user

**Comment by aicioara** [comment]
@crmorford Can you provide more details of the expected and current behavior? How exactly should the word be wrapped (do we use `-` symbol when going to the next line, etc?), do we crop the text at some points if it goes on too many lines?

**Comment by aicioara** [comment]
A fiddle to work with would be useful.

**Comment by CalvinFernandez** [comment]
closed by #3172
