### ISSUE TITLE
Interaction.Dragbox doesn't work with CSS scale() transforms

### ISSUE THREAD

**Issue by adidahiya** [palantir/plottable#1497]
Applying a CSS `scale()` transform to a scatter plot breaks the dragbox interaction. It seems like the element doesn't project interactions to the scaled SVG coordinates.

Repro: http://jsfiddle.net/fvsufoww/3/

**Comment by jtlan** [comment]
Initial experiments seem to indicate that the reported cursor position is always measured in real pixels, meaning that when the dragbox is drawn the scaled version of that position is wrong.

**Comment by jtlan** [comment]
Worse, the purported position of the mouse is different between browsers...

**Comment by jtlan** [comment]
The issue appears to be rooted in D3, whose event reporting doesn't respect CSS transforms that have been applied.

**Comment by adidahiya** [comment]
Here's the D3 issue related to this: https://github.com/mbostock/d3/issues/1787

Maybe you could implement something like the [hack suggested in the comments](https://github.com/mbostock/d3/issues/1787#issuecomment-64166249)?
