### ISSUE TITLE
Implement Interaction.Pan

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1502]

**Comment by jtlan** [comment]
We could do this with the current setup by setting `scaleExtent([1,1])` on the `D3.Behavior.Zoom`. We're planning on replacing `PanZoom` though, in which case it'd just be better to split it...

**Comment by jtlan** [comment]
Soft dependency on global event handlers (#1560), so that they don't interfere with each other (#1209).

Consider what happens for non-`Linear` scales. I suspect most users expect linear-ish behavior from the *pixel position under the cursor* when they start dragging; please consult Design.
