### ISSUE TITLE
Remove scales from Plot constructors

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1507]
The presence of `Scale`s as arguments to `Plot` constructors seems redundant. Consider:

```Javascript
var plot = new Plottable.Plot.Scatter(xScale, yScale);
...
plot.project("x", ..., xScale);
plot.project("y", ..., yScale);
```

The user already supplies the `Scale`s in the `project()` call, so it seems like we shouldn't need to specify them in the constructor.

**Comment by jtlan** [comment]
One scenario I can think of is the case where someone wants to make a `Plot.Bar` and render it before adding any data -- where does the baseline show up?

**Comment by aicioara** [comment]
Refactor RegEx for the update
```regex
(\.Plots\.[^\(]*\()[^\)\"]*
$1
```

**Comment by aicioara** [comment]
QuickTest fixer regEx

```regex
^((.*\.Plots\.[^\(]*\()[^\)\"]*((\{[^}]*\}|[^;])*;))
```
Replace with
```regex
try {
$2$3
} catch(err) {
$1
}
```

**Comment by crmorford** [comment]
Testing Notes:
* Numeric x Numeric axes
* Cat x Numeric scales, Numeric x Cat, Cat x Cat
* Time x Numeric scales, Time x Cat
* absence of .x() and/or .y()
*  .x(), .y() called, but leave out scale argument
* dataset is empty 
* .x() and .y() get passed same scale
* plot is rendered, then .x() is called again with a different scale

**Comment by aicioara** [comment]
Updated Quicktests Regex
```regex
^(.*)(var )(((.*) = .*\.Plots\.[^\(]*\()[^\)\"]*((\{[^}]*\}|[^;])*;))
```
replace with
```regex
var $4;
try {
$1$4$6
} catch(err) {
$1$3
}

```
