### ISSUE TITLE
Inconsistent end ticks on left vs. right of time axis

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1509]
![screen shot 2015-01-09 at 3 21 15 pm](https://cloud.githubusercontent.com/assets/7527733/5689033/472164e2-9813-11e4-9217-eba74eca0420.png)

This is the stocks quicktest. The long tick on the left side is always there when panning, but the right side never is. This looks broken.

**Comment by jtlan** [comment]
Related to #211?
