### ISSUE TITLE
XAxes overlapping (repro/analysis in progress)

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1511]
NO repro yet, attempt: http://jsfiddle.net/xL0duLo9/

EDIT: Changing the svg height on the above example also messes the chart up
http://jsfiddle.net/xL0duLo9/6/

Looks like this in Slate: 
![screen shot 2015-01-09 at 5 29 20 pm](https://cloud.githubusercontent.com/assets/7527733/5689936/2cc268b8-9826-11e4-9fb1-f81a2449bb79.png)

Only happens for ordinal scales.

EDIT (@bluong) : Repro has been made.  Simplifying the example to ensure it's mainly an axis issue, you see the corresponding image:

![screen shot 2015-01-22 at 12 25 28 pm](https://cloud.githubusercontent.com/assets/1448299/5863902/fb1fc308-a231-11e4-9084-4bc19d4c13dd.png)

Corresponding jsfiddle - http://jsfiddle.net/xL0duLo9/4/

NOTE: If you remove any of the Label components, the axes get messed up even more, but if you remove both, it acts fine.

EDIT (@bluong) : Even nicer, simpler repro
http://jsfiddle.net/xL0duLo9/8/

**Comment by crmorford** [comment]
Update: In slate, if you add labels to BOTH x-axes, it looks good again, but not if you add it to just one. I'm gonna need help from @jtlan or someone from Slate, I'm not making meaningful progress on this.

**Comment by crmorford** [comment]
Made a quicktest: doubleAxes. Still can't replicate behavior ¯\_(ツ)_/¯

**Comment by crmorford** [comment]
Plottable (http://jsfiddle.net/xL0duLo9/2/)
![screen shot 2015-01-21 at 1 35 06 pm](https://cloud.githubusercontent.com/assets/7527733/5845628/71822506-a172-11e4-97a9-40b34d397f4e.png)

v Slate
![screen shot 2015-01-21 at 1 33 17 pm](https://cloud.githubusercontent.com/assets/7527733/5845597/26c1f8de-a172-11e4-9660-fe64cdb7ee20.png)

**Comment by jtlan** [comment]
Note that the problem doesn't occur with `Axis.Numeric`:
http://jsfiddle.net/xL0duLo9/9/

**Comment by crmorford** [comment]
Oh, Brandon got a repro for this earlier! You have to make the svg very very short, ~175 pixels or less.

**Comment by bluong** [comment]
@crmorford there are also a few things that can get the bug the occur (Placing it into an unusual table for instance)
