### ISSUE TITLE
Dragboxes overlapping other widgets in Slate

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1512]
Tracked in Slate-1438.

First attempt at repro in JSFiddle (http://jsfiddle.net/fvsufoww/4/) and testing page doesn't show same behavior; I assume JSFiddle has protection against it, and testing page wouldn't be able to do it because of IFrames? (@jtlan)

**Comment by jtlan** [comment]
#1497 adds confounding factors that make it hard to diagnose this one...

**Comment by crmorford** [comment]
Fixed by https://github.com/palantir/plottable/pull/1612
