### ISSUE TITLE
1.0 or API stability timeline?

### ISSUE THREAD

**Issue by rayshan** [palantir/plottable#1524]
Hi Plottable team, would you have a schedule of when devs can expect API stability?

**Comment by jtlan** [comment]
Hi @rayshan,

We will likely reach 1.0 sometime within the next 3-6 months. We're in the process of identifying places where our API can be streamlined and made more consistent (such as #1507) to make it easier to reason about. This sorts of changes will likely constitute the majority of our API changes.

If you have any comments about the API choices we've made thus far, we'd love to hear them.

**Comment by rayshan** [comment]
Hi @jtlan, I don't have anything specific. The changes are great so far. I'm a big fan of the simplification. I have a big project coming up and plan to use plottable. Was just wondering about the general timeline.
