### ISSUE TITLE
Rotated ticks wrap aggressively

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1526]
![screen shot 2015-01-16 at 6 18 45 pm](https://cloud.githubusercontent.com/assets/1440449/5785990/2fa2786c-9dac-11e4-9c50-2d2cbe370f0a.png)
Repro: http://jsfiddle.net/xcgjf426/1/

**Comment by jtlan** [comment]
We can probably fix this by adjusting the `Axis.Category` space request mechanism, now that we use **svgTypewriter**.

**Comment by rcchen** [comment]
![image](https://cloud.githubusercontent.com/assets/1175041/6050696/a1c08582-ac76-11e4-85c5-1bd4178a4cf6.png)

This is just by adding additional space (15px to be precise) in cases where the tick label has been rotated through either 90 or -90 degrees. Kind of arbitrary but it works? @jtlan

**Comment by jtlan** [comment]
We should actually request more space, rather than just padding.

**Comment by rcchen** [comment]
Yeah, sounds good. I'll give that a shot.
