### ISSUE TITLE
Scale.Color produces odd results when used with named colors

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1527]
Repro: http://jsfiddle.net/mj26qxxs/
Expected: Bars are red and green.
Actual: Bars are black.

Inspecting element reveals this:
![screen shot 2015-01-19 at 2 41 15 pm](https://cloud.githubusercontent.com/assets/1440449/5806664/419f85ca-9fe9-11e4-92d1-c510ede1351f.png)
It appears auto-lightening code doesn't work correctly with named colors ("red", "green", etc).

**Comment by bluong** [comment]
I completely overlooked this page when rewriting some functionality for Scale.Color

Likely useful

https://github.com/mbostock/d3/wiki/Colors
