### ISSUE TITLE
InterpolatedColor Legend

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1528]
![](https://hipchat.palantir.com/files/1/769/No6jsNwNO7XOPwm/upload.png)
Grid Plots would be far easier to understand if a 'heat' legend was a feature in Plottable (like this: https://pepperprincess.files.wordpress.com/2012/02/new-heat-scale1.png?w=497)

**Comment by crmorford** [comment]
Initallay assigning to @jtlan, open to reassignment if it makes sense.

**Comment by bluong** [comment]
As legends are their own entity, this should be doable I think with the current state of the library.  My first instinct is that the colorScale that is backing the gridPlot can be ported to a legend and the legend should be able to list the colors and entries

**Comment by jtlan** [comment]
@bluong It's a `Scale.InterpolatedColor`, which makes things trickier...

**Comment by bluong** [comment]
Only if InterpolatedColor extended from Color...
