### ISSUE TITLE
Grid plots and Time Axes don't align

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1531]
![gridplot_big](https://cloud.githubusercontent.com/assets/7527733/5807132/08e89640-9fd5-11e4-8923-5484d1370f4a.png)

Time axes don't align well with grid plots, look at the x-axis.

**Comment by bluong** [comment]
Repro got: http://jsfiddle.net/bluong63/Lzah8a3u/

It seems to me that one of the reasons seems to be that the scale backing the axis is different than the scale backing the actual plot.

**Comment by crmorford** [comment]
Ah, okay. Can you stick a time scale on a grid plot, or no? I could figure this out pretty quick, but I figured I'd ask in case you know off the top of your head.

**Comment by crmorford** [comment]
Wait that makes no sense, right? Since Time is Numeric and Grid Plots need Category.

**Comment by bluong** [comment]
I tried using a Category Axis as the xAxis, and the plot seems to react fine... except that you see a bunch of meaningless numbers for the timestamps.  However, if you use a formatter to show the months (through a bit of Math or using the Date API), then problem should be solved?

**Comment by bluong** [comment]
Tiny bit of work on the Ordinal Scales but here's one possible solution

http://jsfiddle.net/Lzah8a3u/3/

**Comment by crmorford** [comment]
Ben gave me another pic: 

![](https://hipchat.palantir.com/files/1/769/EfM8Ld2FM2kvI8h/upload.png)

**Comment by rcchen** [comment]
Tracking non-ordinal scales for gridplots #1619 which should resolve this issue if I can get it to work properly with TimeScale

**Comment by crmorford** [comment]
Closed by #1619 :)

**Comment by bluong** [comment]
@rcchen Can you follow up with Ben to see if this works well for him?

**Comment by christinaforney** [comment]
Confirmed with Ben that this is resolved and works much better!
