### ISSUE TITLE
Overlaying legend for bar plots

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1532]
![paint](https://cloud.githubusercontent.com/assets/7527733/5807235/fd3b5bd8-9fd5-11e4-97ec-bab19167de35.jpg)

With the beginning of building add-on plots, something that has been asked for is overlaying information on bar plots. Hopefully this picture makes sense. If not, I can elaborate.

**Comment by jtlan** [comment]
There's a `barLabelsEnabled` API point for `Bar` plots right now, but I think this might be better implemented as a separate `Component`.

**Comment by crmorford** [comment]
Agreed, if we're going to start building add-ons as layers that go on top of plots, this should move

**Comment by crmorford** [comment]
Testing Notes:
* Possible to make sure that the labels only show up if they fit inside the bar?
* Good default colors
* Colorable based on data values
* Vertical Bars and Horizontal Bars
* Option to place at base or end of bar

**Comment by aicioara** [comment]
@crmorford Is this still an issue? 

@jtlan Do we want to support add-ons? That might be a neat idea.

**Comment by jtlan** [comment]
Can this be achieved with `labelFormatter()` on `Plots.Bar`?

**Comment by jtlan** [comment]
I think this is done using the `labelsEnabled()` API point on `Plots.Bar`.
