### ISSUE TITLE
Reacting well to CSS changes

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1541]
One power of Plottable is that we are neutral to the user's CSS changes on their Plottable elements... except for sizings.  If one were to change the font-size on a legend entry, for example, after the legend is rendered, the legend does not invalidate it's own inner layout getting all sorts of text collisions.

**Comment by jtlan** [comment]
Fixed by `redraw()`, which the user can invoke after a CSS change. There's no good way to detect a styling change.
