### ISSUE TITLE
[Scale]  - Auto domain fails if only one end of the domain is set

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1542]
Let's say I use a Linear Scale on a Bar Plot.

If I don't do anything to the Scale, then it will autodomain nicely.

However, if I wanted to set a min/max boundary on the scale domain but not both, autodomaining will not happen.

We may want to support autodomaining on a single side of a scale instead of both

**Comment by jtlan** [comment]
This seems more like the type of thing where the user would write a `Domainer` instead of us building out a fixed API point for it.

Speaking of which, `Domainer`s are pretty complicated...

**Comment by jtlan** [comment]
I think I've got a decent way to solve this. Let the user set only one side of the domain if they want:
```
domainMin(value); // sets only the lower end
domainMax(value); // sets only the upper end
```
These methods are basically `domain(values)` applied to only one end of the `Scale`'s domain. The other end will still be set with the value retrieved by `autoDomain()`, unless that would cause the `Scale` to reverse. *Actually* calling `autoDomain()` will blank both the min and the max, the same way that calling `autoDomain()` overrides a domain set with `domain(values)`.
