### ISSUE TITLE
Two sets of legend tests

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1561]
![screen shot 2015-01-29 at 12 04 29 pm](https://cloud.githubusercontent.com/assets/1440449/5965183/0795891a-a7af-11e4-9a77-3901074e787f.png)

Not sure why there are two. We should merge them, and eliminate any unnecessary tests.

**Comment by rcchen** [comment]
Brief look over suggests that it basically comes down to the difference between a regular legend (maxEntriesPerRow = 1) versus a horizontal legend (maxEntriesPerRow = Infinity). Still evaluating whether there are any reasonable merge areas, or whether renaming the two to Legend and HorizontalLegend respectively would be a better approach.
