### ISSUE TITLE
Size of InterpolatedColorLegend

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1568]
![screen shot 2015-01-30 at 5 18 05 pm](https://cloud.githubusercontent.com/assets/1440449/5986148/0f0e35ca-a8a4-11e4-91b0-5350d9a280bf.png)
fiddle: http://jsfiddle.net/df5hjpok/

Does it make sense for `InterpolatedColorLegend` to expand to fill the available space? While it might be reasonable for vertical ones ("right" or "left"), it'd be weird for a horizontal one to expand with a very wide chart...

**Comment by crmorford** [comment]
I don't think this is high priority. Maybe when we get around to it though, we could have something like InterpolatedColorLegend.expand(true/false) so that users have a choice between a fixed size, or filling the space.

**Comment by rcchen** [comment]
Same thing as #1666

**Comment by crmorford** [comment]
Good call, @rcchen. I'll close the other and put the picture here

**Comment by crmorford** [comment]
https://camo.githubusercontent.com/0f990f2e2a8fe9bc56724ba49e034955efae709d/68747470733a2f2f686970636861742e70616c616e7469722e636f6d2f66696c65732f312f3736392f45664d384c6432464d326b764938682f75706c6f61642e706e67

**Comment by aicioara** [comment]
@rcchen what is the status of this?

**Comment by rcchen** [comment]
@aicioara it looks like I've cleaned out most of the things I had planned for this week so I'll jump on it, expect a PR later

**Comment by aicioara** [comment]
cool
