### ISSUE TITLE
Ticks outside of the visible domain get rendered

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1578]
If the user uses a `TickGenerator` that doesn't obey the `Scale`'s domain:
![screen shot 2015-02-04 at 3 37 17 pm](https://cloud.githubusercontent.com/assets/1440449/6052106/cc95104a-ac83-11e4-9723-9c53b22c84d3.png)

http://jsfiddle.net/g2sejn6h/

**Comment by crmorford** [comment]
ew
