### ISSUE TITLE
getClosestPoint() for XYPlots

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1579]
For user-customized interactions, it would help to expose these sorts of methods:

```Typescript
public getClosestPoint(p: Point): ???;
```

So the user can pass mouse movements, clicks, etc in to them. See `getBars()` on `Bar` plots.

It should be possible to implement this on `AbstractXYPlot`.

Questions:
 - What gets returned? Data? Pixel values? `D3.Selection`s?

**Comment by jtlan** [comment]
We should think about maybe using R-trees or something later on for better perf.

**Comment by bluong** [comment]
When you say getClosestPoint, are you referring to a Point selection (like Line plots) or the selections themselves (like Bar plots)?
