### ISSUE TITLE
Hover interactions break on horizontal bar charts

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1584]
for vertical bar plots (http://jsfiddle.net/95hjyedn/1/) you can hover over a bar and the hover callback will draw a circle at the top of the bar.

horizontal...everything goes wrong.
http://jsfiddle.net/95hjyedn/

**Comment by aicioara** [comment]
Does not seem to be an issue anymore.

http://jsfiddle.net/95hjyedn/10/
http://jsfiddle.net/95hjyedn/9/

Maybe I did not repro the exact same thing.

@crmorford Can you check if this is still a problem?

**Comment by jtlan** [comment]
Closing as fixed.
