### ISSUE TITLE
Broadcaster is public, and only one per object

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1604]
Currently, `Broadcaster` requires that a `Listenable` be passed in, and a `Listenable` has the following contract:

```Typescript
export interface Listenable {
  broadcaster: Broadcaster;
}
```

This setup has a number of problems:
* The `broadcaster` field is public.
* Having more than one `Broadcaster` per `Listenable` is difficult, because one has to be named "`broadcaster`".

Instead of defining `Listenable` as a distinct type, we should allow `Broadcaster`s to be able to be attached to arbitrary `Object`s.

**Comment by bluong** [comment]
Can you explain the context behind the need behind having multiple broadcasters?

Also, while it is unfortunate that the `broadcaster` field is public we can hide its publicness through underscores, so I'm not 100% seeing that as an issue even though it is something I'm not a fan of.

**Comment by jtlan** [comment]
>Can you explain the context behind the need behind having multiple broadcasters?

Any case where you want to have a class that can broadcast multiple types of events that need to be distinguished. For example, `Dispatcher.Mouse` might want to alert listeners on both mouse-move and click events, but the groups of listeners might be different.

**Comment by bluong** [comment]
Ok I'm in context now

**Comment by jtlan** [comment]
Better idea: `Broadcasters` with generics:

```Typescript
export class Broadcaster<L> {
  ...
  public registerListener(key: any, callback: (listenable: L) => any) {
    ...
  }
}
```

allows for
```
export class AbstractScale {
  private _broadcaster: Broadcaster<AbstractScale>;
}
```
