### ISSUE TITLE
Non-Ordinal Scales for Plot.Grid

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1619]
`Plot.Grid` currently only supports `Ordinal` scales. But there are cases where non-`Ordinal` scales might be more appropriate:

![gridplot_big](https://cloud.githubusercontent.com/assets/7527733/5807132/08e89640-9fd5-11e4-8923-5484d1370f4a.png)

`Plot.Grid` should support non-`Ordinal` scales.

**Comment by rcchen** [comment]
Note to self: the crux of the issue is that the boxes are not aligning correctly with the scale.

**Comment by rcchen** [comment]
Addressed with the GridPlot restructuring in #1711
