### ISSUE TITLE
API point for forcing redraw

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1634]
When the `<svg>` Plottable is in is resized programmatically, or someone change the CSS stylings in a way that can affect layout (like changing font size), Plottable should redraw, but we are unable to detect these events. Nor would we necessarily want to, since the user has a better sense of when redraws are necessary.

Currently, the user can call `resize()` on the top-level component with no arguments, but that name seems unintuitive. The method name should more clearly reflect what it does.

**Comment by crmorford** [comment]
forceRedraw()
