### ISSUE TITLE
Pan Zoom min/max Zoom Amount

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1639]
(Slate 1721)
Prevent users from zooming too far in or out

**Comment by crmorford** [comment]
* API approved by @dbt 
* If I'm zoomed in the max amount, I should still be able to pan
* If I'm panned to the smaller or upper limit, I should still be able to zoom
* Works on iPad
* Reasonable default settings
* Min/Max values change on data update (if I add an outlier, it should be taken into account)
* Can still explicitly change domain to whatever I want
* Should be able to be turned off

**Comment by jtlan** [comment]
Closed in #2379.
