### ISSUE TITLE
Slider (FR)

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1640]
Create a slider that can be dragged along an axis. Slate wants this to normalize time axes.

**Comment by jtlan** [comment]
Probably two parts to this:
* A "flag" that sits on the axis
* A line that is drawn on the chart itself

**Comment by crmorford** [comment]
* Flag shape & size approved by designer
* Flag looks good on small charts and large charts
* 'Slider' line still 1) takes up all of plot when plot height increases AND 2) doesn't go out of bounds if plot height decreases
* 'Slider' line moves in sync with flag
* Flag can be grabbed and dragged
* Slider can be grabbed and dragged (? discuss)
* Two slider+flag can be placed on the same axis
* 2 Sliders + flags can be placed on x and y axis 
* Slider callback that gives pixel position is accurate on Time/Category/Numeric
