### ISSUE TITLE
CSS Scaling breaks nearly every interaction

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1644]
The mouse position isn't reported correctly, which causes everything to break.

**Comment by jtlan** [comment]
Subissues:
* #1497.

**Comment by crmorford** [comment]
Hover fixed, Key fixed

**Comment by jtlan** [comment]
Drag fixed in #1816.

**Comment by jtlan** [comment]
Panzoom fixed in #1896. All done!
