### ISSUE TITLE
CSS classes with a color name get applied incorrectly on Line/Area if animation is on

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1649]
![screen shot 2015-02-17 at 3 48 03 pm](https://cloud.githubusercontent.com/assets/1440449/6239810/764b08a0-b6bc-11e4-96dd-f926323f9995.png)
Repro: http://jsfiddle.net/68u6qwnn/1/

It looks like the class is applied as the hex value of the color...???

**Comment by rcchen** [comment]
Fixed by #1665
