### ISSUE TITLE
Updating dataset's data makes it disappear from legend

### ISSUE THREAD

**Issue by drglitch** [palantir/plottable#1661]
Repro:

1. Create a "my_plot" Plot.Line with two datasets, use series ID as scale (just like in examples)
2. on render, attach Legend and .merge it onto the Line component
3. observe legend having two items (one for each dataset id)
4. exec: *my_plot.datasets()[0].data(my_new_data);*
5. Observe new data re-render properly on chart, using correct color from scale, but legend now missing first item (only shows second id).

An alternative, *my_plot.removeDataset(series_id).addDataset(series_id, data);*, produces same result as above.

Can send code snip if desired - TIA! :)

**Comment by drglitch** [comment]
nevermind - user error - new dataset was missing the key used as accessor in series

**Comment by jtlan** [comment]
@drglitch : Were you using adding dataset-key property on each datum? Usually the preferred way to set dataset-wide properties is to use the `project()` call to access metadata:

The `project()` call's second argument is can take a method with 4 parameters:
```Javascript
function(datum, index, userMetadata, plotMetadata)
```
`userMetadata` contains the contents of the `Dataset`'s `.metadata()`, while `plotMetadata` contains a `datasetKey` corresponding to the key passed to `addDataset()`.

**Comment by drglitch** [comment]
@jtlan - yes, i was. Didn't realize that metadata existed - will take a look!
