### ISSUE TITLE
Weird ClipPath issue resulting from panzooming

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1669]
Steps:
1. Go to the testing page.
2. Compare against master.
3. Scroll down to the time_tier_config test
4. Press '2' to see the local branches functionality
5. Pan and Zoom

Expected:
The line plot should be clipped

Actual:
The line plot is never clipped showing the line plot outside the svg.

git-bisect bad commit: c8c13f2e05924b1a5e9455a8ae15b268340e919c

**Comment by aicioara** [comment]
I remember @crmorford found something similar for the vertical_line overlaying test. Cannot remember how to reproduce it. 

@crmorford Is this still a bug? Do you remember how to reproduce it?

**Comment by aicioara** [comment]
Doesn't seem to reproduce anymore. Will reopen if observed again
