### ISSUE TITLE
Plot.Scatter support for arbitrary symbol shapes

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1674]
It'd be good to have the ability to draw arbitrary symbols, instead of circles, for a `Plot.Scatter`. One question is what the API for this looks like? One symbol type per `Plot`? Is it `project()`-ed the same way as any other attribute? Is this a new type of `Plot` entirely?

**Comment by bluong** [comment]
What type of symbols are you referring to?  D3 has support for its own symbols here that we can utilize https://github.com/mbostock/d3/wiki/SVG-Shapes#symbol

**Comment by rcchen** [comment]
+1 to @bluong's suggestion for integrating D3 symbols. The `project()` call also seems promising; I don't think changing the symbol type merits a new type of `Plot`.

One thing that I'm thinking about is situations where someone might want to use a custom symbol. In that case, would it be possible to allow people to draw new symbols out of SVG paths or CSS transforms completely through a `project()` call?
