### ISSUE TITLE
Time scale locks up if domain is set to two equal values

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1689]
http://jsfiddle.net/vhqwqwry/2/

Due to `Date` object equality checking.

**Comment by crmorford** [comment]
Locks up as in won't pan?

**Comment by crmorford** [comment]
This still seems kinda shaky with 1 point. http://jsfiddle.net/ck1psjL3/20/
Add 1 point, try to drag it sideways so the point is in the middle (won't work)
Try to add more points (no effect)
