### ISSUE TITLE
Adding Component to filled cell should automatically create Group

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1714]
http://jsfiddle.net/kykxLta8/1/

Trying to add a `Component` to a `Table` cell that is already occupied yields the message:
```
Table.addComponent cannot be called on a cell where a component already exists (for the moment)
```

Should we add in this functionality?

**Comment by rcchen** [comment]
+1, I remember running into this all the time when I was first trying out Plottable. Is the (intended) default behavior to form a component group of existing elements now?

**Comment by bluong** [comment]
Do we want `addComponent` to replace or append to the cell group?  I'm ok with either, but I'm not a fan of the current behavior.  I agree that I think appending is probably nicer.

**Comment by rcchen** [comment]
I actually think replacing is nicer; it was what I expected when I first attempted to use this function. I think it's because of the nature of the table-based layout; I viewed the entire layout area as an Excel spreadsheet where cells are only replaced, and not appended to.

**Comment by jtlan** [comment]
Based on talking to @crmorford, this should produce a `Group` (probably by adding the new `Component` above the ones that are already there).

The replacement effect can be done by calling `remove()` on the `Component` that is already there.
