### ISSUE TITLE
calling getAllSelections on a grid plot before render produces error

### ISSUE THREAD

**Issue by bavardage** [palantir/plottable#1717]
produces the following stack trace
this is plottable version 0.45.1

    TypeError: Cannot read property 'selectAll' of undefined
    at http://localhost:8080/bower_components/plottable/plottable.js:6513:44
    at Array.forEach (native)
    at SelectableGrid.AbstractPlot.getAllSelections (http://localhost:8080/bower_components/plottable/plottable.js:6507:33)
    at link (http://localhost:8080/boards/grid/plottable-grid.js:124:26)

**Comment by bluong** [comment]
`getAllSelections` currently assumes that the appropriate svg elements are already on the page such that we can actually select them.

**Comment by jtlan** [comment]
@bluong Do you mean to say that this is "intended behavior"? We should at least return nothing.

**Comment by aicioara** [comment]
It is called `selections()` now and it returns an empty selection if called before render
