### ISSUE TITLE
Add a rect element inside of render-area to allow styling background

### ISSUE THREAD

**Issue by rimig** [palantir/plottable#1725]
Currently it's practically impossible to style the background content of a chart (inside the axis). Inside of .render-area we could add a rect element to make this much easier.

Below is the area we would like to have control over.

![image](https://cloud.githubusercontent.com/assets/1369884/6560662/2fff356e-c662-11e4-80a6-ec510ee00bfa.png)

**Comment by crmorford** [comment]
note to self: test on every browser/os combo

**Comment by bluong** [comment]
We could possibly append a rect into the foreground that we expose to the user as the background the user can affect

**Comment by jtlan** [comment]
@bluong wrote:
> We could possibly append a rect into the foreground that we expose to the user as the background the user can affect

You mean the background?
