### ISSUE TITLE
Bar Chart Labels are only partially rendered if cut off by min/max

### ISSUE THREAD

**Issue by jchomicki** [palantir/plottable#1728]
When enabling labels on a bar chart, where one bar is partially cut off by a min/max, the label is still rendered, but cut off. If the render is too small to show the label fully, the label should be removed.

Pic attached with a cut off label.
![2015-03-10_12-01-52](https://cloud.githubusercontent.com/assets/5685907/6582853/564a0558-c71d-11e4-9b44-8878b9dc838a.png)

**Comment by rcchen** [comment]
Note to self: also needs to be done with pie chart labels even though we decided this was a WONTFIX there since that decision was made because of pie chart behavior

**Comment by aicioara** [comment]
@christinaforney This is done, just needs to pass CR. @rcchen still owns it I believe.
