### ISSUE TITLE
Bars and Points Partially Cut off from Min/Max

### ISSUE THREAD

**Issue by jchomicki** [palantir/plottable#1729]
When setting a min/max on both bar and line charts, a bar that is directly on the limit, or a point directly on the limit will be partially cut off from the chart. This visually looks bad and should act like excel where there is padding created to show the entire visual.

Bar Chart Example: 
![2015-03-10_12-16-03](https://cloud.githubusercontent.com/assets/5685907/6583141/68925f9c-c71f-11e4-9cf5-3253f328e1b5.png)

Scatter Chart Example:
![2015-03-10_12-16-55](https://cloud.githubusercontent.com/assets/5685907/6583147/70522e2e-c71f-11e4-89d6-bcc644f7d532.png)

**Comment by rcchen** [comment]
I suspect that this is more or less the same issue as #1728, will update when I get a chance to look at the relevant code.

**Comment by rcchen** [comment]
After a number of conversations w/ the team, we determined that this is expected and correct behavior on the part of Plottable, and that applications which utilize Plottable should be responsible for transforming a user-provided min/max into something that will not result in cut off bars. If additional API points are needed to accomplish this, please file issues to that effect. Closing.
