### ISSUE TITLE
background rect is on top of bar plot

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1734]
http://jsfiddle.net/mukzrLk2/9/
 play w/ opacity in css part of fiddle. when it approaches 1, the bars get more and more obscured.

**Comment by bluong** [comment]
The problem is that the background rect is for specifically the one plot.  When you have plots merge on top of each other, the plot on top's background will cover the plot on the bottom

**Comment by jtlan** [comment]
If you set the selector to hit `.component-group`, it's not specific enough either, but you can specify that only fills in the backgrounds of `Group`s get colored:
```CSS
.plottable .component-group > .background-container > .background-fill {
  ...
}
```
http://www.w3.org/TR/css3-selectors/#child-combinators

http://jsfiddle.net/mukzrLk2/13/

**Comment by jtlan** [comment]
We might still want to consider alternative implementations. Maybe it only happens on `Group`s?

**Comment by bluong** [comment]
> We might still want to consider alternative implementations. Maybe it only happens on `Group`s?

This'll only work if we consider a single component to be a Group

**Comment by jtlan** [comment]
> This'll only work if we consider a single component to be a Group

The user can put a single `Component` in a `Group` if they want the background, but they don't need to otherwise.

**Comment by jtlan** [comment]
Resolved using more specific selectors. To select only the background of `Group`s:

```CSS
.plottable .component-group > .background-container background-fill {
  fill: pink;
}
```

Nested `Group`s will require more complex selectors, or using `classed()` to identify a particular `Group`.
