### ISSUE TITLE
Command Line Plottable 

### ISSUE THREAD

**Issue by aliasav** [palantir/plottable#1761]
Is there an API I could use for exporting the plots as png/pdf, server side?

**Comment by jtlan** [comment]
Hello @aliasav,

Thanks for the suggestion! We've been focusing on `Interaction`s lately, so we haven't looked into this. Would you like to submit a pull request, or discuss potential approaches for doing this? We're open to suggestions.

**Comment by aliasav** [comment]
I'm just a student, may not have the technical know-how to achieve this! 
Although a feature where an export request would save the graph in the backend database and then allow user to save it as png/jpeg/pdf was what I had in mind.

**Comment by aicioara** [comment]
Created this as my Hack Week project
https://github.com/aicioara/plottable-node
@aliasav Please let me know if this suits your needs.

**Comment by aicioara** [comment]
Also closing. Plottable was not intended for server side usage or exporting png/pdfs.
