### ISSUE TITLE
add dataset/label as a class in <path> element for pie charts

### ISSUE THREAD

**Issue by rimig** [palantir/plottable#1781]
I'm trying to dynamically style my pie charts with data that I have already populating the values. For bar charts and line charts plottable does this great thing where it inserts the dataset name as a class in the <rect> or <path> element so that you can grab ahold of it and style it dynamically. I'd like this same ability with pie-charts however right now the <path> element is empty (just has an "arc" class)

**Comment by jtlan** [comment]
This is a Slate issue; now tracked as internal issue 1983.
