### ISSUE TITLE
One tier time axis configurations leaves white space in the unused second tier

### ISSUE THREAD

**Issue by vivianliang** [palantir/plottable#1800]
One tier time axis configurations, for example:
```
[
    { interval: d3.time.month, step: 1, formatter: Plottable.Formatters.time("%b d") }
]
```
 leaves white space in the unused second tier instead of eliminating the second tier altogether.

**Comment by jtlan** [comment]
Thanks for flagging this!

In the case where the `Axis.Time` has some configurations that use two tiers, this is intentional. However, in your example, the `Axis.Time` should only occupy one tier because it never has more than one tier.

Repro: http://jsfiddle.net/9kk194m6/1/

**Comment by aicioara** [comment]
@jtlan would we ever want to support more than 2 tiers?

**Comment by jtlan** [comment]
@aicioara We thought about doing that. I'm not sure whether that's best done by adding the ability to specify more configurations, or by coming up with a good way to stack multiple axes (using a `Table).

**Comment by jtlan** [comment]
More tiers tracked at #1820.
