### ISSUE TITLE
Pan/Zoom on Category Scale (Grids/Bars)

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1808]
Lat has a use case for this.
They have tons of data, there can be thousands of buckets on a single axis. Since you can't actually see individual information at that fine of a grain, they want to be able to 
1. zoom in on certain values
2. pan through values (like scrolling through a table)

**Comment by bluong** [comment]
I expected this... and it makes me sad.

**Comment by rcchen** [comment]
I know I have a demo of pan/zoom working on `Plot.Grid` somewhere. `Plot.Bar` definitely has some funkiness going on IIRC though...

**Comment by aicioara** [comment]
@crmorford Is this still an issue? Can we have more details of what is the actual use case? (a concrete example). I don't seem to understand the above.

**Comment by yocontra** [comment]
Also have a use case for this: Basically http://plottablejs.org/examples/calendar/ but with years of data

**Comment by hellochar** [comment]
Fixed by #3137
