### ISSUE TITLE
[Usability] Be able to renderTo HTML DOM Element

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#1819]
When playing with the library, it made a lot of sense for me to do this

```typescript
var svg = document.getElementById('demo');
chartTable.renderTo(svg);
```

Should this not be supported?

**Comment by aicioara** [comment]
@jtlan What do you think?

**Comment by aicioara** [comment]
For whoever implements this feature, line change is 

```typescript
if (typeof(element) === "string") {
```
Transform to 
```typescript
if (typeof(element) === "string" || element instance of Element) {
```

**Comment by jtlan** [comment]
`renderTo()` works when called with a `D3.Selection` -- `Element` support seems kind of redundant.

**Comment by bluong** [comment]
Something to consider in the long term - Instead of us relying on D3 Selections, can we rely on raw elements since the elements are the root source of information?

**Comment by aicioara** [comment]
@jtlan it's not redundant. It's practical. It seems very natural to write code like above. Yet, it fails. This is the exposed bit of the API, so I think it should be as easy to use as possible without the documentation open
