### ISSUE TITLE
Can't merge Component that's already anchored

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1823]
Repro: http://jsfiddle.net/0r93afbf/
Trying to add the label again produces the following message:
```
Uncaught Error: Can't presently merge a component that's already been anchored
```

Expected: adding a `Component` to a new `Group` should work even if the Component is already rendered.

**Comment by aicioara** [comment]
There is an additional issue here. If already anchored, elements do not adjust their translate values upon being moved around

**Comment by aicioara** [comment]
Actually bug reproduces even if the component is not anchored yet. Solving this issue as part of this ticket as well
```typescript 
label = new Plottable.Component.Label("AWESOME!");
chart.addComponent(1, 1, label); // this line has side effect on the final position of the label in cell [0][1]
chart.addComponent(0, 1, label); 
chart.renderTo("#chart");
```
