### ISSUE TITLE
Tutorials don't work with latest library

### ISSUE THREAD

**Issue by synotic** [palantir/plottable#1825]
I'm trying to run the bar chart tutorial with the latest code (0.52.0) and I'm getting this error:

`TypeError: undefined is not a constructor (evaluating 'new Plottable.Scale.Ordinal()')`

It looks like the tutorial is using 0.40.0 and OrdinalScale was renamed to CategoryScale:

https://github.com/palantir/plottable/commit/20e19d494d37391e8efac9a7dc1d1207b0cfcbb4

Changing Ordinal to Category fixes it, but tutorials should probably be updated to latest version of Plottable. May be other issues but only tried the first tutorial.

cc @rcchen

**Comment by rcchen** [comment]
Thanks for letting us know @synotic! I've filed the issue in our website repository; we'll be tracking it from there from here on out.
