### ISSUE TITLE
Plot.Grid fails on bad data values

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1851]
Repro: http://jsfiddle.net/wd1mmd38/

Actual: Errors are thrown in console. DOM contains a `<rect>` with invalid attributes.
Expected: No errors are thrown. `<rect>`s are only added for valid data points.

**Comment by aicioara** [comment]
Taking this since is related to my other 3 tickets of NaN being set on `<rect>` `svg` objects.

**Comment by aicioara** [comment]
Finished
