### ISSUE TITLE
Support for waterfall charts

### ISSUE THREAD

**Issue by joyt** [palantir/plottable#1853]
Example:
![image](https://cloud.githubusercontent.com/assets/2513424/7208696/9d4902f4-e510-11e4-83fb-5055cf06796c.png)
Seems like the basic data model is one where certain values are base bar values, where as others are just delta values between the base points, e.g. for the above:
```
[
{name: "Net Sales 2010", value: 100, type: "base"},
{name: "Price Effect", value: -10, type: "delta"},
{name: "Price Effect", value: 15, type: "delta"},
...
{name: "Net Sales 2011", value: 110, type: "base"}
...
]
```
Or the API could be even more general, with just some function you can pass to determines if each data point is a delta or a normal bar?

**Comment by rcchen** [comment]
Support for the bar parts of waterfall charts is currently possible by some amount of hackery involving `Plot.Rectangle`, if a temporary workaround is needed for the time being. That being said, this has been something we've heard about a couple of times already, so it's definitely a feature we will be building out.

@joyt re: the data model, is the former (something where you have "base" values and "delta" values) the sort of data that you are typically passing in? Or is it more like bar data, but with certain bars marked as "base" values (deltas are auto-computed between base values)?

**Comment by rcchen** [comment]
Just thought about this some more, it's completely possible to derive which bars represent base values. Base values are either (1) the first bar or (2) a bar that has the same value as the bar prior to it. Hence, data should be representable in the same manner as a bar chart.

**Comment by bluong** [comment]
I would be careful with making assumption (2).  I imagine that this type of plot is used for financial typed data like stocks.  I can imagine "bases" being the stock value at the start of a day and "deltas" being the stock changes throughout a day.  In this case, what if a stock didn't change value at a particular time?  Is it a "base"?  Probably not

**Comment by bluong** [comment]
@joyt It would be great if you can provide some sample data format so we can derive how we can think of the data

**Comment by rcchen** [comment]
@bluong If it didn't change, then the waterfall plot would not show anything at that point in time because it has a delta of zero. Seems reasonable to assume that there is always some sort of change being depicted but I agree that having sample data would help out my thought process here

**Comment by joyt** [comment]
Hey, we're still building out the functionality to generate these charts from the analysis tool so I don't have any real sample data. The use case is to have the % change of performance of a product be broken down into the reasons for that change using this waterfall format. It seems like since this is essentially a broken-up stacked bar chart, we could probably use a similar data model, e.g. 
```
[
{group: "2010 -> 2011", name: "Net Sales 2010", value: 100},
{group: "2010 -> 2011", name: "Price Effect", value: -10},
{group: "2010 -> 2011", name: "Volume Effect", value: 15},
{group: "2010 -> 2011", name: "Mixed Effect", value: 5},
{group: "2011 -> 2012", name: "Net Sales 2011", value: 110},
{group: "2011 -> 2012", name: "Price Effect", value: 8},
{group: "2011 -> 2012", name: "Volume Effect", value: 10},
{group: "2011 -> 2012", name: "Mixed Effect", value: 4},
{group: "2012", name: "Net Sales 2011", value: 132}
]
```
Making it 'waterfall' would essentially decompose the normal stacked bar visualization, spreading out the parts per group.

I was thinking I could hack it using the stacked bar for now (by making the bottom bar invisible), but would you guys suggest using Plot.Rectangle instead? (If so, a working example of how to use it would be much appreciated).

**Comment by rcchen** [comment]
@joyt I actually went ahead and implemented `Plot.Waterfall` in this pull request: https://github.com/palantir/plottable/pull/1860. It has a JSFiddle (http://jsfiddle.net/bL1d5gne/1/) so that you can see its usage. Currently the data model is something like this:

```
var data = [
  { x: "Net Sales 2010", y: 100 },
  { x: "Price Effect 10-11", y: 90 },
  { x: "Volume Effect 10-11", y: 105 },
  { x: "Mixed Effect 10-11", y: 110 },
  { x: "Net Sales 2011", y: 110 },
  { x: "Price Effect 11-12", y: 118 },
  { x: "Volume Effect 11-12", y: 128 },
  { x: "Mixed Effect 11-12", y: 132 },
  { x: "Net Sales 2012", y: 132 }
];
```

and deltas are automatically calculated. If this data model looks reasonable, then we can go ahead with the rest of the CR on this feature; if not, let us know what might work better for you.

**Comment by bluong** [comment]
@joyt Which data model is most similar to your usecase?  Do you essentially get a bunch of values and deltas or do you only get values and you would normally have to derive the deltas manually?

**Comment by joyt** [comment]
@bluong I don't have any real data yet as this functionality is still being built out in the upstream tool (within the next 2 weeks); I'll work with @rcchen's model for now and update with a real example when I have one.

**Comment by crmorford** [comment]
Note to devs:
We need to include a way to draw dotted lines connecting the waterfall plot

**Comment by dbt** [comment]
For more examples, Derek suggested checking out this page:
http://www.asymco.com/2013/02/05/margin-call/

Unfortunately the images are broken but I've ... rescued them:
http://www.asymco.com/wp-content/uploads/2013/02/Screen-Shot-2013-02-05-at-2-5-11.25.16-AM-620x620.png
http://www.asymco.com/wp-content/uploads/2013/02/Screen-Shot-2013-02-05-at-2-5-11.36.46-AM-620x586.png
