### ISSUE TITLE
Plot.Grid pixelPoints in wrong spot

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1859]
![screen shot 2015-04-17 at 4 47 32 pm](https://cloud.githubusercontent.com/assets/1440449/7212780/7e5976f6-e521-11e4-92e3-81b4293e3fdf.png)
http://jsfiddle.net/pgn8ms8u/

**Actual**: `pixelPoints` are at top-center of each cell.
**Expected**: `pixelPoints` are in center of each cell.

Note that this also happens with non-`Category` `Scale`s:
![screen shot 2015-04-17 at 5 03 35 pm](https://cloud.githubusercontent.com/assets/1440449/7212890/bd96ae9a-e523-11e4-9d68-c8d532bc0632.png)
http://jsfiddle.net/y5pkauk7/

... but in this case we should probably put the `pixelPoints` on whatevever the `y` values are.

**Comment by aicioara** [comment]
http://jsfiddle.net/pgn8ms8u/6/ Rectangle plot is fixed

**Comment by aicioara** [comment]
Same for the second example
http://jsfiddle.net/pgn8ms8u/7/

**Comment by aicioara** [comment]
@crmorford can you confirm?
