### ISSUE TITLE
.project('class') on waterfall charts clobbers styling

### ISSUE THREAD

**Issue by joyt** [palantir/plottable#1862]
The style classes for waterfall charts:
```
.waterfall-base {
    fill: #039BE5;
}
.waterfall-decline {
    fill: #D32F2F;
}
.waterfall-growth {
    fill: #43A047;
}
```
gets overwritten if the user uses `Plot.project('class', function(){...})` to add their own classes. Would it be possible to make a way to only add classes rather than determine them completely?

**Comment by rcchen** [comment]
@bluong how do you feel about gradually building out API points to replace the `.project` calls? This would be a great candidate for that
