### ISSUE TITLE
Crosshairs as Component

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1871]

**Comment by crmorford** [comment]
Testing Notes:
* Crosshair appearance is easy to change with CSS
* Crosshairs work well with mouse-move, either following mouse or attaching to closest point
* Crosshairs work well with hover on iPad, same as above
* Crosshairs render similarly on Chrome, IE, Firefox, iPad

**Comment by jtlan** [comment]
Is this taken care of with the addition of `GuideLineLayer`?

**Comment by CalvinFernandez** [comment]
closing -- guidelinelayer is sufficient.
