### ISSUE TITLE
[ScaleDomainCoordinator] - Usage is really confusing

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#1893]
The most of the work of the coordinator seems to be done on the construction of the object, thus one will run into code flows like the following:

```typescript
var scale;
var scale2;
new Plottable.ScaleDomainCoordinator([scale, scale2]);
```

Note that the coordinator only has to be constructed and there does not even have to be a reference to interact with the object.  This seems like an antipattern

**Comment by aicioara** [comment]
This class does not exist anymore
