### ISSUE TITLE
project() restructuring - remove 2nd-argument magic

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1909]
Was: #1075.

The 2nd argument of `project()` currently does many magical things:
- If a number, it is applied directly
- If a string, it gets turned into a key, *unless* it begins with "#"
- If a function, it gets invoked and passed `(datum, index, userMetadata, plotMetadata)`.

The behavior should be closer to that of D3's `attr()` call:
- If a function, it gets invoked.
- Otherwise, it is wrapped in a functor that returns that value.

**Comment by bluong** [comment]
Done
