### ISSUE TITLE
project() restructuring - remove 1st-argument magic

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1910]
Was: #1074.

`project()`'s first argument is nominally the "attribute to set", and so the results of the accessor function + scale are usually applied directly. Except:
- `"x"` and `"y"` are usually distorted all over the place due to the particulars of whatever plot we're on.
- `"width"` and `"height"` are distorted on `Plot.Bar`.
- `Plot.Pie` doesn't do anything the normal way!
- `"class"` needs to be set strangely to avoid clobbering existing styling. Whatever method is used to set this needs to be named carefully to avoid colliding with the existing `classed()` method.
- The baseline on `Plot.Bar` might be a good candidate for this conversion as well, which would enable floating bars.

The resolution:
- [ ] **Step 1**: pull special calls into their own methods. An example:
```Typescript
public xValue(accessor: AccessorFunction, scale?: Plottable.Scale)
```
- [ ] **Step 2**: make `project()` always apply the result directly to the "attribute to set", and rename it `attr()` (an existing alias) to make the new functionality clear.

**Comment by jtlan** [comment]
Some follow-ups for properties we should have:
#### All `XYPlot`s
- `x()`
- `y()`

#### `Plots.Scatter`
- `size()`
- `symbol()` -- I think this should take no scale and only accept either a `String` or a function that returns a `String`. While this is a downgrade in functionality, I think the current API for symbols is too powerful. Let's start with this and figure out a way to add custom symbols later.

#### `Plots.Grid`
- `x2()`
- `y2()`

#### Other thoughts
- `Plots.Rectangle` is sort of a mystery to me, since I don't really want to expose `x`, `x1`, and `x2` for all its descendants -- for one thing, it doesn't make sense on `Plots.Bar`. Maybe make the properties `protected`?

**Comment by bluong** [comment]
@rcchen what are your thoughts on `Plots.Rectangle`

**Comment by bluong** [comment]
DONE
