### ISSUE TITLE
Refactor Drawers

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1913]
`Drawer`s were originally created to compartmentalize part of the `Plot`'s logic in a reusable way. However, shifting information between `Plot`s and their `Drawer`s turned out to be troublesome and involved a whole bunch of "package-protected" methods.

We either need to come up with a good public-facing API for `Drawer`s, or re-integrate them back into the `Plot`s.

Close #1917 or edit (depending on the case) when done

**Comment by crmorford** [comment]
What things did drawers used to do for the plots? so that I can make sure all of that still works.

**Comment by bluong** [comment]
Done!
