### ISSUE TITLE
Remove underscores from private/protected vars

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1914]
Un-idiomatic in Typescript, since the `private` and `protected` keywords already indicate not to mess with them.

Make sure to retain underscores on variables shadowing a getter/setter.

**Comment by rcchen** [comment]
There's a pretty good discussion about this in Microsoft's Typescript forums (https://typescript.codeplex.com/discussions/397651) as well as StackOverflow (http://stackoverflow.com/questions/4484424/underscore-prefix-for-property-and-method-names-in-javascript)

The bottom line is that Javascript developers are accustomed to private members having the underscore prefix convention to denote "use at your own peril", so we should be designing Plottable around this convention.

+1 prefixed underscores for private and protected members. No prefixed underscores for the public API.
