### ISSUE TITLE
Use reference equality rather than keys when registering objects/callbacks

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1915]
Prime examples:
- `addDataset()` on `Plot`
- `onEvent()` on `Dispatcher`s and `Interaction`s.

Also includes a refactor to use `offEvent(callback)` to deregister `callback` rather than `offEvent(key, null)`.

- [x] Implement `CallbackSet`
- [x] `onDomainChange()` for `Scale`s -- currently `Scale`s use `Broadcaster`s
- [x] `Dispatcher`s also use `Broadcaster`s.
- [x] Remove `Broadcaster` from datasets
- [x] Remove `Broadcaster` (after the previous three items are complete)
- [x] `Interaction`s currently use `onEvent(null)` instead of `offEvent()` to remove callbacks.
- [x] <del> `addDataset()` + `removeDataset()`: should take in the `Dataset` directly instead of a key (this one might be hard enough to warrant a separate issue)</del> --> #1974
- [x] `domainer` use ids
- [x] Remove `PlottableObject` because we no longer need the IDs. 

One thing to remember is  
```Typescript
var clipPathId = (<any> c)._boxContainer.node().getElementsByTagName("clipPath")[0].getAttribute("id");
```
does fail on PhantomJS. It works on all other browsers though. Reverted it to 
```typescript
var clipPathId = (<any>c)._boxContainer[0][0].firstChild.id;
```

**Comment by aicioara** [comment]
Picking this up

**Comment by jtlan** [comment]
@aicioara , I've taken on #1974. It's as hard as I was afraid it might be...

**Comment by aicioara** [comment]
The ID is now only used on the scale `domainer`
