### ISSUE TITLE
Remove "package-protected" fields

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1917]
We have a number of fields in our classes that look like this:
```Typescript
public _packageProtectedField;
```
We should make them fully `public`, `protected`, or `private. This may be tricky for some things, such as the layout code -- those will receive separate subissues.

**Comment by aicioara** [comment]
Will not affect things regarding `Drawers` and `Domainers`

**Comment by aicioara** [comment]
Please close when https://github.com/palantir/plottable/issues/1913 and https://github.com/palantir/plottable/pull/2150 merge in
