### ISSUE TITLE
Remove weird label break in table.ts

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#1920]
Was brought up during the API review. It is weird and can be avoided.

![screen shot 2015-04-25 at 5 50 00 pm](https://cloud.githubusercontent.com/assets/3248682/7335438/87613092-eb73-11e4-965b-5e5249357143.png)

**Comment by jtlan** [comment]
This code is really ridiculous if you look at it, since after you find `component` it can just stop:
```Typescript
for (var r = 0; r < this._nRows; r++) {
  for (var c = 0; c < this._nCols; c++) {
    if (this._rows[r][c] === component) {
      this._rows[r][c] = null;
      return;
    }
  }
}
```
