### ISSUE TITLE
Un-skip tests

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1921]
A number of tests are currently being skipped, which makes it harder to see if we've screwed something up during the refactor. We should un-skip any skipped tests.

**Comment by aicioara** [comment]
On it. Tests are failing for various reasons (old browser config in SauceLab, TODOs, weird measurements in FF), so trying to fix them all.

**Comment by aicioara** [comment]
Could not eliminate one skiptest because of this https://github.com/palantir/plottable/issues/2003

**Comment by aicioara** [comment]
Blocked by #2003

**Comment by aicioara** [comment]
Reopen the PR #2127 and continue once unblocked

**Comment by aicioara** [comment]
Eliminated all. Blocked by 
#2164
When done open PR here https://github.com/palantir/plottable/compare/unskipTests3?expand=1
