### ISSUE TITLE
[Style] Final touches - indentation, folder structure and method order

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#1942]
Final touches:
- [x] indentation ![screen shot 2015-04-29 at 5 29 05 pm](https://cloud.githubusercontent.com/assets/3248682/7404291/587bbba6-ee95-11e4-8cb1-46ed152bf468.png)
- [x] Plots should not be inside the components folder - as per module hierarchy
- [ ] Public first, protected after. They are so mixed up in the plottable.d.ts file. I think it makes sense to move protected after public. Private is not so much a big deal and it might make sense to keep them.

**Comment by bluong** [comment]
It'll be on its way.  We either want to do this immediately or last.  I'm planning to have this done on apiRefactor ASAP

**Comment by aicioara** [comment]
hmm, sure but keep in mind that this is a change that affects over 90% of the code, so everything everyone is working on will be a continuous merge conflict. I'd do this last

**Comment by bluong** [comment]
Someone eventually will have to deal with conflicts so it doesn't matter too much when it happens as long as the changes are all at once (you definitely don't want continuous pull requests for this sort of thing.  it'll be really silly).

I would prefer that we do this sooner as a planned refactor/reformat that's pushed off means more tech debt.

**Comment by rcchen** [comment]
It's literally just adding two spaces to every single line other than the first and last one. I think we should wait off on this one and make it one of the last things that we touch.

**Comment by aicioara** [comment]
Maybe as part of this you want to also move the public methods at the top, protected methods after and private at the bottom, since this is another super conflicting change

**Comment by aicioara** [comment]
Merged multiple issues here since this should be done in 1 pass

**Comment by aicioara** [comment]
Regarding the method shuffle. 

### Regex for matching a full method
```regex
(?<=\n\n)((?!\n\n)[\s\S])*public[^\{]*((?!(\s*public|\s*private|\s*protected|\s*/\*))[\s\S])*
```

**Comment by aicioara** [comment]
There's no nice regex to do the public, protected bit. The above crashes sublime

**Comment by aicioara** [comment]
Will postpone that as it does not justify the effort

**Comment by bluong** [comment]
I personally think it does justify the effort, albeit we need to enlist a tslint rule to aid the enforcement

**Comment by aicioara** [comment]
Which does not exist at the moment
