### ISSUE TITLE
Interaction.PanZoom causes scrollbars to appear on IE9

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1944]
![panscrollbar](https://cloud.githubusercontent.com/assets/1440449/7406245/054e4d26-eeb4-11e4-9efc-c4ef7dbaa41c.png)

Repro: http://jsfiddle.net/5dkaqt4e/1/ (open in IE9). Pan data off the visible _window_ area.

**Actual**: Panning data off the visible area in the window causes scrollbars to appear, as though the `<svg>` changed sizes.
**Expected**: Panning doesn't have that effect.

**Comment by aicioara** [comment]
Repro http://jsfiddle.net/5dkaqt4e/4/

**Comment by hellochar** [comment]
Not happening in ie11 anymore (updated for 3.x - http://jsfiddle.net/hellochar/5dkaqt4e/5/)
