### ISSUE TITLE
get Selection and data at point / in range

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#1959]
Similar to `getBars()`, users should be able to get the `D3.Selection`s and data at a particular `Point` on a `Plot`, or in a x and y range.

- [x] Plots.Pie: #2340
- [ ] Plots.Rectangle
- [ ] Plots.Scatter
- [x] Plots.Bar
- [ ] Plots.Segment

**Comment by jtlan** [comment]
Partial Progress at #1787.

**Comment by dbt** [comment]
Is this done for 1.1 or is there more work to be done in v1.2?

**Comment by rcchen** [comment]
The ask this week was for `Plots.Pie` explicitly I think; there are still a number of other plots that this needs to be enabled for (tracking at top)

**Comment by christinaforney** [comment]
Christina to break this into actionable pieces

**Comment by jtlan** [comment]
Done:
`Rectangle`'s `entitiesAt()`
`Scatter`'s `entitiesIn()`

**Comment by christinaforney** [comment]
Broken into separate issues:
https://github.com/palantir/plottable/issues/2572
https://github.com/palantir/plottable/issues/2571
https://github.com/palantir/plottable/issues/2570
https://github.com/palantir/plottable/issues/2569
