### ISSUE TITLE
Static Labels on Pie Plots

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#1970]

**Comment by crmorford** [comment]
Testing Notes:
* Labels have a smart default color per slice, or color is easy to modify on a slice-by-slice basis.
* Labels are 'centered' on each slice, in large pie plots (design)
* Labels are truncated on small pie plots if they don't fit
* On pie plots with a hole in the middle, labels still look acceptable

**Comment by jtlan** [comment]
Subissue of #1959.

**Comment by jtlan** [comment]
A few questions:
 * Are the labels just numbers, or arbitrary strings? Should the users expect line-wrapping for long labels?
 * For thin slices, would the text just not show?

**Comment by rcchen** [comment]
Looks like https://github.com/mbostock/d3/wiki/SVG-Shapes#arc_centroid can be used for on-slice labels.
