### ISSUE TITLE
Rename all the remove to delete

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#1982]
We need to be consistent in our API naming. I see in public methods that we use both `remove` and `delete` as a keyword. We should choose one (I believe `delete`) and refactor it everywhere
Example
`domainer.ts:97` -> `Domainer.removePaddingException(key: any)` (not yet on apiRefactor branch)
`ComponentContainer.remove()`
`Set.delete()`

**Comment by aicioara** [comment]
@jtlan Please add appropriate label if you believe it is part of the `apiRefactor`

**Comment by dbt** [comment]
Why prefer delete to remove?

**Comment by aicioara** [comment]
I don't have a preference. We should be consistent. Currently we have a mixture

**Comment by aicioara** [comment]
https://github.com/palantir/plottable/blob/develop/src/utils/set.ts#L23
https://github.com/palantir/plottable/blob/develop/src/drawers/drawer.ts#L53

**Comment by bluong** [comment]
Note that `Set` uses `delete()` because that is part of the ES6 spec https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by jtlan** [comment]
Same for `Map`.

**Comment by aicioara** [comment]
Makes sense. Closing as solved
