### ISSUE TITLE
Combine two scales

### ISSUE THREAD

**Issue by tongcx** [palantir/plottable#1992]
Is it possible to combine InterpolatedColor and ModifiedLog so that it will use color after logscale?

**Comment by crmorford** [comment]
When you construct the ColorScale, you can pass in the colorRange, and ScaleType:
We don't support modifiedLog yet, but you could try this!

```javascript
scale = new Plottable.Scale.InterpolatedColor("reds", "log");
```

Let us know if this works for you :)

**Comment by rcchen** [comment]
Note that the new syntax for this as of v1.0.0 is the following

```javascript
scale = new Plottable.Scales.InterpolatedColor("log");
scale.range(Plottable.Scales.InterpolatedColor.REDS);
```

Closing for now due to inactivity. If you have any other questions, feel free to leave a comment or visit our [Gitter](https://gitter.im/palantir/plottable) room!
