### ISSUE TITLE
Legend text is truncated when given a trailing newline

### ISSUE THREAD

**Issue by istarnx** [palantir/plottable#1998]
![screen shot 2015-05-07 at 7 48 29 pm](https://cloud.githubusercontent.com/assets/11776100/7529769/6d77a872-f4f2-11e4-94eb-37db5fa89d90.png)

In the screenshot, the legend entry's text is "dataset1\n". I would expect trailing whitespace to be ignored.

**Comment by crmorford** [comment]
Testing Notes:
* Have 3 legend entries all with newlines, make sure top/middle/bottom all show up the same
* Have 3 legend entries, bottom with newline, make sure it shows up correctly
* Works as expected for horizontal and vertical legends
* Works for short words and long words / sentences
* Works with other types of whitespace at end (space/tab/etc)

**Comment by aicioara** [comment]
Repro:
http://jsfiddle.net/f2L94hg2/1/
http://jsfiddle.net/f2L94hg2/

Note that whitespace `\s` `\t` is trimmed. `\n` is not.

**Comment by aicioara** [comment]
Use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

**Comment by CalvinFernandez** [comment]
#3172 should provide a means of resolution
