### ISSUE TITLE
[Plots.Line] - allow for arbitrary xScale/yScale arguments

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#2003]
The constructor restricts these two arguments to be of `QuantitativeScale` but they can totally be used for ordinal purposes like in `CategoryScale` and we in fact use this fact in our quicktests.  Let's loosen the binding.

**Comment by jtlan** [comment]
#1507 would eliminate the need for this, although the typing on the `x()` and `y()` property setters would have to be carefully adjusted.

**Comment by aicioara** [comment]
Done, but blocked by 
#2164
When finished, open PR here https://github.com/palantir/plottable/compare/unskipTests3?expand=1

**Comment by aicioara** [comment]
Moving this to RC4. It is just a method signature change, but there's no need to rush through it. It has been implemented in the bigger PR above
