### ISSUE TITLE
Enable Selection and PanZoom at same time

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2011]
Options:
1. zoom with scrollwheel, and if you click-drag on the axis, that's panning. but click-drag on the plot is selection
2. click-drag is always panning, and to do selection you have to do something like hold CTRL key while you click+drag

1 is probaby the better option, because of mobile users

**Comment by aicioara** [comment]
@crmorford 

How would option 1 work for mobile users? Do we consider those? Do we have any feature request for this?

**Comment by jtlan** [comment]
I feel like resolving the conflict is he responsibility of the user -- Plottable's `Interaction` structure should be modular enough to resolve this in a way the user considers appropriate.

**Comment by crmorford** [comment]
Closing.
In order to get both, you have a few options.

1. Select in the Plot Area, and put PanZoom on axes. The downside of this is that PanZooming over axes is pretty unintuitive.

2. Have a button that toggles PanZoom with a dragbox. The downside of this is that you have to add infrastructure around Plottable Plots in your app to be able to switch.

3. If supporting mobile isn't important, toggle PanZoom and Selection with a key interaction.
