### ISSUE TITLE
Utils Refactor

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2024]
There is some inconsistency in the Utils package.

For Example, `Formatters` is under the `Utils` package, but it is not invoked as `Utils.Formatters`. -> put under module

Also the `utils.ts` file is actually a file of `Methods`, so all methods here are invoked as `Utils.Methods.method` -> filename change

**Comment by aicioara** [comment]
@jtlan What do you think?

**Comment by bluong** [comment]
I am currently highly under the opinion that maybe we should first-class some of these `Utils` functions similar to how D3 first-classes their array utility functions, for example.

**Comment by aicioara** [comment]
I agree with that as well

**Comment by jtlan** [comment]
+1 for making the directory structure match the module struture.

I think `Formatters` should stay as a top-level module.

Renaming **utils.ts** --> **methods.ts** (or **utilMethods.ts**) seems fine by me.

**Comment by aicioara** [comment]
For consistency *methodUtils.ts* instead of *utilMethods.ts* (like *domUtils.ts*)
