### ISSUE TITLE
Poor and unclear documentation of label orientation

### ISSUE THREAD

**Issue by istarnx** [palantir/plottable#2048]
Can you guys make it easier to understand the direction in which labels will render? 

This has no description for "orientation":
http://plottablejs.org/docs/classes/plottable.component.axislabel.html#constructor

...and this is unclear: ("The orientation of the Label (horizontal/left/right) (default = "horizontal")")
http://plottablejs.org/docs/classes/plottable.component.label.html#constructor

Really, we're talking about the rotation of the text:
- 0 deg (default, horizontal left-to-right), 90 deg (vertical top-to-bottom), and -90 deg (vertical bottom-to-top)

Ideally, these would be (self-documenting...) string constants with some description... somewhere. :)

**Comment by jtlan** [comment]
Another possibility is to take a `number` the same way `tickLabelAngle()` (on `Axes.Category`) does.
