### ISSUE TITLE
StackedPlot refactor

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2051]
Or transform it into a set of utils

**Comment by jtlan** [comment]
In more detail:

There is a diamond problem where `StackedArea` extends `Area`, `StackedBar` extends `Bar`, but both share logic for stacking values. Currently we do some weird mixin-like logic to get this to have `StackedArea` and `StackedBar` "extend" `StackedPlot`, but it would be more elegant if `StackedPlot` was a `static` grouping of utility methods or something where inheritance wasn't required.
