### ISSUE TITLE
Get rid of PlotMetadata

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2056]
Right now the signature for `Accessor` looks like this:
```Typescript
(datum: any, index?: number, dataset?: Dataset, plotMetadata?: Plots.PlotMetadata) => any
```

The PlotMetadata is internal information and shouldn't be exposed to the user.

**Comment by aicioara** [comment]
This was closed here I believe https://github.com/palantir/plottable/pull/2114
@bluong  ?

**Comment by bluong** [comment]
Yep this has been completed I should have referenced
