### ISSUE TITLE
`Plots.Line` and `Plots.Area` should take a generic for Y

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2064]
Currently the signature for the two classes look like this:
```Typescript
export class Line<X> extends XYPlot<X, number>
export class Area<X> extends Line<X>
```

But the type shown on the Y-axis doesn't have to be a `number`, so the signatures should take a second generic.

**Comment by bluong** [comment]
Currently we are running with the idea that the `Y` domain should always be numbers
