### ISSUE TITLE
Confusing behavior when Linear Scale given strings

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2103]
given strings like "06.14", "14.34" projected onto the yAxis, if you forget to convert them to numbers, the plot has weird behavior instead of giving an understandable error.

Example of when this happens: using data from a csv, try to project the strings without converting them to doubles.
```
 d3.csv("../overlaying/tests/baseball.csv").get(function(error, rows) {
  var data = rows; 
  var dataset = new Plottable.Dataset(data);

  console.log(data);

  var xScale = new Plottable.Scales.Linear();
  var yScale = new Plottable.Scales.Linear();
  var xAxis = new Plottable.Axes.Numeric(xScale, "bottom");
  var yAxis = new Plottable.Axes.Numeric(yScale, "left");
  
  var plot = new Plottable.Plots.Area(xScale, yScale);
  plot.addDataset(dataset);
  plot.x(function(d){ return d.season; }, xScale)
      .y0(function(d){ return d.low; }, yScale)
      .y(function(d){ return d.high; }, yScale);

  var table = new Plottable.Components.Table([[yAxis, plot],
                                             [null, xAxis]]);
  table.renderTo(svg); 
```
![screen shot 2015-05-19 at 11 29 47 am](https://cloud.githubusercontent.com/assets/7527733/7710712/7a8fe020-fe1a-11e4-813d-b02d6dc4b7d8.png)

**Comment by aicioara** [comment]
@crmorford can you provide a fiddle please?

**Comment by aicioara** [comment]
I also suspect this is no longer valid due to a `v1.0.0` fix

**Comment by crmorford** [comment]
In baseball.js, remove the + in front of each d.attr in lines 17-21.
This isn't happening anymore.
