### ISSUE TITLE
Top tick on yAxis sometimes gets cut off

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#211]
Probably being drawn outside the SVG.
![screen shot 2014-03-18 at 4 30 10 pm](https://f.cloud.github.com/assets/1440449/2454975/58565680-aef5-11e3-86a5-5308a2184943.png)

**Comment by rcchen** [comment]
Hey @crmorford I think this doesn't happen anymore after poking around in Firefox and Chrome. @jtlan  suggested asking you to check it out to verify that this can be closed out. Relevant line is https://github.com/palantir/plottable/blob/v0.42.0/src/components/abstractComponent.ts#L54

**Comment by crmorford** [comment]
Yeah, I haven't seen this in a while. Closing.
