### ISSUE TITLE
Chaining API is inconsistent across the codebase

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#2119]
Currently blocking on the following TypeScript issues

- https://github.com/Microsoft/TypeScript/issues/275
- https://github.com/Microsoft/TypeScript/issues/285

**Comment by aicioara** [comment]
@rcchen is this still valid?

**Comment by aicioara** [comment]
Can you point to the code base ?

**Comment by rcchen** [comment]
Still valid; the easiest repro for this is chaining a method for a parent class on a subclass.

Example: `new Plottable.Plots.Rectangle().x().x2()..`

If `.x()` were not explicitly defined on `Plots.Rectangle`, `.x2()` would not work.

This is an open issue on Typescript as has been referenced above.

**Comment by aicioara** [comment]
Closing as duplicate
