### ISSUE TITLE
[Pixel Perfect] Solve failing FF tests on Windows and Linux SauceLabs browsers

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2122]
Some thoughts on this can be found here https://github.com/palantir/plottable/pull/2121
In particular:
- The `SVGTypeWriter` uses `getBBox()`, while our tests use `getBoundingClientRect()`, in order to get the `width` and `height` of elements and to test inclusion. These give the same values on Chrome and IE9, but they are different in FF, and even worse they are different between Windows and Linux (I believe because of the screen resolution and rounding issues)

If Implementing this: use the Windows for the VMs (as most of our users do) and bring the CloseTo requirement back to 1

``` typescript
  if (isFirefox) {
    window.Pixel_CloseTo_Requirement = 1;
```

**Comment by aicioara** [comment]
This argument in the Gruntfile might be useful
```typescript
"screen-resolution": SCREEN_RESOLUTION,
```

**Comment by aicioara** [comment]
Also, we might want to use the Windows version of both Chrome and FF browsers

**Comment by hellochar** [comment]
"Fixed" this by increasing tolerance to 2; not a huge deal if we're a bit off across browsers
