### ISSUE TITLE
Enhancement Request: Formatter on legend

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2125]
I want to make it obvious these are percents
![screen shot 2015-05-20 at 4 11 58 pm](https://cloud.githubusercontent.com/assets/7527733/7738565/0ad409cc-ff0b-11e4-870f-140b66fb6cf6.png)

**Comment by jtlan** [comment]
We've also had requests to display a different name on an ordinary `Legend` than then values in the `Scales.Color`'s domain.

**Comment by joyt** [comment]
We would also like to have the feature to have "vanity" names on color scales!

**Comment by rcchen** [comment]
@joyt could you clarify "vanity" names? Perhaps with a mockup/screenshot or something? Thanks!

**Comment by joyt** [comment]
Basically the ability to specify, either through a map or in the underlying data, a human-friendly/readable name for a given series. It could be part of the API for Legend or for ColorScale. Possible example (not neccesarily the best format):
```javascript
var data = [
{id: 'jtao', name: 'Joy Tao', score: 13},
{id: 'mschafer', name: 'Mark Schafer', score: 15},
{id: 'kfalter', name: 'Kelsey Falter', score: 11}
]
The chart should use "name" as the display name for legends, axis labels but use "id" to identify the series (multiple series could have the same "name" value)

**Comment by jtlan** [comment]
`InterpolatedColorLegend` already has a `formatter()` API point.
