### ISSUE TITLE
Labels on Plots.Rectangle

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2126]
I wanna put the values in these boxes
![screen shot 2015-05-20 at 4 13 32 pm](https://cloud.githubusercontent.com/assets/7527733/7738572/318c4cfa-ff0b-11e4-81ee-568fd2cbe082.png)
A lot of plots online do this. It seems like a very common use case

**Comment by rcchen** [comment]
@crmorford do you happen to know where the labels are optimally placed? I'm defaulting to direct center (both vertical and horizontal) but if it should go somewhere else.

**Comment by crmorford** [comment]
DIrect center sounds good to me

**Comment by crmorford** [comment]
Testing Notes:
* Labels disappear if they don't fit vertically
* Labels disappear if they don't fit horizontally
* Font and Size are changeable with css

**Comment by rcchen** [comment]
Note to self: this feature only makes sense if a fill accessor is set.

**Comment by jtlan** [comment]
> Note to self: this feature only makes sense if a fill accessor is set.

You could have labels with no fill, but that might be kind of odd.

**Comment by ztsai** [comment]
should we add an API to let user to set label accessor in addition to having ```labelsEnabled```

**Comment by jtlan** [comment]
Something like this?
```Typescript
public labels(labels:Accessor<string>)
```

**Comment by bluong** [comment]
> should we add an API to let user to set label accessor in addition to having ```labelsEnabled```
I think having the API point is useful
