### ISSUE TITLE
getClosestDataPoint() and Dataset metadata

### ISSUE THREAD

**Issue by bmsq** [palantir/plottable#2157]
Hi,
I've been using plottablejs (great work!) with a column based data library like Miso dataset and datavore.  So far, I've tried to avoid duplicating data by setting the data() attribute of plottable Datasets to the "Index" column and adding the other columns as Dataset metadata. 

Therefore, most of my project() calls looks something like this:
```
plot
	.project("fill", function (d, i, m) { return m.series; }, colour)
	.project("x", function (d, i, m) { return m.category[d]; }, xScale)
	.project("y", function (d, i, m) { return m.value[d]; }, yScale)
```

Unfortunately, I've just attempted to add hover interactions to my plots and discovered that there is no way to access the dataset metadata from a call to getClosestDataPoint().  Since the returned data is only an index, I can't see how I could access the desired column data (ie. metadata.value[closest.data]).

Is it possible to make the Dataset metadata available through getClosestDataPoint()? 

Alternatively, am I doing this wrong? Should I be changing my approach and transform my column orientated source data structures to row orientated Datasets even if requires duplicating data each time the source is updated?

Thanks,
bmsq

**Comment by jtlan** [comment]
Hi @bmsq,

As part of our refactor for v1.0.0 we're improving the return type of our closest-point methods in #2168. After that pull request makes it to a release version, the closest-ponit methods will now return this object:
```Typescript
export type Entity = {
  datum: any;
  index: number;
  dataset: Dataset;
  position: Point;
  selection: D3.Selection;
  plot: Plot;
}
```
You should then be able to use the `dataset` field to retrieve the relevant metadata.

If you're interested in trying out the new functionality ahead of schedule, you can check out the 1.0.0 Release Candidates; a Release Candidate with the new `Entity` type should be available later this week.

Let us know if the new type solves the problem.

**Comment by bmsq** [comment]
Thanks jtlan, 

I've been watching progress since integrating plottable with my project but I hadn't seen the linked issue. Providing the dataset and row index is a nice touch as it doesn't make any assumptions about how plottable is being used.

After stumbling across Dan Mané's talk about there being so many charting libraries, I ditched my hand rolled D3 code in preference of plottable. Its been almost 6 months and I still think plottable is the perfect mix of flexibility, easy of use and encapsulation.

I love this library. Well done to everyone involved, I'm looking forward to migrating to v1.0 :)

Cheers,
bmsq
