### ISSUE TITLE
Plot.animate() should also function as a getter.

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2185]
And possibly renamed. "`animated()`"?

**Comment by bluong** [comment]
Boolean parameters are bad, can we find a way to factor this endpoint to not take in a boolean?

One way could be to split this into 3 endpoints, one that's like `animate(true)`, one for `animate(false)` and one for the boolean getter.

**Comment by aicioara** [comment]
How do we specify the type of animation right now? Do we actually have different types?

**Comment by jtlan** [comment]
@aicioara wrote:
>How do we specify the type of animation right now? Do we actually have different types?

That's done using the `animator()` API point:
```Typescript
/**
 * Get the Animator associated with the specified Animator key.
 *
 * @return {Animators.Plot}
 */
public animator(animatorKey: string): Animators.Plot;
/**
 * Set the Animator associated with the specified Animator key.
 *
 * @param {string} animatorKey
 * @param {Animators.Plot} animator
 * @returns {Plot} The calling Plot.
 */
public animator(animatorKey: string, animator: Animators.Plot): Plot;
```

The `animate()` API point is merely intended for enabling or disabling the animations set on the `Plot`. Since there's only two possible states, I think a `boolean` is fair here.

**Comment by aicioara** [comment]
What I am thinking is: do we need this API end point in the first place? Shouldn't specifying an animator imply an animation is needed, and just add a `noAnimation` endpoint, which acts like `removeAnimator`

**Comment by jtlan** [comment]
>Shouldn't specifying an animator imply an animation is needed

Not quite, since you might want to specify a particular type of animator, but then switch animation on/off independently of that. This is particularly important because the `Plot`s ship with default animators unique to the `Plot` type, and the user shouldn't have to think about the correct timings to get a nice visualization.
