### ISSUE TITLE
getClosestPlotData() should use an efficient data structure

### ISSUE THREAD

**Issue by istarnx** [palantir/plottable#2195]
We're using getClosestPlotData() for interactive tooltips and the performance just isn't cutting it. The implementation should use an efficient space-partitioning data structure (i.e., kd-tree) to reduce query time to O(log n).

**Comment by aicioara** [comment]
Fiddled http://jsfiddle.net/9emes3ud/1/

**Comment by aicioara** [comment]
Initial perf for 1471 points is `660 ms` on average

**Comment by derekcicerone** [comment]
Is that the baseline? Sorry, not sure how to interpret that result...

**Comment by aicioara** [comment]
Those are just notes for me as I go along. 

The above means: if you open the jsfiddle, select 1471 points to display, the time required to get the closest datapoint is 660ms on my machine. Full overview will be available with the Pull Request for this

**Comment by derekcicerone** [comment]
Ah ok cool, wasn't sure if I was supposed to respond :)

**Comment by aicioara** [comment]
Managed to reduce the time of this downto `1-4 ms`.

`600x` speedup

**Comment by derekcicerone** [comment]
:100:

**Comment by aicioara** [comment]
In case we need a k-d-tree data structure in the future, I was recommended this https://github.com/mourner/rbush-knn. (suggested by @uschi2000 )

At the moment the extra dependency and the engineering time is not justified.
