### ISSUE TITLE
[Drawer] - Exported types are possibly a little odd

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#2196]
There are exposed types that are pretty `Drawer` specific and I'm unsure if they should be exposed.

Namely
`DrawStep` and `AppliedDrawStep`

**Comment by aicioara** [comment]
They are `Drawer` specific, but they are used in `Plots` as well. For example `AreaPlot._generateDrawSteps()` which returns an array of `Drawer.DrawSteps`. The fact that it is encapsulated inside the `Drawers` module seems good enough.

**Comment by aicioara** [comment]
Won't fix. @jtlan opinion?

**Comment by jtlan** [comment]
`DrawStep` makes sense, but it's weird that `AppliedDrawStep` also exists.

**Comment by aicioara** [comment]
So the issue we face is the following. 
- `AppliedDrawStep` is used inside the `protected _drawStep` method only. This method is protected, but there is no way to bring a type (or interface for what matters) to this visibility level. 
- If someone wants to extend the class, they need to have knowledge of the `AppliedDrawStep`
- We cannot declare the type as being non exported and then reference it to an exported method (protected). Hence, we have to explicitly type the type in the definition, which is super ugly.

Conclusion: won't fix

**Comment by jtlan** [comment]
Okay, sounds good to me.
