### ISSUE TITLE
[Drawer] - the `draw()` endpoint should return this

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#2197]
The `draw()` endpoint is inconsistent in that it draws stuff to the DOM and returns the time it takes to draw.  `draw()` maybe should be more consistent and return `this` but then the time idea is important.  There might be a need to get the time it takes to draw in another endpoint

**Comment by aicioara** [comment]
Why would we want to return `this`? Is this the only API point which does not behave like that?

**Comment by jtlan** [comment]
Most state-changing API points return `this`; Consider the getter-setter combos on most Plottable objects. From a consistency standpoint most state-changing methods on `Drawer`s would return `this` too, but they don't.
