### ISSUE TITLE
[Drawer] - underscored endpoints should be removed or publicized

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#2198]
There are three public endpoints that are underscored.  They should be removed or actually publicized.

Note that their main usage is in `getAllSelections()` `entities()` and `closestEntity()`

**Comment by aicioara** [comment]
> ```Typescript
> public _getRenderArea();
> public _getSelector();
> public _getSelection(index: number);
> ```
>
> Should probably just become public, and the "get" removed.
