### ISSUE TITLE
[Typings] Update to the latest d3.d.ts

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#2200]
https://github.com/borisyankov/DefinitelyTyped/pull/4032 adds generics to the D3 typings file. In addition, the module is no longer named "D3", and is instead named "d3". As a consequence, a nontrivial amount of Plottable code needs to be fixed. 

This is important because #2163 introduced a D3 typings file into our repository that we were planning to merge back into DefinitelyTyped, but now we have a divergence that won't make it into DefinitelyTyped.

**Comment by jtlan** [comment]
Closed in ##2212.
