### ISSUE TITLE
[Component] classed() endpoint

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2219]
The `classed` endpoint. [jQuery](https://api.jquery.com/addclass/) [is](https://api.jquery.com/hasclass/) [nicer](https://api.jquery.com/removeclass/)

Our current implementation:
```typescript
    /**
     * Checks if the Component has a given CSS class.
     *
     * @param {string} cssClass The CSS class to check for.
     */
    public classed(cssClass: string): boolean;
    /**
     * Adds/removes a given CSS class to/from the Component.
     *
     * @param {string} cssClass The CSS class to add or remove.
     * @param {boolean} addClass If true, adds the provided CSS class; otherwise, removes it.
     * @returns {Component} The calling Component.
     */
    public classed(cssClass: string, addClass: boolean): Component;
```

Pros: 
- Consistent with `d3.classed()`

Cons:
- It is ugly
- It has a boolean as a parameter

**Comment by jtlan** [comment]
The consistency of it with D3 is a good thing. However, renaming it would free up the name `class()` for a property-setter on `Plot`s (setting the `class` with `attr()` is a mess, because you can't preserve existing classes).

**Comment by aicioara** [comment]
Can you elaborate on why the consistency with D3 is a good thing?

**Comment by jtlan** [comment]
Plottable is built on top of D3, so it makes sense to align with D3's semantics so that users familiar with D3 can pick up Plottable easily.

**Comment by aicioara** [comment]
@jtlan Okay, I guess the conclusion is we don't want this change?

**Comment by aicioara** [comment]
In that case, the type definition has to be changed to match [D3](https://github.com/mbostock/d3/wiki/Selections#classed)

**Comment by jtlan** [comment]
@aicioara wrote:
>In that case, the type definition has to be changed to match D3

How does it currently differ? Is it just that we're missing the object setter?

**Comment by aicioara** [comment]
The value can be a function which can be evaluated to true/false not necessarily a constant boolean

**Comment by aicioara** [comment]
Question is: do we want this signature:

```typescript
classed(name: string): boolean;
classed(name: string, value: boolean): Update<Datum>;
classed(name: string, value: (datum: Datum, index: number) => boolean): Update<Datum>;
classed(obj: { [key: string]: boolean | ((datum: Datum, index: number) => boolean) }): Update<Datum>;
```

I could implement it if we believe it is necessary

**Comment by jtlan** [comment]
Since `classed()` only applies the class to a single `Component`, the signature with the function parameter isn't really helpful.

**Comment by aicioara** [comment]
Closing this as won't fix. There is not much value in trying to imitate all the methods from `d3`. Also we can add it in the future if we really need.

**Comment by aicioara** [comment]
This discussion is still on?

**Comment by danmane** [comment]
+1 for leaving it the way it is. consistency with d3 is important, since plottable is intimately tied and (in my mind) philosophically extends from d3. i don't think consistency with jQuery is important especially since it seems jQuery is becoming increasingly irrelevant. 

you could modify the fn signature to perfectly match d3 api as proposed above, imo its a bit pedantic since it's not useful in this context, adding in the additional handling can be done without breaking backcompat so there's really no rush...

**Comment by aicioara** [comment]
Although I have been a great fan of not having `.classed()` it seems like we cannot completely remove it from the codebase, because we still use it on all `d3` selections. Now we would have a mixture, which I did not predict beforehand. RFC on the PR

**Comment by jtlan** [comment]
I think it's fine for our outward-facing API to differ from the D3 `classed()` call used inside the codebase.

**Comment by aicioara** [comment]
Fair enough

@danmane We had a RFC discussion about this change and got 4+ people in favor, so will go with the change
