### ISSUE TITLE
tickLength call only changes inner ticks

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2227]
I'd think that calling tickLength(0) should get rid of all ticks, but it leaves the outer ticks, so you also have to call endTickLength(0);
this feels incorrect to me.

see: http://jsfiddle.net/v20vw15v/; ticks super bold for emphasis

**Comment by jtlan** [comment]
Hmm. What happens if the user wants to set the end-tick length too?
```Javascript
axis.endTickLength(20);
axis.tickLength(0); // negates the above line
```
Now there's the chance for unexpected behavior depending on the order of operations.

Should we maybe rename the method to `innerTickLength()`?

**Comment by crmorford** [comment]
ah a rename would work for me :)
