### ISSUE TITLE
Pie plots cut off in certain layouts

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#2244]
![image](https://cloud.githubusercontent.com/assets/1175041/8026506/d80f57cc-0d2d-11e5-9975-bd23a2bfe0bb.png)

As seen in the above screenshot, the left and right sides are cut off slightly. I suspect this is related to table autolayout.

**Comment by jtlan** [comment]
No, I think it's because the `Plots.Pie` in that example have hardcoded radii:
```Typescript
...
ABplot.innerRadius(50);
ABplot.outerRadius(100);
...
```

**Comment by rcchen** [comment]
Got it, closing out.
