### ISSUE TITLE
[Animator.Base] methods names have to be refactored

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2246]
Playing with the methods inside the Base Animator, lots of things did not work as expected. That is because poor documentation and non descriptive method names. Fix for `1.0.0`.

In particular
- `maxIterativeDelay` -> `iterativeDelay`
- `maxTotalDuration` should win over `duration`
- `duration` sounds too much like a total Duration, when it is in fact animation per bar (in bar plot) (`stepDuration`)
- `delay` is actually the starting delay
- the `maxTotalDuration` has a non `Infinity` default
- All the numbers should be tested more thorroughly
- The overlaying tests should be repaired (for example `Plot.animator("bars", animator) ->       Plot.animator("main", animator)`)

**Comment by aicioara** [comment]
Also, why is there a `Plottable.Animators` and a `Plottable.Plots.Animator` module

**Comment by aicioara** [comment]
Suggestion:
- `delay()` -> `startDelay()`
- `duration()` -> `stepDuration()`
- `maxIterativeDelay` -> `delay()
- `maxTotalDuration` - stays the same
- `easing()` -> `ease()`

**Comment by jtlan** [comment]
`easing` should keep its name, since that's the conventional name for that concept.

**Comment by aicioara** [comment]
but the d3 version is called `ease()`

**Comment by bluong** [comment]
Agree with @jtlan , "ease" I'm decently sure is a verb, which means that if one does `animator.ease()` that implies that some ease action has taken place

**Comment by aicioara** [comment]
Cool so no `ease()`, how about the rest?

**Comment by bluong** [comment]
Why the change for `maxIterativeDelay`? And why is the change different from `maxTotalDuration`

**Comment by jtlan** [comment]
> Why the change for `maxIterativeDelay`? And why is the change different from `maxTotalDuration`

It's gotten you confused too, which is why the name change is necessary:
* In `maxTotalDuration()`, the "`max`" is meant to imply that the method sets a limit.
* In `maxIterativeDelay()`, the "`max`" is meant to imply that you might not get exactly the value you set...!

**Comment by aicioara** [comment]
Reason for all above
- `startDelay` I believe initially we wanted to imitate CSS API, but this does not work since we have animation steps as well and CSS does not
- `stepDuration`, that is not the duration for the entire animation, just for the singular bar (if we have a bar plot)
- `iterativeDelay` the reasoning for the initial naming was that this delay will be at most the value set here, and will be shorter if there is an upper bound (maxIterativeDelay). However, following this logic the duration should also have been called `maxDuration` since it cannot exceed the maxTotalDuration, right? Too much max and confusion is created
