### ISSUE TITLE
Fix the API Documentation on Google Chrome on OS X

### ISSUE THREAD

**Issue by cmslewis** [palantir/plottable#2253]
**Mac Version:** 10.9.5
**Chrome Version:** 43.0.2357.81 (64-bit)

*Expected (screenshotted from Safari on the same computer):*
http://postimg.org/image/vkbxhuivp/

*Actual (screenshotted from Chrome):*
http://postimg.org/image/4jaesqfmx/

**Comment by crmorford** [comment]
Thanks for letting us know! This works for me on Chrome 43.0.2357.81, so we may have to follow up with you to try and figure out what else is different.

**Comment by rcchen** [comment]
Hey @cmslewis, just wanted to loop back and check if this is still an issue with the new website. We updated plottablejs.org for 1.0, so things might work for you now.

**Comment by aicioara** [comment]
Checking on 
**Mac Version** 10.10.3
**Chrome Version** 43.0.2357.130 (64-bit)

**Comment by aicioara** [comment]
In the mean time, closing both issues, as `can't reproduce`, but please reopen when more information is available
