### ISSUE TITLE
Factory Methods should have a method called getInstance()

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2264]
ClientToSVGTranslator has a factory function with the “get” prefix in front. We may consider renaming the factory functions to possibly “getInstance”.

**EDIT:** Not sure if that is actually a standardized design pattern naming convention. TODO: look into it

**Comment by aicioara** [comment]
I looked into it
apparently `getInstance()` is mainly for singleton pattern
so I believe the old method names were fine
`getWhatever()` / `makeWhatever()` are totally fine for factory pattern

**Conclusion** I vote for `wontfix`

**Comment by bluong** [comment]
Thinking about it and I vote for wontfix as well
