### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2265]
We will need to do a documentation sweep as a large number of our exposed stuff is not well documented.

For now, we should aim for basic documentation on all of our public methods and once we have a basic sweep, we can refine this to have more nicely worded documentation.

Modules that need to be documented:

**please do not edit description, just check things on/off and comment as a separate comment**

- [x] Animators
- [x] Axes
- [x] Plots
- [x] Components
- [x] Utils (@aicioara)
- [x] Scales
- [x] Drawers
- [x] Interactions (@jtlan)
- [x] Dispatchers (@jtlan)
- [x] Misc (The stuff in the core directory containing like Formatters/Dataset/RenderController)

**Comment by aicioara** [comment]
the branch `docs` is aimed for this

**Comment by aicioara** [comment]
I'll take `Utils`

**Comment by bluong** [comment]
I got `Plots`

**Comment by jtlan** [comment]
`Dispatcher`s and `Interaction`s check out.

**Comment by aicioara** [comment]
Taking Animators

**Comment by aicioara** [comment]
Taking `Scales`

**Comment by aicioara** [comment]
`Scales` are fine

**Comment by jtlan** [comment]
Checking out `Axes`.

**Comment by aicioara** [comment]
Taking `Components`

**Comment by jtlan** [comment]
`Axes` check out.

**Comment by bluong** [comment]
Getting `Drawer`s

**Comment by aicioara** [comment]
`Components` are fine

**Comment by jtlan** [comment]
Going after `misc`.

**Comment by aicioara** [comment]
Ok, so that should be all

**Comment by jtlan** [comment]
`misc` checks out. Done?

**Comment by aicioara** [comment]
Waiting for my build to pass

**Comment by aicioara** [comment]
It merged

**Comment by jtlan** [comment]
We still need to merge `docs` into `develop`.
