### ISSUE TITLE
Dispatcher and Interaction refactor

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2268]
- [x] Dispatcher has an instance variable called _event2Callback.  We should change the “2" to a “To"
- [x] Dispatchers.Mouse.lastMousePosition should be explicitly typed to Point
- [x] Interactions.Key has “onKey” endpoints that should probably be renamed to something like “onKeyPress”
- [x] PanZoomInteraction has an exposed PIXELS_PER_LINE that should be looked at.
- [x] Interactions.Drag has a constrainToComponent() endpoint that should be renamed so that dragInteraction.constrainToComponent() more looks like a getter

**Comment by bluong** [comment]
Got all the checkmarks.
