### ISSUE TITLE
Animators refactor

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2269]
- [ ] The Animators all extend from Plots.Animator which seems really odd.
- [ ] The main Animator that a bunch of the Plots use is called Animators.Base, which is not a good name.

Changes: 
- `.iterativeDelay()` -> `.stepDelay()`
- `.easing()` -> `.easingMode()`
- `DEFAULT_EASING` -> `DEFAULT_EASING_MODE`
- `Animators.Plot` -> `Animator`
- `Animators.Base` -> `Animators.Easing`

**Comment by aicioara** [comment]
Suggestion:
- `Animators.Base` -> `Animators.Easing`
- `Animators.Plot` -> `Animator`

**Comment by crmorford** [comment]
Why "Easing", what does that mean?

**Comment by aicioara** [comment]
It is a type of animation. Anything that looks like this http://easings.net/

**Comment by jtlan** [comment]
For `Animator`s, we used to have `Animator.IterativeDelay`, which had most of the functionality that `Animators.Base` has now. We combined it with a simpler class since we realized that `IterativeDelay` was a strict superset of the functionality.

**Comment by aicioara** [comment]
You can hover over to see how it looks.

**Comment by jtlan** [comment]
I don't think `Easing` is a good name, since I'd argue the core functionality is not the easing part.

Renaming `Animators.Plot` to just `Animator` is a good idea though, since it seems general enough.

**Comment by aicioara** [comment]
`Animators.Step` ?
I actually like the easing because it reflects the way things are animated. Everything else is just extras to make it look better (have steps)

**Comment by rcchen** [comment]
Proposal: `.easing()` -> `.easingFunction()` since this is what it is defined as within D3

https://github.com/mbostock/d3/wiki/Transitions#d3_ease

**Comment by aicioara** [comment]
we decided to call it `.easingMode()`

**Comment by jtlan** [comment]
To clarify, we decided against "`easingFunction()`", since the method doesn't actually accept a `function`...!

**Comment by aicioara** [comment]
Wrote an RFC for this, but ended up not sending it since this is a low traffic API point. You can find it in the PR and bellow

**Comment by aicioara** [comment]
BLUF: We are considering changing the Animators.Base to something more appropriate.

We are considering renaming the Base Animator Animators.Base to an Easing Animator Animators.Easing. 

There are multiple reasons for that. 
There is nothing that extends the Base Animator at the moment.
`Easing` makes sense is because that is the type of animation this is implementing. http://easings.net/
It is in symmetry with `Animators.Null`, which is a no-op. the `Null` bit represents the no-op as an animation type, so `Easing` also represents the animation type here
However, it is a bit weird that the Easing animator also has logic for the steps timing and inter step delays.

Alternatives we have considered are
`Animators.General` 
`Animators.Default`
`Animators.Base` - old version
`Animator` - Conflict with the interface
`Animators.Easing` - top Choice
`Animators.Step`
`Animators.Iterative`

Unless there are better alternatives or strong opposition, we plan to stick with `Animators.Easing`.

Cheers,
Andrei @ Plottable
