### ISSUE TITLE
Scale Refactor

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2271]
- [ ] QuantitativeScale._DEFAULT_NUM_TICKS seems like it is not used and should be deleted.
- [ ] Possibly remove the colorRange constructor parameter from InterpolatedColorScale.

**Comment by bluong** [comment]
_DEFAULT_NUM_TICKS is actually found to be used to determine the number of ticks the default tick generation algorithm should return.

I personally am ok with leaving this variable in.

**Comment by aicioara** [comment]
Yeah, will leave it in
