### ISSUE TITLE
Utils.Set should use value equality

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2300]
`Date`s with the same value should be considered the same in a `Set`, but they aren't.

Link to spec: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Value_equality

Repro: http://jsfiddle.net/ahup9g56/

**Comment by jtlan** [comment]
Apparently the actual `Set` doesn't work this way. Should we still do this?

**Comment by aicioara** [comment]
We are now using the ES6 actual set underneath, hence there is no way we can still do this. Closing.
