### ISSUE TITLE
Logarithmic axes + Stacked bar plots don't show data correctly.

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2304]
JsFiddle http://jsfiddle.net/radbhdtL/1/

In this fiddle, the 'blue' and 'red' datasets have the exact same yValues for each xValue, and the yValues increase as the xValues do

Expected: The height of the blue bars increase as x increases, and the red and blue bars have the same height at each xValue

Actual: Blue bars are the same height at every value, and it isn't the same height as the red bars.

**Comment by jtlan** [comment]
>Expected: The height of the blue bars increase as x increases, and the red and blue bars have the same height at each xValue

Not exactly, since it's a `Scales.ModifiedLog`, but they should still show the correct value.

**Comment by crmorford** [comment]
wait WHAT

**Comment by crmorford** [comment]
I don't know enough math to QE this

**Comment by jtlan** [comment]
Looks like `StackedArea` renders this correctly, so it's a problem localized to `StackedBar`:
![screen shot 2015-06-29 at 1 51 31 pm](https://cloud.githubusercontent.com/assets/1440449/8418146/052a6b4a-1e66-11e5-8db3-44d6590c5db4.png)

**Comment by jtlan** [comment]
Making the bars transparent reveals the problem:
![screen shot 2015-06-29 at 1 58 50 pm](https://cloud.githubusercontent.com/assets/1440449/8418295/06fb0d02-1e67-11e5-815a-d60fbb378bb2.png)
