### ISSUE TITLE
Clearing out an <svg> breaks Interactions

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2335]
Calling `svg.text("")` (or equivalently, JQuery's `empty()` call, or `node.innerHTML = ""`, etc) causes any subsequent `Interaction`s in that `<svg>` to fail:

http://jsfiddle.net/o98de038/

Probably what's going on here is the `ClientToSVGTranslator`'s measurement nodes are being destroyed.

**Comment by jtlan** [comment]
Not sure how valid this bug is, since `destroy()` should be used to clear out Plottable `Component`s.

**Comment by adidahiya** [comment]
Closing as invalid; willing to re-open if there is a user need for a fix.
