### ISSUE TITLE
Submit Types for Math, Map and Set to DefinitelyTyped

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2339]
In order to reduce the number of `<any>` casts we perform in our codebase

**Comment by aicioara** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/3581

**Comment by aicioara** [comment]
There is an answer in that thread, but I can't seem to make it work for our project setup. 

On a single file, this works:
```typescript
interface Window {
  Math: typeof Math;
  Set: typeof Set;
  Map: typeof Map;
}

var x = window.Math.min(2, 3);

```

**Comment by bluong** [comment]
This sounds like a sensible solution to me.  we get the proper namespacing and things I think will work nicely.
