### ISSUE TITLE
Axes performance is bad

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2355]
As documented here https://github.com/palantir/plottable/issues/2352#issuecomment-113284978

**Comment by aicioara** [comment]
Taking this.
The slow function is `_hideEndTickLabels` Probably because it iterates through all the labels a couple of times to hide them. Need to rethink this logic

**Comment by aicioara** [comment]
Interesting. Apparently, the performance issue there is the `getBoundingClientRect()` on the bounding box, which needs `147ms`!!!

**Comment by aicioara** [comment]
When merging, make sure it does not conflict with https://github.com/palantir/plottable/issues/2210

**Comment by aicioara** [comment]
Actually, the profiler is a bit misleading. After a lot of research into this, I figured out on [this fiddle](http://jsfiddle.net/2apxs87q/1/) that performance of the axes cannot really be improved.

First diagram shows the performance without calling any reflow method (like `Axes.Numeric._hideEndTickLabels()`. It can be observed that the render time is significantly shorter, but there is a (program) time at the end. To be noted that the browser does not actually display anything until the (program) time is done.
![screen shot 2015-06-30 at 4 17 35 pm](https://cloud.githubusercontent.com/assets/3248682/8444310/1f8f56d8-1f44-11e5-93bf-25717108af45.png)


Second diagram shows the performance in it's current state. Note that the render call is significantly longer, but if you add up the long render time to the short program time, this time is exactly the same as the one above.
![screen shot 2015-06-30 at 4 17 27 pm 1](https://cloud.githubusercontent.com/assets/3248682/8444313/2785c0ca-1f44-11e5-8c25-8075e6e0d505.png)

**Comment by bluong** [comment]
What is this (program) time?

**Comment by aicioara** [comment]
Native code (chrome binary code running). In this case it should be the actual render of the page.

**Comment by hellochar** [comment]
With the new Typesettable changes and Measurer caching axis drawing is no longer a bottleneck
