### ISSUE TITLE
Key interaction should have a "onKeyHold" endpoint

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2393]
It'd be convenient to be able to know when a key was being held down, for example in issue #2011 holding the ctrl key to change which interaction you're using.

**Comment by jtlan** [comment]
Maybe `onKeyRelease()` to go with `onKeyPress()`? The two API points together would effectively creat the "hold" feature.

**Comment by crmorford** [comment]
Yeah, that'd be good!

**Comment by jtlan** [comment]
As a side note, `onKeyPress()` appears to spam events as long as the key is held down. This might be a separate issue.
