### ISSUE TITLE
Line Segment Plot

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#2394]
![7fa1ff70-6389-47a2-9d55-023acd396d9f](https://cloud.githubusercontent.com/assets/1559622/8286746/2e470160-18c0-11e5-8d22-e3887c80ada9.png)

**Comment by jtlan** [comment]
Seems like a more generalized way of doing this is to have a `Plot` that draws line segments (using `<line>`s), and combining it with other `Plot`s in a `Group`. I can see use-cases for just the segments by themselves too.
