### ISSUE TITLE
Zoom isn't capped on plots, letting them reach unusable states

### ISSUE THREAD

**Issue by andreweduffy** [palantir/plottable#2437]
*Repro*: 
1. Visit the weather example: http://plottablejs.org/examples/weather/
2. Open up the JS console
3. Keep zooming out on the Plot
4. At a certain point, the plot goes blank and the following errors appear on the console:

```
    Error: Invalid value for <g> attribute transform="translate(NaN,0)"
    Error: Invalid value for <line> attribute x1="NaN"
    Error: Invalid value for <line> attribute x2="NaN"
    ...
```

Looks like potentially some kind of FP underflow issue, probably should be some sort of zoom-level capping.

**Comment by andreweduffy** [comment]
Before:
<img width="1440" alt="screen shot 2015-07-03 at 5 52 13 pm" src="https://cloud.githubusercontent.com/assets/332583/8505122/4a89642c-21ac-11e5-9143-eef0dc4cfec5.png">

After:
<img width="1440" alt="screen shot 2015-07-03 at 5 52 27 pm" src="https://cloud.githubusercontent.com/assets/332583/8505123/4a89dcd6-21ac-11e5-9e3f-81a259832071.png">

After the errors occur, the plot is left in an unusable state

**Comment by rcchen** [comment]
@bluong actually added limits to pan/zoom, which can be a way to address this problem. It is available as of [1.2.0](https://github.com/palantir/plottable/releases/tag/v1.2.0). Cross-referenced at https://github.com/palantir/plottable-website/issues/114

**Comment by aicioara** [comment]
On top of that, we should maybe add some default capping, such that issues like the above are no longer  possible

**Comment by aicioara** [comment]
As documented here https://github.com/palantir/plottable/issues/574, this only fails on time scale, which I believe should be fixed as part of this issue. Closing the other one as duplicate

**Comment by jtlan** [comment]
Probably would be fixed by https://github.com/palantir/plottable/issues/2613.
