### ISSUE TITLE
animate_line quicktest broken on firefox

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2440]
Can't find any reason in the console.
I've run it a few times so it doesn't seem like a quicktest flake.
The line just isn't showing up.
None of the other line quicktests seem broken.
![screen shot 2015-07-06 at 3 21 13 pm](https://cloud.githubusercontent.com/assets/7527733/8534594/ad9db08e-23f2-11e5-90e4-178bdc1fd0af.png)

**Comment by aicioara** [comment]
It is because FF date parsing. It was broken in `v1.0.0` as well. It's weird that we missed it.

**Comment by aicioara** [comment]
Using this http://tools.ietf.org/html/rfc2822#page-14
