### ISSUE TITLE
Testing best-practices

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2446]
Just refactor. We postponed this to after `v1.0.0`

**Comment by aicioara** [comment]
`beforeEach()` should only be used for setting up tightly-related tests, inside a more-specific `describe()`. Using it to avoid writing setup code means that it's more difficult to write independent tests.

**Comment by aicioara** [comment]
In the testing code, a common way to test if a path element renders correctly is to strictEqual the path strings.  This is completely fragile as floating point errors can easily occur as well as it does not really test the path other than "did this thing render exactly as i thought it would render?".  Ideally we have a testing framework that can be flexible for floating point errors as well as have a better expression of the test as in "does the path contain this point?" or "does this path not contain this point?"

**Comment by rcchen** [comment]
@aicioara could you please start a wiki page documenting best practice for writing tests within our testing framework?

**Comment by aicioara** [comment]
That's fun. Do we have a set of best practices? I think the best would be to populate the wiki page along with solving this ticket

**Comment by aicioara** [comment]
However, opened https://github.com/palantir/plottable/wiki/Testing-best-practices

**Comment by jtlan** [comment]
"tooling", even though there's no real enforcement by tools.

**Comment by aicioara** [comment]
I believe this can be closed as it has been split into 
#2621
#2622
#2623
#2624
#2625
#2626
#2627
#2628
#2629
#2630
#2631
#2632
#2633
#2634
#2635
#2636
#2637
#2638
#2639
#2640
