### ISSUE TITLE
[Axes.Time + Plots.Bar] Bars are not centered on days, but on midnights

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2447]
http://jsfiddle.net/cgh159Ld/6/

The width of the bars is 1 day. Time is not specified, but it is inferred of being midnight. This means that the center of the bar is on midnight (first moment of the day specified)

For correct behavior, this should be mid day.

**Comment by jtlan** [comment]
I think changing this would produce an inconsistency between the behaviors for `Plots.Bar` and other `Plot`s -- for example, for `Plots.Line`, it's critical that the data point be exactly at the value specified.

**Comment by jtlan** [comment]
Closing this -- `Plots.Bar` should be consistent with the other `Plot`s, and the behavior should make more sense if https://github.com/palantir/plottable/issues/1868 goes in and everything converts to UTC.

**Comment by havran** [comment]
Simple solution for this is add 12 hours to date. Here is JSFiddle http://jsfiddle.net/2mdpt9ha/1/
