### ISSUE TITLE
Auto-generate PRs to DefinitelyTyped when releases made

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#2449]
I've manually filed https://github.com/borisyankov/DefinitelyTyped/pull/4882 for consumers who asked for the typings to be accessible via tsd, but we should look into a way to autonomously do this in the future.

**Comment by leemi** [comment]
Any chance a release will be done anytime soon? The version in @types is a super old 1.4 version of the typings.
Thanks!

**Comment by rcchen** [comment]
It seems that Plottable auto-publishes typings via NPM now so you shouldn't have to install separate typings from `@types` in order to use this library

**Comment by hellochar** [comment]
@rcchen's answer is correct. Let me know if this still pops up
