### ISSUE TITLE
Removing Datasets should be simplified

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2456]
A lot of users hit into this issue because it might not be intuitive.

The code bellow does not work because datasets are removed by reference equality 
```typescript
plot.addDataset(new Plottable.Dataset(data));
plot.removeDataset(new Plottable.Dataset(data));
```
Instead users need to use
```typescript
var dataset = new Plottable.Dataset(data)
plot.addDataset(dataset);
plot.removeDataset(dataset);
```

The solution is to make the remove logic more complex and try to do some deep equality comparison instead of reference equality.

**Comment by rcchen** [comment]
I disagree. Doing deep equality would make users into thinking that this is the right way to do this, it introduces perf issues once datasets become larger, etc. We should educate users properly the first time around.

I think that we should simply add documentation for `.addDataset()` and `.removeDataset()` that emphasizes that it is done by reference equality.

**Comment by aicioara** [comment]
Agree with the above. Waiting for at least 1 more opinion before closing.

**Comment by aicioara** [comment]
How about we throw a warning when the dataset was not found?

**Comment by aicioara** [comment]
@jtlan ?

**Comment by LukeSheard** [comment]
I may not be a collaborator, but having started using this for a couple of weeks I'm with keeping this as reference equality.

**Comment by aicioara** [comment]
2 opinions against is enough for me. Closing this.
