### ISSUE TITLE
Autoranging does not work correctly for Plots.Rectangle and Plots.Segment

### ISSUE THREAD

**Issue by rcchen** [palantir/plottable#2463]

**Comment by jtlan** [comment]
Repros:
`Plots.Segement`: http://jsfiddle.net/tgm3ze9o/
`Plots.Rectangle`: http://jsfiddle.net/Lc17dqkw/

**Comment by jtlan** [comment]
Better repro, showing the problem again:

`Plots.Segment`: http://jsfiddle.net/tgm3ze9o/2/
`Plots.Rectangle`: http://jsfiddle.net/Lc17dqkw/2/

Note that 7 is included in the Y-domain, even though it should be excluded.
