### ISSUE TITLE
Date range tick mark customization

### ISSUE THREAD

**Issue by christinaforney** [palantir/plottable#2476]
Seasonality lines, and being able to specify the ticks that are most relevant to the viewable chart.

**Comment by bluong** [comment]
I've talked with the relevant customers and this seems to be essentially 2 features:

* A translucent rectangle that can show up in the component space to specify relevant date ranges.
  * This can currently be done by using `Plots.Rectangle` with a tiny bit of wizardry.  Maybe we want to abstract this away, but at the very least this can be accomplished with the current architecture.
* Some identifier that can be placed at the axis area that be attached to some tick value to signify that the tick value is important.
  * Note that it should not be difficult to place multiple of these identifiers.  This is so, if a recurring tick value is important, it is not difficult to create an identifier for each tick.

**Comment by bluong** [comment]
Status on the latter is that the pull request is currently in iteration.  I'm currently taking the approach of attaching these identifiers known as annotations to be additional aspects of the axis.  More details can be found at #2620

**Comment by christinaforney** [comment]
The related PR #2620 has merged, so I'm going to go ahead and close this.

**Comment by christinaforney** [comment]
Merged in 1.10, so updating milestone to be accurate.
