### ISSUE TITLE
Mouse cursor position is not correct for pie chart selection.

### ISSUE THREAD

**Issue by sarapeletz** [palantir/plottable#2491]
The mouse cursor position does not correspond to the slice of the pie chart that is selected on click. The mouse cursor position is several pixels off and on click, selects either a different slice nearby or no slices at all.

Reproduce:
1. Create a pie chart with 5 slices - where one slice has a value of 500 and the other slices have values around 5.
2. Try to select one of the small slices.

See Slate ticket 2428

**Comment by crmorford** [comment]
Made a plottable repro! http://jsfiddle.net/pghLh8da/
Thanks for catching this @sarapeletz

**Comment by jtlan** [comment]
Strangely it doesn't seem to happen for wider slices: http://jsfiddle.net/pghLh8da/1/
