### ISSUE TITLE
Chart selection on time series at the millisecond level

### ISSUE THREAD

**Issue by sarapeletz** [palantir/plottable#2498]
When making a chart with a time series axis and selection enabled, the drag selection box will jump to the nearest integer value. At the moment, this seems to be the expected behavior. Is there a way that we can change this to feel less like a bug?

See Slate ticket 2438

**Comment by jtlan** [comment]
This doesn't actually occur within Plottable: http://jsfiddle.net/go5zkf4a/1/ (non-repro)

Here's probably what's happening. The Slate implementation probably inverts the bounds of the drag-box to get `Date` objects. However, `Date` objects can only take on [integer values of milliseconds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date):
```Javascript
var fractional = new Date(0.5);
var whole = new Date(0);
fractional.valueOf() === whole.valueOf(); // true
```
http://jsfiddle.net/a7sm0dwh/

**Comment by jtlan** [comment]
Closing as invalid.
