### ISSUE TITLE
Use string-literal signatures

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2509]
I see this here https://github.com/palantir/plottable/blob/develop/typings/d3/d3.d.ts#L2182 (link might outdate at some point, but pasted bellow). Looks pretty neat in the cases where we use stringy enums. Let's see if our build tools (or our code style) can make those as well

``` typescript
interpolate(): string | ((points: Array<[number, number]>) => string);
interpolate(interpolate: "linear"): Line<T>;
interpolate(interpolate: "linear-closed"): Line<T>;
interpolate(interpolate: "step"): Line<T>;
interpolate(interpolate: "step-before"): Line<T>;
interpolate(interpolate: "step-after"): Line<T>;
interpolate(interpolate: "basis"): Line<T>;
interpolate(interpolate: "basis-open"): Line<T>;
interpolate(interpolate: "basis-closed"): Line<T>;
interpolate(interpolate: "bundle"): Line<T>;
interpolate(interpolate: "cardinal"): Line<T>;
interpolate(interpolate: "cardinal-open"): Line<T>;
interpolate(interpolate: "cardinal-closed"): Line<T>;
interpolate(interpolate: "monotone"): Line<T>;
interpolate(interpolate: string): Line<T>;
interpolate(interpolate: (points: Array<[number, number]>) => string): Line<T>;
```

**Comment by bluong** [comment]
We need to see if this constitutes an API break.  While this should break no workflows (places where we use this idea will usually error with foreign strings), maybe users expect differently.

**Comment by aicioara** [comment]
I believe this
```
interpolate(interpolate: string): Line<T>;
```
Will still allow random strings to be inserted. In my understanding the above just documents the method better. Might be worth to play with it for a bit.

**Comment by jtlan** [comment]
This sounds great, particularly for things like `xAlign()`.

**Comment by aicioara** [comment]
@jtlan you were looking into this. Do we want it?

To perform:
- Just dump the above as overloaded version of the method

Issues:
- Does not provide type safety anyway (just like any overloaded method)
- Takes a while to implement (I guess)

Advantages: 
- Makes it cleaner for the consumers (who either use tooling / ts / read the d.ts) what does the method accept.

**Comment by jtlan** [comment]
This seems like the "most Typescript" way to cover the Javascript convention of having "stringy" APIs.
