### ISSUE TITLE
iPad: Pan and Zoom interactions within one chart affect other charts

### ISSUE THREAD

**Issue by sarapeletz** [palantir/plottable#2510]
Panning/zooming within a single chart causes other charts within the document to pan/zoom. This happens on an iPad when multiple charts with Pan and Zoom enabled are within a single document. 

Version: plottable v1.4.0

**Comment by bluong** [comment]
Wondering, does this happen in both scenarios?

1) One finger dragging.

2) Two finger pinching.

**Comment by sarapeletz** [comment]
This only happens with 2) Two finger pinching. 

Filed as Slate ticket 2456

**Comment by bluong** [comment]
Thanks for the info!

**Comment by jtlan** [comment]
Repro: http://jsfiddle.net/w82shn5r/

**Comment by bluong** [comment]
As a bugfix note, I believe this is not necessarily a bug in dealing with iPad, but likely there is a bug in the `_handlePinch` function in the relevant code.
