### ISSUE TITLE
Add pan limitations functionality

### ISSUE THREAD

**Issue by christinaforney** [palantir/plottable#2522]
Similarly to how we have zoom limitations, we also would like to have pan limitations.

**Comment by RobAtticus** [comment]
Is there an update on when this is projected to land?

**Comment by christinaforney** [comment]
Hi @RobAtticus - hoping to complete this in the next few weeks. Right now it's scheduled as an "if time", so once the currently prioritized work gets done, we'll be able to start work on this feature.

**Comment by hellochar** [comment]
Fixed by #3111 !
