### ISSUE TITLE
Audit all formatters

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2527]
We are unsure what happens when we pass wrong values to `Plottable.Formatters`. 
- Decimal values 2.3
- Values bigger than 20
- 0
- Negative values.

Make sure we have consistency

**Comment by bluong** [comment]
Specifically for the `precision` parameter for most of the formatters

**Comment by aicioara** [comment]
Thank you. That's correct.

Also, apparently the `Formatters.general` seems to behave weirdly. Needs investigation

**Comment by aicioara** [comment]
Formatters are (checked as I go through them)

- [ ] currency
- [ ] fixed
- [ ] general
- [ ] percentage
- [ ] siSuffix
- [ ] shortScale

**Comment by aicioara** [comment]
So `general` and `siSuffix` are broken and will be addressed as part of the PR
