### ISSUE TITLE
Gridlines don't expand to fill available space

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2532]
Repro: http://jsfiddle.net/f2yqb8ek/

**Actual**: `Scales` backing `Gridlines` don't have their `range()` set correctly, so the lines are bunched up on one side.
**Expected**: `Scales` have their `range()` set appropriately.

**Comment by dwadelson** [comment]
isn't this because the range isn't set until data are entered?

**Comment by bluong** [comment]
This is the driving reason behind https://github.com/palantir/plottable-website/issues/133 . I'll get to this so that the website can have the upgrade.

**Comment by rcchen** [comment]
Actually @bluong the reason Gridlines never showed up on there was because there are a couple distinct categories of Components, and I wasn't sure what to throw "Gridlines" into, as it fit more into an "Overlay" category than anything.

**Comment by bluong** [comment]
@rcchen While this is true, Gridlines currently cannot be rendered by themselves unless the scales are set up beforehand.  This probably should be fixed.
