### ISSUE TITLE
Incorrect typing on plottable website example

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#2533]
Minor issue: On the website's [hockey chart example](http://plottablejs.org/examples/hockey/) the angles for the axis labels are specified as strings, but it actually expects a number.
Love the examples btw. I think it would be awesome if they were on the front page :)

**Comment by bluong** [comment]
Hello @danmane !

I'll take a quick glance at the code on the website to make sure everything is typed correctly, and I'll file and issue / ask how we would move the examples to the front page.

**Comment by jtlan** [comment]
Fixed.
