### ISSUE TITLE
Glitch when panning and zooming clustered bars

### ISSUE THREAD

**Issue by jasperSpeicher** [palantir/plottable#2545]
<a href="http://www.youtube.com/watch?feature=player_embedded&v=JS0WA17XLnc
" target="_blank"><img src="http://img.youtube.com/vi/JS0WA17XLnc/0.jpg" alt="Pan-Zoom Glitch" width="240" height="180" border="10" /></a>

**Comment by jasperSpeicher** [comment]
Closer look:
<a href="http://www.youtube.com/watch?feature=player_embedded&v=BHrxKwfyvpU
" target="_blank"><img src="http://img.youtube.com/vi/BHrxKwfyvpU/0.jpg" alt="Pan-Zoom Glitch" width="240" height="180" border="10" /></a>

**Comment by aicioara** [comment]
Taking this

**Comment by aicioara** [comment]
AFAIK this is what used to be the expected behavior. The lines are trying to squeeze in the given space if they have this option. 

However, this bug was signaled so many times, I believe it is not a good default

**Comment by jasperSpeicher** [comment]
Seems weird that it would change the scale of the bars even when just panning, and also strange that it is only happening as January 1 passes the origin...

**Comment by aicioara** [comment]
Repro here as well 
http://jsfiddle.net/m6amh0vv/1/
Feel free to PanZoom

**Comment by aicioara** [comment]
@jasperSpeicher this has been fixed and is now merged into develop. Will most likely be part of release 1.7.0 at the end of this Friday. Please let us know if you still experience problems. Thank you for submitting the issue and enjoy using Plottable.

**Comment by jasperSpeicher** [comment]
@aicioara Thank you! Very excited. Great lib.
