### ISSUE TITLE
Bad data for Pie Plots results in off-by-one labels

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2556]
http://jsfiddle.net/k5yaLhyp/
one of the values is "f". instead of throwing it out, we apply that label to the wrong pie piece, and the rest of the labels are off by one.

**Comment by crmorford** [comment]
![screen shot 2015-08-04 at 1 13 40 pm](https://cloud.githubusercontent.com/assets/7527733/9071527/a5643bbc-3aaa-11e5-9084-147f3dc7434b.png)
![screen shot 2015-08-04 at 1 13 35 pm](https://cloud.githubusercontent.com/assets/7527733/9071531/a69e7ad8-3aaa-11e5-9a9f-6db232523dbb.png)

**Comment by christinaforney** [comment]
This might also occur on bar charts

**Comment by ztsai** [comment]
verified that it doesn't happen on bar charts
