### ISSUE TITLE
Add .entitiesAt() to Plots.Scatter

### ISSUE THREAD

**Issue by christinaforney** [palantir/plottable#2569]
Broken out from https://github.com/palantir/plottable/issues/1959

**Comment by jtlan** [comment]
One question is if the points are considered "square" or "round" for detection:

#### "square"
The hit area is considered a square with edge of length `size()`, but that means the corners count as part of the circle:
![circleoutside](https://cloud.githubusercontent.com/assets/1440449/9262236/32cac0ba-41c8-11e5-9ecb-d2aedae55be5.png)

#### "round"
The hit area is considered a circle with radius `size()/2`, but that means the corners won't count as part of the square:
![squareoutside](https://cloud.githubusercontent.com/assets/1440449/9262263/6b47c294-41c8-11e5-935d-798a85bd4efd.png)

Things get weirder when shapes like crosses/triangles are considered. Doing a direct hit-test against the path is really difficult.

**Comment by crmorford** [comment]
Obviously a direct hittest would be nice, but I think it's better to give more room for user error (escpecially since scatter plot points are so tiny). I'm in favor of "square", so that every shape will be completely contained in the hitbox.
