### ISSUE TITLE
PanZoom - allow limiting zoom on any side

### ISSUE THREAD

**Issue by RobAtticus** [palantir/plottable#2573]
For example, if I have a graph that goes from [0, 100] and I'm zoomed in on [90, 100], it would be nice to limit the zoom so that it doesn't sound values past 100 but still zooms out on the other side. That is, zoom from [90, 100] -> [80, 100] -> ... -> [0, 100].

**Comment by christinaforney** [comment]
Hi @RobAtticus, I think what you're referring to is pan limitations (https://github.com/palantir/plottable/issues/2522), we already have zoom limitations https://github.com/palantir/plottable/issues/1639. 

You can see an example of zoom limits here: http://jsfiddle.net/bluong63/bzbbaxcy/

Do you feel like the pan limitation would cover this case? If so, I'd like to close this as a duplicate.

**Comment by RobAtticus** [comment]
Perhaps I am thinking of pan limitations. I do already do the techniques you show there, but that only works if I am centered on the graph. I suppose this actually is pan limitations and I did not see that issue.

**Comment by christinaforney** [comment]
@crmorford - can you verify that pan limitations have this sort of functionality, and if so, close this out? Otherwise let's discuss. I'd love to see a fiddle with this working.

**Comment by crmorford** [comment]
@christinaforney @RobAtticus 
We actually don't have pan limits yet. I think they're on brandon's plate for this week though :) So I can verify this when I QE it.

**Comment by themadcreator** [comment]
Fixed by #3111
