### ISSUE TITLE
onAnchor fired before the chart is fully rendered

### ISSUE THREAD

**Issue by okal** [palantir/plottable#2577]
*Back story*

Because there's no clear API method to show labels on all bars in a bar chart, and restyle them to appear above the rect without resorting to modifying protected methods (`Bar.prototype._drawLabel`, for example), we tried creating the text elements manually using d3 within an onAnchor callback. We need access to the `x` and `y` attributes of the individual `<rect>`s generated, to determine where to place the labels, but they're not available by the time the callback is fired.

*Suggestions/Proposals*

1. Would it be possible to only fire `onAnchor` once the SVG is fully populated?
2. Alternatively, would it be possible to add an `onRender` that only fires after complete rendering?

**Comment by jtlan** [comment]
Hello @okal,

`onAnchor()` is meant to fire when `anchor()` is called. #1755 tracks the request for an API point to be called after rendering is complete.

By symmetry, `onRender()` would fire when `render()` is called, which isn't that helpful (`render()` only enqueues the `Component` for rendering). Maybe something like `onRenderComplete()`?

**Comment by okal** [comment]
Yeah, sounds like just the thing. At what point would that be called? Could work on it if you're willing to do a (very little, I promise 😄) bit of hand-holding.

**Comment by aicioara** [comment]
+1 for the feature. 

I was also recently thinking that we may want to switch to a more callback-oriented model in our internals to support random initialization for our plots (be able to specify the settings of a plot in any order) without the current headache. [but this is outside the scope of this discussion] 

One small thing from the top of my head: 
- If the plot was already rendered to the SVG, the callback should be called immediately to be consistent with onAnchor behavior 
- We may want to expose some end-points to query for `wasRendered` or `wasAnchored` (unsure if we want this as it would be part of the public API)

Hand-holding wise, you may want to start by looking into how on/offAnchor is implemented and probably implement this feature in the `component.ts` and add adequate tests in `componentTests.ts`. I guess that's a good way to start, but I'm happy to help further when stuck.

**Comment by bluong** [comment]
@aicioara In regards to the `wasRendered` / `wasAnchored`, there actually are instance variables `_isAnchored` / `_isSetup` currently existing that we can leverage if you want to move forward with this idea

**Comment by aicioara** [comment]
Yeah, I know, I brought it up just for a matter of "do we want this or not" and does it make sense to add extra API points. We could instead have something hacky like

```typescript
let isAnchored = false;
component.onAnchor(function() {
  isAnchored = true;
});
```

**Comment by bluong** [comment]
I would personally say that you should experiment with that model and see the results.  If the results are more clean, then sure we can move forward with it.

**Comment by okal** [comment]
I'll see how much time I can get allocated on this. Hopefully can put in some work on it today.

**Comment by jtlan** [comment]
Going to close this, since `onAnchor()` is behaving properly, and the on-render callback is covered by #1755.

**Comment by okal** [comment]
Sounds good.
