### ISSUE TITLE
Flakyness on IE for dragBoxLayer.movable(true)

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2599]
http://jsfiddle.net/5tw5efp9/7/
This example is far harder to use on IE than on any other browser. 
It's hard to explain why without playing with it yourself, but it feels like the end of the click isn't caught, and sometimes edges will continue to be moved around with the mouse pointer, even though you're done clicking. 
This could also be due to the cranky touchpad on our windows box, but I couldn't find a mouse and I didn't want to block on that to file this.

**Comment by jtlan** [comment]
I think this is due to the performance of `entitiesIn()`; removing the data from the `Plot` seems to solve the problem:
http://jsfiddle.net/9tz45m13/

**Comment by crmorford** [comment]
yep, perf bug. sorry i didn't close sooner.
