### ISSUE TITLE
Better tooling for visualizing diffs

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2609]
Github allows visualizing the diff between hashes, but the interface is kind of clunky. This makes it somewhat difficult for a reviewer to see what's changed since the last time they looked at the PR, rather than the full diff or individual commits. Maybe there's some sort of tool we can use for this?

**Comment by aicioara** [comment]
Finally implemented by GitHub. https://github.com/blog/2123-more-code-review-tools#pick-up-where-you-left-off 
Can be closed.
