### ISSUE TITLE
Pie should blow up on negative values

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2611]
Plottable currently throws a warning when the user gives negative values for a pie plot. We should blow up the plot instead, since the result is misleading:
http://jsfiddle.net/k5yaLhyp/6/
![screen shot 2015-08-13 at 2 41 30 pm](https://cloud.githubusercontent.com/assets/7527733/9262380/6c28667c-41c9-11e5-9d66-f33ab6c77ae7.png)

**Comment by jtlan** [comment]
Would it make more sense just to remove the slice from consideration?
