### ISSUE TITLE
Timewheel support

### ISSUE THREAD

**Issue by christinaforney** [palantir/plottable#2612]
Take a look at this old PR that never merged: https://github.com/palantir/plottable/pull/1347. Don't necessarily need to do this the same way - so consider the optimal implementation. An RFC would be a good idea.

**Comment by ztsai** [comment]
- [ ] basic rendering
- [ ] add stroke
- [ ] `labelsEnable`
- [ ] `entitiesAt`

**Comment by jtlan** [comment]
Closing because this wound up being split.
