### ISSUE TITLE
PanZoom Interactions should automatically configure with limits

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#2613]
When a Pan Zoom interaction is created, it should automatically set pan/zoom limits so that it will not allow the user to entirely lose the data on the screen. Here is what I propose:

The PanZoom interaction attaches listeners to its scales, and listens for domain changes. When there is a domain change that was not caused by the PanZoom interaction (can determine this by setting a `isModifyingScale` flag on the PZI and then ignoring changes when that flag is set), it caches the domain on the scale and modifies its limits so it will not zoom out to more than 1.5x the domain span, and will not pan outside the range `[domainMin - domainSpan*.25, domainMax + domainSpan*.25]`

Do you think this approach is technically feasible?

**Comment by yocontra** [comment]
@danmane Did you ever manage to get this working or figure out a workaround?

**Comment by hellochar** [comment]
You can now do this by calling `PanZoom.setMinMaxDomainValuesTo()` after attaching the PanZoom interaction.
