### ISSUE TITLE
Update chai and its definitions

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2614]
Currently our bower.json lists 1.9.0; the current version is **3.2.0**.

Also, signature for `assert.throws` is wrong in the definitions file. From experimenting, to include a message requires the following signature:
```Typescript
assert.throws(function, errorConstructor, message_error_throws, message);
```

But the .d.ts file doesn't seem to list the signature, nor do the docs?

**Comment by aicioara** [comment]
It's not in the docs. That's weird.

**Comment by aicioara** [comment]
Will not be fixed. Opened this https://github.com/palantir/plottable/issues/2661
