### ISSUE TITLE
[Testing Audit] Scales

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2640]

**Comment by aicioara** [comment]
Note for self, this means
- [ ] `categoryScale.ts`
- [ ] `colorScale.ts`
- [ ] `interpolatedColorScale.ts`
- [ ] `linearScale.ts`
- [ ] `modifiedLogScale.ts`
- [ ] `quantitativeScale.ts`
- [ ] `scale.ts`
- [ ] `timeScale.ts`
- [ ] `tickGenerators.ts`

**Comment by aicioara** [comment]
Blocking on scale and quantitative scale until children are merged.

**Comment by jtlan** [comment]
`Scale` and `QuantitativeScale` done in #2974; closing this out.
