### ISSUE TITLE
Cursor Styles only show on top dragbox layer

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2647]
I'm not sure if there's actually a case for this monstrosity...
but if you layer multiple dragbox layers, the little cursor indicators for grabbing only show up on the 'top' layer. 
http://jsfiddle.net/fa3mjzew/5/
1. make a drag box
2. hover over green section and see the grabby hand cursor
3. hover anywhere else -- no grabby hand

**Comment by jtlan** [comment]
Related: http://jsfiddle.net/ssL0Lbs0/

On *Safari*, the pointer events destined for the `Legend` appear to wind up in the `Component` behind it. Hovering over the background shows tooltips, when it shouldn't...
<img width="414" alt="screen shot 2015-08-25 at 7 41 23 pm" src="https://cloud.githubusercontent.com/assets/1440449/9484451/4a297150-4b61-11e5-9e44-49213b05be2a.png">

**Comment by jtlan** [comment]
Another repro using `DragLineLayer`: http://jsfiddle.net/teed664k/

**Comment by jtlan** [comment]
An even more straightforward repro, demonstrating that any `Component` in front of a `DragLineLayer` will cause the problem: http://jsfiddle.net/7Lxzacoz/

**Actual**: No cursor is shown on the `DragLineLayer`.
**Expected**: Cursor is shown on the `DragLineLayer`.
