### ISSUE TITLE
Event callbacks for PanZoomInteraction

### ISSUE THREAD

**Issue by istarnx** [palantir/plottable#2651]
We have some stuff we'd like to disable upon pan/zoom. Can you guys add callbacks to signal panZoom start/end?

**Comment by christinaforney** [comment]
Are waiting on clarification of need before continuing to work on this.

**Comment by christinaforney** [comment]
e

**Comment by jtlan** [comment]
@christinaforney What was the eventual clarification?

**Comment by MadsMadsDk** [comment]
Any news on this? I have a situation where I want to do things after panning has ended. Currently I'm listening for timescale-updates, but it creates a great deal of overhead.
