### ISSUE TITLE
Add support for localization to date references

### ISSUE THREAD

**Issue by christinaforney** [palantir/plottable#2652]
Any references to time/date should have an option to set localization. For example, on a chart with a date axis, I should be able to set the localization language to French, or any other language I choose.

**Comment by christinaforney** [comment]
for CONTOUR-577

**Comment by tedvanderveen** [comment]
+1 Same here for Dutch localization

**Comment by christinaforney** [comment]
D3 supports Locales, looks like it should be a relatively minor change to Plottable to leverage the D3 locales (change Formatters.time to return a locale-specific formatter).

**Comment by christinaforney** [comment]
This feature should support all available languages from D3 locales, not just the two specified here :)

**Comment by christinaforney** [comment]
@bluong can you link to the moment wrapper project here when you have a chance?

**Comment by bluong** [comment]
Progress is being made here https://github.com/bluong/plottable-moment

Once the project is complete, however, it will move under the Palantir umbrella.

**Comment by christinaforney** [comment]
https://github.com/palantir/plottable-moment Released!
