### ISSUE TITLE
onClick() triggers for drags

### ISSUE THREAD

**Issue by istarnx** [palantir/plottable#2692]
Flagging this, but I'm not sure how this *should* behave. If I mouse down, move, and mouse up, I get an onClick() triggered at the mouse up position.

In my particular case, this made using DragBoxLayer and Interactions.Click together difficult.

**Comment by jtlan** [comment]
That's currently the intended behavior for `Interactions.Click`, given the behavior clicks usually have in other contexts. For example, if you click down on an HTML `<button>`, move your cursor around, then release it anywhere inside the button, the click is triggered.

Maybe we should only trigger clicks if the start and end positions are exactly equal? @crmorford , any thoughts on this?

**Comment by adidahiya** [comment]
I think the current behavior is correct since it is consistent with HTML element interactions as @jtlan described. Happy to reopen if there is further discussion.

**Comment by waltonseymour** [comment]
Is there a way to prevent propagation of events to onClick from drag events? Or maybe detect the change in position between mouseDown and mouseUp?

I'm not seeing a clear way to distinguish the two, given onClick only binds to mouseUp.
