### ISSUE TITLE
Horizontal Bar Plots + dataset.data() bad behavior

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2704]
http://jsfiddle.net/ubwgm9cn/
repro:
1. open jsfiddle, note yScale domain
2. click on plot
3. yScale domain is now smaller

expected: yScale domain doesn't change when the callback is called
actual: yScale domain becomes smaller

also happens on stackedBar, clusteredBar

**Comment by aicioara** [comment]
Updated the fiddle.

http://jsfiddle.net/o3rzuqur/
