### ISSUE TITLE
using plottable in AngularJS

### ISSUE THREAD

**Issue by Sutikshan** [palantir/plottable#2716]
Hello everyone,
Has anyone used plottable in AngularJS as directive?
Is there and wrapper available for this.

~thanks.

**Comment by crmorford** [comment]
Hello @Sutikshan!

Thanks for your interest in Plottable! Unfortunately, we don't support any implementations of Plottable Directives at the moment.

Our current focuses in Plottable are improving perf and introducing new features, but we'll keep your interest in this in mind! If anything changes in the future, we'll be sure to make an announcement.

**Comment by Sutikshan** [comment]
Thanks for the words.
Actually it is very-very easy to do. I quickly wrote Angular directive wrapper around Open-mHealth usage of plottableJS. 
As it is not an issue at all, I am closing it.
