### ISSUE TITLE
Testing code which uses Plottable

### ISSUE THREAD

**Issue by ricklupton** [palantir/plottable#2731]
I'm finding it difficult to unit test code which makes use of Plottable to draw graphs: nothing shows up inside the svg during testing, although it works properly in normal use.

I've tried adding
```
Plottable.RenderController.renderPolicy("immediate");
```
based on your own testing code; is there anything else that needs to be done to render immediately within unit tests?

(I'm using karma / jasmine / Chrome)

**Comment by jtlan** [comment]
Hi @ricklupton,

That's probably the best thing to do. Plottable's `RenderController` defaults to using [`requestAnimationFrame()`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame), meaning that `Component`s may not necessarily rerender immediately after `render()` is called (`render()` only queues the `Component` for render). 

Another option is to call `RenderController.flush()`, which will cause all `Component`s currently queued to immediately render.

Let us know if this works for you.

**Comment by crmorford** [comment]
Hey @ricklupton, same as the other issue, I'm gonna close this out since it seems like there were no followup questions. I can reopen if necessary.

**Comment by ricklupton** [comment]
Yes that's fine, thanks for your help.
