### ISSUE TITLE
clipPath loses reference if URL changes

### ISSUE THREAD

**Issue by christinaforney** [palantir/plottable#2733]
Contour found an issue with zooming and time series plots. See CONTOUR-654 for more details.

**Comment by jtlan** [comment]
Dug into this a bit -- I think it's because the [`clipPath`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath) reference is written out as "`URL_PREFIX#clipPathID`", meaning if the same `Component` is reused but the URL changes, the reference to the `clipPath` is lost.

**Comment by jtlan** [comment]
A repro: http://jsfiddle.net/mpqwxg4n/7/

For some reason it currently only works on Firefox, even though it worked on Chrome for me earlier today...
