### ISSUE TITLE
Formatters.RelativeDate - Warns deprecation, API doesnt say so

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#2750]
When you instantiate a Formatters.RelativeDate, it prints a warning to console saying that it's deprecated. However, the API docs don't say this, so someone reading http://plottablejs.org/docs/modules/plottable.formatters.html may think it's fine to depend on.

As an aside, a relative date formatter seems useful to have, does it really make sense to deprecate it due to a bug? As opposed to just fixing the bug? My impression is you deprecate things because they are the wrong api, not because they have a bad implementation. Or is the API for RelativeDate formatter fundamentally unworkable because they don't get the TZ info from js date objects? I never really grokked time zones.

**Comment by aicioara** [comment]
For the first part, the fix is above.

**Comment by aicioara** [comment]
For the second part, we just had a discussion with @bluong and @jtlan .

The core problem is the daylight save times for various timezones, which we do not know. As a scenario, assume today 4PM + 1 day and assume tonight the time shifts from 1 am to 2 am. We expect adding 1 day to not change the time, but

```typescript
x = new Date(2015, 02, 07)
// Sat Mar 07 2015 00:00:00 GMT-0800 (PST)

new Date(x.valueOf() + 1000 * 60 * 60 * 24 * 1)
// Sun Mar 08 2015 00:00:00 GMT-0800 (PST)

new Date(x.valueOf() + 1000 * 60 * 60 * 24 * 2)
// Mon Mar 09 2015 01:00:00 GMT-0700 (PDT)
``` 

This means that the API point is not useable. What we need to do instead is to have a base value, an increment AND an unit of measure (day, minute, second). That way we can do tricks like

```typescript
x = new Date(2015, 02, 07)
// Sat Mar 07 2015 00:00:00 GMT-0800 (PST)

new Date(x.getFullYear(), x.getMonth(), x.getDate() + 1, x.getHours(), x.getSeconds(), x.getMilliseconds())
// Sun Mar 08 2015 00:00:00 GMT-0800 (PST)

new Date(x.getFullYear(), x.getMonth(), x.getDate() + 2, x.getHours(), x.getSeconds(), x.getMilliseconds())
// Mon Mar 09 2015 00:00:00 GMT-0700 (PDT)
```

**Comment by aicioara** [comment]
Opened https://github.com/palantir/plottable/issues/2754 

We are always happy to accept pull requests.
