### ISSUE TITLE
Is it possible to put label on yAxis on top of the axis

### ISSUE THREAD

**Issue by mato75** [palantir/plottable#2770]
![screen shot 2015-09-15 at 17 10 57](https://cloud.githubusercontent.com/assets/616192/9880671/db63a746-5bcc-11e5-957c-f3c13d6c6ca2.png)

The yAxis label, I would like to have it on top/centered of the axis. Used xAlignment('center') but it doesn't do the trick.

**Comment by bluong** [comment]
Hello @mato75 ,

When you say you want to have the yAxis label on top/centered of the axis, do you mean that you want the label on a different row than the axis?

If so, what we need to do here is to affect the table that is being rendered so we can make that the case.  In taking only the yAxis and the yAxisLabel, do you want the relationship to look like this? http://jsfiddle.net/zsfkg32b/5/

Note that in the JSFiddle, the main difference is that there is the label is placed in a separate array from the axis, which allows it to act in its own row about the axis.

With this in mind, I tried replicating your example using random data, and I got this: http://jsfiddle.net/zsfkg32b/7/

Are the above examples replicating what you are trying to do?  If you run into any trouble, feel free to reach out! :smiley:

**Comment by mato75** [comment]
![screen shot 2015-09-15 at 18 22 37](https://cloud.githubusercontent.com/assets/616192/9882795/c786c622-5bd6-11e5-9ebd-7583a37f2243.png)

This is what I would like to have. I would also like to hide y line and only show numbers and when line is hidden.

And one more question, how do I add grid inside the chart (only horizontal grid), I tried using gridlines with line in Group, but the chart is totally of, grid is way to big.

**Comment by bluong** [comment]
The above JSFiddles I believe should help you move the label above the yAxis.  Can you confirm this?
Hiding the y axis line should be capable through css.  What we need to do here is add a class to the yAxis to differentiate it from other axes and then affect the tick marks through css, as can be seen here: https://jsfiddle.net/bluong63/zsfkg32b/11/

Note the CSS box on the top-right side of the page.

**Comment by mato75** [comment]
Thx will check out. This is what I would like to generate with plottable. Is it possible, that you give one more example with grid + chart.

![screen shot 2015-09-16 at 10 38 51](https://cloud.githubusercontent.com/assets/616192/9900168/38afcafa-5c5f-11e5-8c9f-a159459ffe42.png)

**Comment by mato75** [comment]
How do you set that x Axes starts at 0px, because when used .Linear there is padding on the left and right side.

**Comment by mato75** [comment]
Is there a chart room anywhere, where people talk about using plottable?

**Comment by mato75** [comment]
Grid + Chart = http://jsfiddle.net/mato75/1734wvs5/27/

Now the only thing that I would like to do is set xAxis to 0.

**Comment by crmorford** [comment]
Talked to @mato75 on gitter, we're getting closer using these charts 
http://jsfiddle.net/1734wvs5/28/ (Y label not centered above axis)
http://jsfiddle.net/1734wvs5/29/ (xAxis.width() != plot.width())

**Comment by mato75** [comment]
http://jsfiddle.net/mato75/1734wvs5/32/
