### ISSUE TITLE
Plot.ScatterPlot.EntityNearest() throws error when no data is visible

### ISSUE THREAD

**Issue by ztsai** [palantir/plottable#2782]
it throws error if there's no data in Dataset or no points are in domain
http://jsfiddle.net/ztsai/ukpfwckb/
http://jsfiddle.net/ztsai/ukpfwckb/1/

**Comment by jtlan** [comment]
What should we return in this case? `null`?

**Comment by ztsai** [comment]
empty array?

**Comment by ztsai** [comment]
yeah, I think that's what the other plots return

**Comment by jtlan** [comment]
Looks like the same issue as #2925, in which case @crmorford fixed it in #2945.
