### ISSUE TITLE
Plots.Bar doesn't autodomain a linear "base" scale if there's only one data point

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2788]
If the "base" scale for a `Plots.Bar` (x on vertical, y on horizontal) is `Linear` or `Time`, and there's only one data point, the `Scale` won't autodomain:

**Repro**: http://jsfiddle.net/acfamvqn/

**Actual**: The `Scale`'s domain remains at the default of `[0, 1]`.
**Expected**: The `Scale` autodomains to center on the data point.

**Comment by jtlan** [comment]
Moving `addDataset()` post-render causes the autodomaining to happen as expected.

**Comment by bluong** [comment]
Repro is no longer valid.  Possibly fixed here #2857
