### ISSUE TITLE
[Plots.Bar] _pixelPoint() returns wrong value

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2793]
The `_pixelPoint()` of `Plots.Bar` returns the wrong value:

<img width="414" alt="screen shot 2015-09-21 at 3 59 52 pm" src="https://cloud.githubusercontent.com/assets/1440449/10007407/d117363e-6079-11e5-84be-7c22f039a131.png">
(green shows expected positions, red shows actual ones)

**Repro**: http://jsfiddle.net/8gxszz87/
**Actual**: points for negative values appear at the top of the bar, rather than the end.
**Expected**: return value for `_pixelPoint()` should match `entities().position`

It looks like `entities()` accounts for the wrong position somehow.

**Comment by jtlan** [comment]
Also broken on horizontal: http://jsfiddle.net/8gxszz87/1/

**Comment by yunhaolucky** [comment]
This might not be a bug. Because according to the logic in the code, `_pixelPoint()` should return the top point of each bar and `entities().position` should return the data point of each bar.
