### ISSUE TITLE
[Plots.Bar] entities() returns wrong positions when domain is reversed

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2794]
<img width="316" alt="screen shot 2015-09-21 at 4 23 30 pm" src="https://cloud.githubusercontent.com/assets/1440449/10007807/5435fa16-607d-11e5-9736-ad9afb409962.png">

**Repro**: http://jsfiddle.net/ogL16g2f/
**Actual**: `entity.position` is at the top of some bars, and at the base of others
**Expected**: `entity.position` is at the top of each bar

**Comment by jtlan** [comment]
Even goofier things happen if more data points are used, and some lie outside the visible domain:
<img width="311" alt="screen shot 2015-09-21 at 4 26 30 pm" src="https://cloud.githubusercontent.com/assets/1440449/10007831/89c5599c-607d-11e5-867a-c71d98ee6ef1.png">
http://jsfiddle.net/ogL16g2f/2/

**Comment by jtlan** [comment]
Probably related to https://github.com/palantir/plottable/issues/2793

**Comment by crmorford** [comment]
GROSS

**Comment by crmorford** [comment]
@yunhaolucky  fixed this :)
