### ISSUE TITLE
Scattered line

### ISSUE THREAD

**Issue by mato75** [palantir/plottable#2799]
Is it possible to generate scattered line.

![screen shot 2015-09-23 at 17 16 55](https://cloud.githubusercontent.com/assets/616192/10049272/1e7f0d68-6217-11e5-9f0d-42612c0515c9.png)

**Comment by crmorford** [comment]
This can be done by applying the following line of javascript to a `Plots.Line`:
```
.attr("stroke-dasharray", "3 3");
```

**Comment by mato75** [comment]
thx
