### ISSUE TITLE
Setting scatter size with Scale

### ISSUE THREAD

**Issue by mato75** [palantir/plottable#2804]
Hm, scatter sizes are all the same when used with sizeScale.

Please check this example.
http://jsfiddle.net/mato75/1734wvs5/43/

There is a code snippet in this issue that says 

            .size(function (d) { return d}, sizeScale);

 #2521

**Comment by jtlan** [comment]
@mato75, I think the issue in [that fiddle](http://jsfiddle.net/mato75/1734wvs5/43/) is this line:
```Javascript
var sizeScale = new Plottable.Scales.Linear().range([0, 60]);
```
Since the minimum value of the range is `0`, some data values will have a size that maps to `0` or something similarly small, and will effectively be invisible. Try something like `range([30, 60])`.

**Comment by crmorford** [comment]
Hey @mato75 , I'm gonna close this out because I expect @jtlan's comment to solve your problem. Let me know if you had more issues.
