### ISSUE TITLE
Update development guide on the README.md

### ISSUE THREAD

**Issue by aicioara** [palantir/plottable#2826]
## Before

- Clone the repo
- Install global dependencies `sudo npm install grunt grunt-cli typescript -g`
- Install local dependencies `npm install`
- Run `grunt` and it will spin up a server (pointed at localhost:9999) and begin compiling the typescript code

## Suggestion

- Clone the repo
- Install global dependencies `npm install grunt grunt-cli -g`
- Install local dependencies `npm install`
- Ensure correct version of node is used `npm install n && n 0.12.7`
- Run `grunt` and it will spin up a server (pointed at localhost:9999) and begin compiling the typescript code
- If you get an `EACCESS` error at any point, either [fix npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) or run the commands with `sudo`. Make sure you clean the npm cache beforehand

## Diff
- typescript is not needed globally as it is either used from `grunt-ts` or from
- Correct version of Node has to be installed
- `sudo` should not be used when installing packages either globally or locally.
- suggestion to fix EACCESS error

**Comment by adidahiya** [comment]
@endrjuskr you recently updated your Plottable dev environment, right? Can you take a look at these setup instructions and send a PR if the updates look good?
