### ISSUE TITLE
Customizing number of rectangles on Interpolated Color Legend

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2854]
Feature Request from Slate
*  want the number of rectangles to be less than or equal to values in its domain
* currently: scale has a domain from [0 to 10] but the interpolated legend if stretched can have 10+ rects

**Comment by christinaforney** [comment]
@crmorford - didn't you fix this last week? Can you link the associated PR?

**Comment by jtlan** [comment]
Since `InterpolatedColorLegend` is continuous now this issue seems to be invalid.

**Comment by bluong** [comment]
We should close this unless we want to reword to the following possible enhancement:  Now that we have continuous `InterpolatedColorLegend`s, it should be decently feasible to set how far the legend extends in pixels.

**Comment by christinaforney** [comment]
Talked to Slate - ok to close
