### ISSUE TITLE
Padding on InterpolatedColorLegend

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2856]
![image](https://cloud.githubusercontent.com/assets/7527733/10326152/a951e520-6c4c-11e5-9d5b-d63a4c8c68e7.png)
Here's an example: Slate would like to be able to place padding between the plot and legend. We don't have a way to do that right now (maybe legend.xAlignment("right"), but it isn't super customizable.

Ideally, they'd like to set a fixed amount of padding around the legend component (measured in pixels)

The API suggested is something like table.padding(row, col, 20);
However they'd like to be able to do just leftPadding, just rightPadding, top, bottom.

Maybe component.padding(pixelAmount, arrayOfDirections)
so you'd call it like:
component.padding(20, ["left", "bottom"]);

**Edit: the key ask behind this issue is that the legend is too close to the plot. We probably won't resolvve this with a padding API point, but just adjust the legend padding**

**Comment by jtlan** [comment]
For reference, the `Table` API points are:
```Typescript
public rowPadding(rowPadding: number): Table;
public columnPadding(columnPadding: number): Table;
```
