### ISSUE TITLE
AutoDomain doesn't seem deterministic

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#2858]
This Plot autoDomains both scales on Clicks
http://jsfiddle.net/j5b9f60c/53/
On each click, the bars jump around, so it seems like autoDomain is making different decisions everytime. That's weird.

**Comment by jtlan** [comment]
Turned off the `yScale` domain-setting at the beginning, which reveals that only `xScale` jumps around:
http://jsfiddle.net/j5b9f60c/62/

Which means this is the same as #2941.
