### ISSUE TITLE
Exception thrown by entityNearest() on plot with no visible data 

### ISSUE THREAD

**Issue by istarnx** [palantir/plottable#2925]
It appears that your code doesn't handle the "no entity nearest" case in Plot.entityNearest().

**Comment by jtlan** [comment]
Details: Doesn't happen on `Line` and `Bar`, which use slightly different algorithms.

**Comment by jtlan** [comment]
Issue is probably in `Plot`'s `_lightweightPlotEntityToPlotEntity()` method, which doesn't expect `undefined` as an input.

**Comment by jtlan** [comment]
Fixed in https://github.com/palantir/plottable/pull/2945, I believe.
