### ISSUE TITLE
Cannot scroll out when time axis is 0NaN

### ISSUE THREAD

**Issue by mato75** [palantir/plottable#2944]
http://plottablejs.org/examples/spacerace/

**Comment by jtlan** [comment]
Thanks for flagging this, @mato75; the example should be fixed now.

It seems like this is the same issue as https://github.com/palantir/plottable/issues/2437. We'll look into whether we should add default zoom limits on `QuantitativeScale`s.

**Comment by MaestroJurko** [comment]
The same goes for http://plottablejs.org/examples/weather/ and http://plottablejs.org/examples/finance/. I think the zoom limit would be awesome.
