### ISSUE TITLE
[Future] Remove Plots.Wheel

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#2957]
Development of it was stopped halfway, and it appears that the users who initially asked for it wound up using `Plots.Rectangle` for its use case instead. If we go to 2.0.0, we should roll it back until it is ready.

**Comment by jtlan** [comment]
If we do roll it back, we should be able to close the following tickets:
* https://github.com/palantir/plottable/issues/2683
* https://github.com/palantir/plottable/issues/2684
* https://github.com/palantir/plottable/issues/2693
* https://github.com/palantir/plottable/issues/2694

**Comment by ztsai** [comment]
on 2.0 branch
