### ISSUE TITLE
Use a tsconfig to compile tests

### ISSUE THREAD

**Issue by softwords** [palantir/plottable#2993]
tsconfig.json could be used to compile the tests, eliminating the need for testReferences.js.

-- move the tsconfig.json for the src compile to `src`
-- create a tsconfig.json in `test` for the test compile

use the option `outFile` rather than `out` in both tsconfig.json files. outFile is relative to the location of tsconfig.json.

Go up to `grunt-ts` 5.1.0 which supports `outFile`

You can specify the path to the tsconfig in the gruntfile:

``` javascript
 var tsConfig = {
    app: {
      tsconfig: "./src"
    },
    test: {
      tsconfig: "./test"
    }
  };
```

**Comment by hellochar** [comment]
Fixed when we moved from grunt to npm scripts
