### ISSUE TITLE
Is there possibility of NPM publish?

### ISSUE THREAD

**Issue by SamMorrowDrums** [palantir/plottable#3005]
I understand that multiple publishing comes with it's own issues, but for anyone who is using npm for all deps (including client side), this would be a really awesome feature.

**Comment by LukeSheard** [comment]
I would really love this to be implemented. While I love this library it's frustrating to use with webpack.

**Comment by adidahiya** [comment]
+1, this is on the roadmap pretty soon

**Comment by aaronhayes** [comment]
Is there an ETA on this? I'd really love to use plottable but this is holding me back.

**Comment by SamMorrowDrums** [comment]
Just wanted to check. I can see there is a version 3.x milestone. Will NPM version be usable when version 3 is released?

**Comment by adidahiya** [comment]
Hey folks, sorry for the delay on this. I understand the pain with NPM consumption right now. We are looking into this more seriously in the next couple weeks. We'll also have to migrate the svg-typewriter dependency to NPM.

**Comment by adidahiya** [comment]
In progress here: #3077

**Comment by adidahiya** [comment]
We've published the first beta release on NPM, v2.0.1-beta.0: https://www.npmjs.com/package/plottable

Can you try it out and let us know if there are any issues? We'll try to publish a real (non-beta) release later today.

**Comment by adidahiya** [comment]
Published v2.1.0 to NPM 🎉  https://github.com/palantir/plottable/releases/tag/v2.1.0
