### ISSUE TITLE
Is it possible to add Plots after chart is rendered.

### ISSUE THREAD

**Issue by mato75** [palantir/plottable#3006]
I would like to add Scattered and Line plot to stacked area.

Something like this:
https://jsfiddle.net/cdx3521r/1/ 

What is the easiest way to do this?

**Comment by jtlan** [comment]
You'll want to create a `Group`, then add all the `Plot`s to it. If the `Plot`s are powered by the same `Dataset`s they should show points in the same place. In this case, however, there is the complication that the `StackedArea` sums the values for a given key, so you'll have to recompute that.
