### ISSUE TITLE
Plottable Broken with Browserify Builds

### ISSUE THREAD

**Issue by SamMorrowDrums** [palantir/plottable#3008]
This issue is in regard to the pre-built bower package version (testing using non-minified, same issues with both however).

For some reason, when loading in Browserify context, the `this` reference to the global object is not working, and all the assignments of the  `__extends = this.__extends ||` function break because this is undefined. Yes, even though in the first instance this is checked with `(this && this.__extends)`!

Also, the node JS sniffing is also causing problems, so I have made `exports  = undefined`. This makes it run as if it's in a pure browser context.

I can successfully get it to build with the code below, however I feel like this is so close to being able to run in the context, that it should be possible to achieve!

The goal is to use `require`, and ideally from NPM, but pulling it in from bower can work so long as we can get past these minor issues.

```
// use BRFS to load static file as variable
let plot = fs.readFileSync(path.join(__dirname, "../../public/lib/plottable/plottable.js"), "utf8");

// Remove the two different forms of problematic assignment, that occur numerous times throughout the file (and don't lay into the regex, it was good enough to work :-p)
plot = plot.replace(/var __extends = .+\n.+\n.+\n.+\n\};/gm, "");
plot = plot.replace(/var __extends = .+\n.+\n.+\n.+\n.+\n\};/mg, "");

// Make a function that defines the extends function
plot = `(function (exports) {console.log(this);
    var __extends = function (d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
    this.__extends = __extends;
   // evaluate the code, now it's ready for execution
    ${plot}

}.bind(window))(undefined)`;
eval(plot);
```

**Comment by SamMorrowDrums** [comment]
For now I've resourced to pre-building this into usable form for require, however I'm still really hoping we can find a way to make Plottable work in as many places as possible.

**Comment by hellochar** [comment]
We now use webpack to build the bower plottable.js and the `this` in `__extends = this.__extends || ` should now reference the specific module being wrapped so I don't think this is an issue anymore. Also our code is in module format now so if you're in an npm environment you can just `npm install plottable` and `require("plottable")` and you should be good to go!
