### ISSUE TITLE
Custom AxisLabel text as per yAxis Value

### ISSUE THREAD

**Issue by Sutikshan** [palantir/plottable#3040]
Hi,
I would like to print AxisLabel near yAxis to deonote two important value of threshold on my line chart.
But it is not possible to supply numerical value on yAlignment , while defining AxisLabel, my code is - 

```
  var thresholdLabel = new Plottable.Components.AxisLabel(thresholdObj.max, 0)
  .padding(10)
  .yAlignment(thresholdObj.max)
  .xAlignment('right')
  .addClass('zoom-hint-label');
```

where thresholdObj.max is yAxis value of threshold line, I have drawn.

![screen shot 2015-12-18 at 11 51 22 am 1](https://cloud.githubusercontent.com/assets/1274910/11891879/c883c31c-a588-11e5-934d-04afc415734b.png)

**Comment by jtlan** [comment]
Hello @Sutikshan 

This should be done by using a `Axes.Numeric`, but flipped over, merged with the `Plot`, and with the alignment set correctly. Let me give you an example:

https://jsfiddle.net/qLxmohfb/

Let me know if that works for you.

**Comment by Sutikshan** [comment]
Thanks @jtlan . I want to draw two lines only, as these lines are denoting upper limit of blood-sugar readings. and label text for these two lines only. I am drawing line using Plottable.Plots.Line() class. Is there anyway I can print text above these two lines only.

**Comment by jtlan** [comment]
@Sutikshan It might be easier to do that by setting a `tickGenerator` on the `Scale`:

``` Javascript
var minValue = 0.27;
var maxValue = 0.78;
yScale.tickGenerator(function() {
  return [minValue, maxValue];
});
```

https://jsfiddle.net/qLxmohfb/1/

**Comment by Sutikshan** [comment]
Thanks. It is done using tickGenerator.
