### ISSUE TITLE
Bar chart with modified log axis is broken

### ISSUE THREAD

**Issue by istarnx** [palantir/plottable#3045]
Create a bar chart with a modified log y-axis. Ensure a y-value of at least 100. Note that the axis doesn't render.

**Comment by adidahiya** [comment]
@istarnx can you please throw together a quick JSFiddle with a repro?

**Comment by istarnx** [comment]
Even simpler repro: the bars themselves don't render. http://jsfiddle.net/t0zsdd1h/

**Comment by adidahiya** [comment]
likely caused by #3029
