### ISSUE TITLE
Space Race example in Firefox not working

### ISSUE THREAD

**Issue by Maksims** [palantir/plottable#3084]
This example does not plots data in Firefox Nightly 50.0a1 (2016-06-30):
http://plottablejs.org/examples/spacerace/

It works well in Chrome.
There are no console log errors, and quick look from code, seems like data is loaded and parsed well, but then it is not added to a plot.
Additionally while data is loading or not available, callback in onPointerMove assumes there will be always at least one entity, but that is not the case, which leads to exceptions while mouse is moved above plot when no data is available.

**Comment by CalvinFernandez** [comment]
Seems to also be broken in Safari
