### ISSUE TITLE
Enable events API for Pan and Zoom

### ISSUE THREAD

**Issue by SamMorrowDrums** [palantir/plottable#3086]
The pan and zoom interaction is really nice, but it's also an excellent opportunity for developers to enable dynamic loading of data.

I suggest adding event listeners, that are triggered at the end of Pan events and Zoom events, so it is possible to fill in the missing data. The user can then, for example, check the scale domains on callback, and make a request for the data they haven't downloaded yet.

**Comment by yocontra** [comment]
This can be closed (#3087 landed)
