### ISSUE TITLE
Per-label Formatting Option for plot.labelFormatter(d)

### ISSUE THREAD

**Issue by freedomflyer** [palantir/plottable#3088]
I've dug a lot, but haven't found a way to do custom, per-label formatting. As you see below, `labelFormatter` is only given one argument, `d`, so there's nothing else to key off of to intelligently format a label differently than any other label. However, in other methods such as `attr(d, i, dataset)`, I have that information.  Getting that information to labelFormatter seems trivial, and would be very useful in my use-case.

Is there a way around this? Otherwise, this is a feature request that seems fair. Something like `labelFormatter(d, i, dataset)`

``` ts
myPlot
.labelFormatter(d => {
    // All bars will be formatted only one way
    return myFormatter.display(d);
})
.attr('plot-index', (d, i, dataset) => {
    // Here, however, I have access to the dataset and index, so I can perform more custom logic
    return myAttrFunction(d, i, dataset);
})
```

**Comment by hellochar** [comment]
There's an 80% ready PR at https://github.com/palantir/plottable/pull/3226 ; maybe we can just touch it up and get this in?
