### ISSUE TITLE
Upgrade to D3V4

### ISSUE THREAD

**Issue by teamdandelion** [palantir/plottable#3091]
Are there any plans to upgrade Plottable to use d3 version 4?

**Comment by pchaganti** [comment]
+1

**Comment by CalvinFernandez** [comment]
Currently blocked by https://github.com/palantir/svg-typewriter/issues/38

**Comment by themadcreator** [comment]
Heh, easy for you to say @danmane, =P

This is gonna be a pretty big update, I expect. But, I think we're going to give it a shot.

**Comment by teamdandelion** [comment]
Yo yo, it's @themadcreator!  😀 

Any timeline for the upgrade? If it could happen by end of Q1 that would be greeaaaaaaat, mkay? 😉
