### ISSUE TITLE
PanZoom interaction disrupts page scrolling

### ISSUE THREAD

**Issue by devnev** [palantir/plottable#3092]
I have a number of line plots which have horizontal panzoom enabled. The current implementation is very disruptive as a user may scroll down a page only to get stuck on a plot that is then zoomed in or out. I would like the zooming of these plots to only occur when the shift key is pressed (shift key is also commonly used for horizontal scroll) so that the user can scroll up and down the page naturally.

**Comment by yocontra** [comment]
Shift seems weird, how about if the element is focused (clicked)?

**Comment by devnev** [comment]
Shift is commonly used for horizontal scrolling, and I think I've encountered it in the past. Beyond that I'm happy either way. Probably should make this behaviour toggleable as graphs filling a whole page probably want the current zoom-on-scroll behaviour.

**Comment by SamMorrowDrums** [comment]
I implemented my own lock, unlock stuff for this (little clickable icon in corner of chart). You can quite easily add an interaction for click if you want, and then add / remove the panZoom interaction.

Different users will want different methods of controlling the interaction though, so it can't be baked-in really. If you experiment with a couple of triggering events, you can make it behave correctly. I'd recommend giving it a try.

**Comment by adidahiya** [comment]
I'm inclined to agree with @SamMorrowDrums's suggestion of adding / removing the pan zoom interaction imperatively as necessary -- that feels like the right level of abstraction for plottable in this use case.

**Comment by devnev** [comment]
That does sounds reasonable. In that case, however, would it be possible to have uncomposed Pan and Zoom interactions?

**Comment by hellochar** [comment]
With #3399 you can now configure a custom wheel filter to e.g. only scroll when `wheelEvent.shiftKey` is true. You can configure the pan interaction in a similar fashion by using `panZoomInteraction.dragInteraction().mouseFilter((e) => e.shiftKey)`
