### ISSUE TITLE
Colored (title) label

### ISSUE THREAD

**Issue by siFeiden** [palantir/plottable#3095]
Hi, I'd like to create a title label with green text color. I already tried `label.addClass('text-green')` and

```
.text-green {
  fill: #00ff00;
  color: #00ff00;
}
```

in my CSS but both do not seem to be working. Is there any other way I'm overlooking?

**Comment by BaEigner** [comment]
The addClass methods adds the class to a container parent element:

![image](https://cloud.githubusercontent.com/assets/10982245/19509420/e9116b10-95de-11e6-89cf-60944cf43657.png)

Just add text selector and !important to your class:

.text-green text {
    fill: #00ff00 !important;
}

It works for me:

![image](https://cloud.githubusercontent.com/assets/10982245/19509434/f1cb098c-95de-11e6-896e-9be2e786f1da.png)

2016-10-18 18:37 GMT+02:00 Simon Feiden notifications@github.com:

**Comment by siFeiden** [comment]
Yes this works! Thanks
