### ISSUE TITLE
Scatter plot with text labels

### ISSUE THREAD

**Issue by siFeiden** [palantir/plottable#3103]
Hi, I'd like to create a scatter plot where each data point either is a text label or is an icon that has a text label right next to it. Find an example [here](http://www.clear-lines.com/blog/image.axd?picture=WindowsLiveWriter/ExcelScatterPlotwithlabelscolorsandmarke/1C1462E0/PowerScatterPlot_thumb.png).

Is this possible?

**Comment by CalvinFernandez** [comment]
Hey @siFeiden, unfortunately this isn't possible at the moment -- would you like me to open a feature request for this?

**Comment by siFeiden** [comment]
Hi @CalvinFernandez , yes this would be great!

**Comment by hellochar** [comment]
Dupe of #2617, lets consolidate conversation over there ( @siFeiden looks like there's discussion of some workarounds in that thread)
