### ISSUE TITLE
Having an option or method to place pie labels inside or outside the pie slices

### ISSUE THREAD

**Issue by epicallan** [palantir/plottable#3105]
It would be great if we could specify whether we want the pie slice labels  inside the pies or outside the pie with an option of having a connector to the pie slice or not for the outside labels.

If some one has already implemented this, please point me to your folk, in the meantime i will take a stab at implementing this.

**Comment by epicallan** [comment]
Ended up implementing something similar to what we wanted by extending the draw labels method.

**Comment by CalvinFernandez** [comment]
Cool @epicallan, if you have a chance, can you share the extended draw labels method here or in a gist so others can benefit as well !

**Comment by epicallan** [comment]
Hey we found extending the draw labels method to be problematic for cases when we would want the original behaviour. So we just created another draw labels like function. below is a fiddle.
http://jsfiddle.net/epicallan/36suv9a0/4/

**Comment by epicallan** [comment]
@CalvinFernandez wouldn't it be nice if we had a central place for hosting various plottable chart fiddles for various people to learn from. I and my team have quite a number that have some really custom charts.
