### ISSUE TITLE
percent area chart?

### ISSUE THREAD

**Issue by yocontra** [palantir/plottable#3110]
Is it possible to do this with the existing area chart component or does a new one need to be made?

http://recharts.org/examples#PercentAreaChart

Will send a PR if you point me in the right direction

**Comment by CalvinFernandez** [comment]
Thanks for the question! You can do this with the existing area component by manipulating your data such that the dependent axis values are a ratio  . 

https://jsfiddle.net/5Lcng8n2/5/
