### ISSUE TITLE
v2.3.0 NPM distribution

### ISSUE THREAD

**Issue by SamMorrowDrums** [palantir/plottable#3114]
When building a JS bundle with Browserify, I get the error`SVGTypewiter is not defined` in the browser console, when trying to draw charts. I've tried bundling without minifying etc. and the issue does not occur with 2.2.0, so I am assuming that there is a genuine issue with the NPM distribution of Plottable 2.3.0.

**Comment by CalvinFernandez** [comment]
thanks for the flag @SamMorrowDrums looking now
