### ISSUE TITLE
set zoom in zoom out using external controls

### ISSUE THREAD

**Issue by awsumnik** [palantir/plottable#3141]
Hi,

I have a requirement where I need to zoom in and zoom out over a Quantitative time scale using some external buttons (say one for zooming in and another for zooming out).

Is there a way I can get and set zoom levels for  a chart as per the click on these buttons.

**Comment by CalvinFernandez** [comment]
hey @awsumnik there isn't a way to control the zoom interaction externally. You can get the effect you want by fiddling with the domain of your scale, however

**Comment by awsumnik** [comment]
@CalvinFernandez - Is there an example of what you have mentioned ? If yes, can you please share.

**Comment by CalvinFernandez** [comment]
@awsumnik #3146  should help you do this
