### ISSUE TITLE
Performance: Make label drawing faster in SVG Typewriter

### ISSUE THREAD

**Issue by CalvinFernandez** [palantir/plottable#3142]
@themadcreator I know you did a lot of work already during hackweek -- has this already merged?

There was also some talk of just abandoning svg-typewriter and pulling directly into plottable. Are we going to do this?

**Comment by adidahiya** [comment]
+1 for putting svg-typewriter source into this codebase

**Comment by hellochar** [comment]
Filed https://github.com/palantir/svg-typewriter/issues/41
