### ISSUE TITLE
Category axis labels containing many spaces disappear

### ISSUE THREAD

**Issue by hellochar** [palantir/plottable#3152]
Repro: https://jsfiddle.net/hellochar/0zg2jkus/

svg-typewriter's Measurer ignores whitespace in its calculations. Labels with lots of whitespace may be measured to be just below the maximum width, but be rendered in the DOM wider than the axis width (because of the whitespace). categoryAxis will then hide that label because it is overflowing the bbox of the axis.

The number of spaces needed to trigger the bug depends on `tick length + tick padding + axis margin`. If the unaccounted whitespace length (which is ~3px per space with the default font) is greater than that number, it will overflow. 

Possible solutions:
* Make svg-typewriter account for whitespace
* Modify _hideOverflowingTickLabels' "overflowing" detection (e.g. instead of BBox, check if the range value is outside of [0, 1])

**Comment by themadcreator** [comment]
seems like the right solution is to make svg-typewriter account for whitespace

**Comment by themadcreator** [comment]
This is fixed, closing
