### ISSUE TITLE
Pie chart, support for padAngle

### ISSUE THREAD

**Issue by armano2** [palantir/plottable#3166]
Propably i do not understund somethink but d3 allows us to set `padAngle` to pie charts

http://bl.ocks.org/mbostock/f098d146315be4d1db52

idk how to set this value by plottable, 

In code i found `startAngle`, `endAngle`, `outerRadius`
```ts
protected _propertyProjectors(): AttributeToProjector {
      let attrToProjector = super._propertyProjectors();
      let innerRadiusAccessor = Plot._scaledAccessor(this.innerRadius());
      let outerRadiusAccessor = Plot._scaledAccessor(this.outerRadius());
      attrToProjector["d"] = (datum: any, index: number, ds: Dataset) => {
        return d3.svg.arc().innerRadius(innerRadiusAccessor(datum, index, ds))
                           .outerRadius(outerRadiusAccessor(datum, index, ds))
                           .startAngle(this._startAngles[index])
                           .endAngle(this._endAngles[index])(datum, index);
      };
      return attrToProjector;
}
```
https://github.com/d3/d3-3.x-api-reference/blob/master/Pie-Layout.md

**Comment by hellochar** [comment]
Hey @armano2 thanks for your interest. We don't actually expose that option in Plottable but it's a reasonable feature request. We'd welcome a PR to add support for it.

**Comment by armano2** [comment]
i already started working on implementing this 🗡
