### ISSUE TITLE
Bar labels should be more conservative about requesting space

### ISSUE THREAD

**Issue by adidahiya** [palantir/plottable#3196]
Instead of drawing labels when text barely fits within a bar, I'd like labels to request 10px of extra padding on all sides before being drawn. This requires users to zoom in or create less dense charts in order to see labels. Currently, it is too easy to draw plots with too much visual complexity with labels.

![2017-02-01 14 31 47](https://cloud.githubusercontent.com/assets/723999/22526174/3b3f495a-e898-11e6-8e84-42f4ed0e7da8.gif)

Note that this is a small visual breaking change because some charts will now hide labels more often.

**Comment by pkwi** [comment]
+1 for the extra padding around the label.
We should also standardise when do we show labels. It's strange that some labels show up and some don't. We should show labels when all fit (by the longest label).
