### ISSUE TITLE
bar and stackedbar plots are slow

### ISSUE THREAD

**Issue by BaEigner** [palantir/plottable#3219]
Sorry if this is already posted. My problem is that the drawing of bar plots, especially stackedbar are extremely slow compared to e.g. line. Created a JSFiddle to demonstrate this:

https://jsfiddle.net/BaEigner/17yq0zne/

It draws 3 different charts:

- one with two bar plots mimicking the stackedbars
- one with a simple stackedbar plot
- and one with two line plots for performance comparison

Performance for each is measured:

- the cost of plot creation
- the render time
- and the total time taken

It draws 100 points, but you can change it in the first line. So the result are:

My laptop (2015 15" RMBP, OS X El Capitane, Chrome): 
1.1 Bar Plot 1: 29 ms
1.2 Bar Plot 2: 53 ms
1.3 Bar Render: 453 ms
**1.0 Bar Total: 563 ms**
2.1 StackedBar Plot: 300 ms
2.2 StackedBar Render: 782 ms
**2.0 StackedBar Total: 1160 ms**
3.1 Line Plot 1: 2 ms
3.2 Line Plot 2: 1 ms
3.3 Line Render: 27 ms
**3.0 Line Total: 35 ms**

Our webserver (Windows Server 2012, 4 core Xenon @2,6GHz, Chrome -- but it not really counts...):
1.1 Bar Plot 1: 126 ms
1.2 Bar Plot 2: 217 ms
1.3 Bar Render: 1663 ms
**1.0 Bar Total: 2113 ms**
2.1 StackedBar Plot: 900 ms
2.2 StackedBar Render: 3982 ms
**2.0 StackedBar Total: 5210 ms**
3.1 Line Plot 1: 6 ms
3.2 Line Plot 2: 6 ms
3.3 Line Render: 86 ms
**3.0 Line Total: 116 ms** 

A random windows laptop at the company (Chrome): 
1.1 Bar Plot 1: 38 ms
1.2 Bar Plot 2: 62 ms
1.3 Bar Render: 614 ms
**1.0 Bar Total: 752 ms**
2.1 StackedBar Plot: 350 ms
2.2 StackedBar Render: 1052 ms
**2.0 StackedBar Total: 1500 ms**
3.1 Line Plot 1: 2 ms
3.2 Line Plot 2: 1 ms
3.3 Line Render: 24 ms
**3.0 Line Total: 29 ms**

Are there any workarounds, fixes or anything to make the bars faster? If you draw one of them it's let's say, okay, but in some cases we have to draw 10-20 at a time.

**Comment by adidahiya** [comment]
This performance is consistent with what we expect when manipulating more DOM nodes. A line plot only requires one `<path>` for a single series, while a bar plot requires a `<rect>` node per data point. You can see this difference when you inspect the SVG.

We _are_ generally interested in fixing performance problems in Plottable, but this issue isn't really framed in a tractable way at the moment.

**Comment by BaEigner** [comment]
Thanks for the response, it really makes sense. :) Only one more question: then why there's a significant performance difference the two bar plots (I mean the simple bar based "stacking" and the stackedbar), and not only in the rendering part, but the plot creation?

**Comment by hellochar** [comment]
@BaEigner I've been tracking bar chart performance; you're right in that there is a lot of unnecessary computation being done right now. One major contributor is that `Bar.render`, which should be fast (its responsibility is only to queue the bar chart to render in the next frame), instead calls `Plot.updateExtents()` which does a linear pass through all the data, and is even in some cases recursive. I attempted to tackle this about a month ago but couldn't figure it out exactly. Will keep this ticket updated if we tackle it again

**Comment by BaEigner** [comment]
Thanks @hellochar, I'll stay tuned and looking forward for the results of your investigation. Thank you for your efforts!
