### ISSUE TITLE
Plottable.js Custom Formatters

### ISSUE THREAD

**Issue by realph** [palantir/plottable#3222]
Does anyone know how to achieve custom formatting when using [Plottable.js][1]. You used to be able to pass in a function to the `Custom()` method to format your numbers, like so:
    
    let customFormatter = new Plottable.Formatter.Custom(someCustomFunction);
    let yAxis = new Plottable.Axes.Numeric(this.yScale, 'left').formatter(new Plottable.Formatter.Custom(customFormatter))
    

Any idea how to do this in the latest release?

Any help is appreciated. Thanks in advance!

  [1]: http://plottablejs.org/

**Comment by BaEigner** [comment]
Just pass a function to the formatter, like:
```

function axisFormatter(d) {
	return d + '.0%';
} 

var yAxis = new Plottable.Axes.Numeric(yScale, "left");
yAxis.formatter(axisFormatter);
```
Working example: https://jsfiddle.net/BaEigner/z72w7mbk/

Hope that I did not misunderstood you question. :)

**Comment by hellochar** [comment]
@BaEigner's answer is correct (thanks!).

**Comment by mac066** [comment]
Formatter doesn't work for time scale
