### ISSUE TITLE
DoubleClickInteractions sometimes doesn't fire onDoubleClick

### ISSUE THREAD

**Issue by leebyp** [palantir/plottable#3246]
Repro steps:
- set the DoubleClickInteraction on a plot
- add a callback to the handler
- click once
- without moving the mouse, double click
- the double click interaction doesnt fire

Source of bug:
- the double click interaction is distinguishing between click and doubleclick using an internal enum, and time independent logic which can become out of sync if you click in the same position.

**Comment by adidahiya** [comment]
Is the [`dblclick`](https://developer.mozilla.org/en-US/docs/Web/Events/dblclick) event not sufficient in this case?

**Comment by leebyp** [comment]
@adidahiya do you mean in `DoubleClickInteraction.ts` file? I'm not sure why it uses the internal state.

**Comment by leebyp** [comment]
fixed with #3252
