### ISSUE TITLE
Migrate our tests to use jest framework

### ISSUE THREAD

**Issue by hellochar** [palantir/plottable#3285]
The jest testing framework is better suited to modern tooling; move onto that.

It has a JSDOM implementation that runs on node. It also has mocks, coverage, describe/beforeEach/afterEach, and expect built in (so we could get rid of sinon, mocha, karma, and chai).

You can't run Jest tests in the browser directly which might be more of a roadblock for us.

Saucelabs assumes that your unit tests are runnable by visiting a particular web page; this might not work with jest since jest runs only on node.

**Comment by adidahiya** [comment]
See https://github.com/palantir/plottable/pull/3282#issuecomment-288145388; you'll need to continue using Phantom to simulate browser layout, which is important for testing chart layouts

**Comment by hellochar** [comment]
You're right; closing this for now since it's inactionable
