### ISSUE TITLE
Axis Labels render without the text in Firefox

### ISSUE THREAD

**Issue by leebyp** [palantir/plottable#3323]
When using `new Plottable.Components.AxisLabel("test label")`, the element is in the DOM but the text is not

NOTE: this only happens on Firefox & retina screens

@acolombi

**Comment by hellochar** [comment]
Can you provide a more concise repro? I visited https://409-16149854-gh.circle-artifacts.com/0/home/ubuntu/plottable/quicktests/dev/index.html#functional/nearestEntity on Firefox and had labels

**Comment by leebyp** [comment]
Gosh... this took a while to figure out. It's only happening on retina screens!

**Comment by hellochar** [comment]
Got it - repro is to open https://409-16149854-gh.circle-artifacts.com/0/home/ubuntu/plottable/quicktests/dev/index.html#realistic/rainfall_ClusteredBar on a retina display

Looks like the results of computeLayout are different in a retina display such that typesettable doesn't think it has any room to fit the label... @themadcreator thoughts?

**Comment by hellochar** [comment]
Fixed in #3344
