### ISSUE TITLE
Legend maxEntriesPerRow not respected in Firefox

### ISSUE THREAD

**Issue by leebyp** [palantir/plottable#3324]
`legend.maxEntriesPerRow(n)` becomes n - 1 in Firefox

NOTE: this only happens on Firefox & retina screens

@acolombi

**Comment by acolombi** [comment]
See #3344

**Comment by hellochar** [comment]
Hey @acolombi did #3344 fix this as well?

**Comment by acolombi** [comment]
yup

**Comment by hellochar** [comment]
Great!
