### ISSUE TITLE
__VERSION__ is not defined

### ISSUE THREAD

**Issue by clarkmoody** [palantir/plottable#3338]
Upgraded to `3.1.0` just now, and when I `require('plottable')` in my project, I get `__VERSION__` not defined.

The browser points me to `core/version.js` that contains the offending line. Perhaps the `sed-version` task did not run properly for this build?

I'm using watchify 3.8.0 and browserify 13.1.1

**Comment by hellochar** [comment]
@clarkmoody Oof, thanks for the bug report, we really should have an automated test for that. Will get this fixed immediately...

**Comment by clarkmoody** [comment]
Thanks! New version `3.3.1` works well.
