### ISSUE TITLE
plottable.zip does not contain plottable.js or typings files

### ISSUE THREAD

**Issue by teamdandelion** [palantir/plottable#3339]
The Plottable release zip archive used to contain plottable.js, as well as working .d.ts files.
In the most recent release archive:

- plottable.js is missing.
- plottable.d.ts references a 'build' directory which does not exist in the archive.

**Comment by hellochar** [comment]
Yo @dandelionmane ! We've mostly deprecated the zip file; is there something about the zip that npm and unpkg.com don't do?

**Comment by teamdandelion** [comment]
For TensorFlow/TensorBoard we are going to download Plottable manually from npm's servers, so we won't need the zip file any more. It's fine with us if you delete it.

**Comment by hellochar** [comment]
Sounds good
