### ISSUE TITLE
PointerInteraction doesn't respect the Component's translated bounds

### ISSUE THREAD

**Issue by hellochar** [palantir/plottable#3345]
From gitter:

> The pointer interaction translates the point to component space (LinePlot). p: {x:53,y:140}, translatedP: {x: 2.98, y:140}. This makes sense. Then in retrieving the entities they are mapped via _lightweightPlotEntityToPlotEntity and their real ??component?? position is calculated. e.g. my first entity is pos: (x: 10, y: 97) where this pos should be relative to the LinePlot right? not to the whole table.
https://github.com/palantir/plottable/blob/v3.0.0/src/plots/xyPlot.ts#L409
Then in https://github.com/palantir/plottable/blob/v3.1.0/src/plots/linePlot.ts#L488 the point is checked if it is within bounds, but these bounds are relative to the entire Table, not the Line. my bounds.topLeft is (43,0) because of the y-axis

Repro: ![hover missing points](https://cloud.githubusercontent.com/assets/1079495/26020773/d0a3df04-3737-11e7-80dc-99b9c1bbc64d.gif)

1. Open interaction_hover_scatter
2. Mouse around on the bottom-left corner. You may have to refresh the page a few times to see the random data get within the threshold of ignored points

**Comment by leebyp** [comment]
same issue as #3268 for more details

**Comment by hellochar** [comment]
Closing this as dupe of #3268
