### ISSUE TITLE
FR: True Log Scale

### ISSUE THREAD

**Issue by teamdandelion** [palantir/plottable#3348]
For applications where the data is in the range (0, 1], Plottable's modified log scale is essentially useless. Can we have a true log scale implemented please?

**Comment by hellochar** [comment]
Agreed. We can't make guarantees about timeline here so your best bet is to submit a PR (could probably just copy/paste modifiedLog with a few adjustments). Or as a workaround you can try ModifiedLog with setting `scale._pivot = 0`
