### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by simpers** [palantir/plottable#3349]
I'm a bit worried about your suggestion of running

    sudo chown -R /usr/local

without giving any reasoning (apart from some error code) as to why this would be a good idea. Changing ownership of OS files/folders is to me not a good fix for anything, and should be solved in a distro-specific manner I would assume.

Same applies to OSX, I suppose.

Could you either elaborate what goes wrong and please not encourage possibly breaking systems by just telling people to write things like this?

If I'm wrong though I'd love to know why.

**Comment by adidahiya** [comment]
I think we can remove that part of the README. It was put there a while go to tell users how to get around permissions errors in running binaries since homebrew and npm install global binaries in `/usr/local` by default.

**Comment by hellochar** [comment]
Yeah good call @simpers , we should clarify it. We'd be happy to accept a PR that modifies the README to your liking
