### ISSUE TITLE
Multiple colorScale on Heatmap

### ISSUE THREAD

**Issue by cosbgn** [palantir/plottable#3352]
I'm trying to build a heatmap which compares different metrics for the same category, in other words the Y axis is the same but the X axis are completely unrelated between them. Something like [this](http://jsfiddle.net/mf5e58tL/2/) (Made with plot.ly which doesn't support this feature).

Is it possible to have a heatmap with different colour schemas for each X axis?

**Comment by hellochar** [comment]
Thanks for the interest in Plottable! We don't currently support this but probably could allow different datasets to have different color scales in the Rectangle Plot.

As a workaround you could pre-compute your datum to have the final "color" value directly in the datum, and then access that in the Rectangle Plot's `.fill()`

**Comment by hellochar** [comment]
Resolved on Gitter:

1. Create two InterpolatedColor scales: `var scale1 = new Plottable.Scales.InterpolatedColor(); var scale2 = new Plottable.Scales.InterpolatedColor();`
1. set their colors: `scale1.range(["red", "blue"]); scale2.range(["green", "yellow"])`
1. pre-compute your data to run through the different scales:
```
for (var i in dataArray) {
  var datum = dataArray[i];
  if (datum.category === "cat1") { datum.color = scale1.scale(datum.value); }
  if (datum.category === "cat2") { datum.color = scale2.scale(datum.value); }
}
```
4. finally, tell RectanglePlot to look at the datum's color property: `plot.attr("fill", (datum) => datum.color);`
