### ISSUE TITLE
Tricky downloading plottable.min.js

### ISSUE THREAD

**Issue by src73** [palantir/plottable#3364]
I just tried upgrading to the latest version (3.1.1) and encountered two issues: 

1. clicking the "download (latest)" button on [plottablejs.org](http://plottablejs.org/) downloads the latest off of the Master branch, which hasn't been updated since 2015. 
2. the commit tagged 3.1.1 doesn't include a plottable.min.js file (or even plottable.js). This breaks [unpkg](https://unpkg.com/plottable@3.1.1/plottable.min.js), and makes it very difficult for those without NPM or Yarn to use the latest version of the library, even if just download the repo. 

Do let me know if I'm missing something..

**Comment by hellochar** [comment]
Hey @src73 , thanks for the report. 1 is filed as #3342 , apologies for that - we'll try to get around to it in the upcoming weeks.

I'm able to find the standalone `plottable.js` in 3.1.1 at `https://unpkg.com/plottable@3.1.1/plottable.js`, but I'd recommend pulling in Plottable through individual js modules npm/yarn - you'll notice `package.json`'s main points to `build/src/index.js`. It's also for that reason we've recently removed the standalone .min.js file - we expect consumers to use Plottable with a module bundler like webpack or rollup, which has full bundle minification features. Does that work with how you are consuming the library?

**Comment by MartinKolarik** [comment]
@src73 if you want to use the file directly from a CDN, you can use [jsDelivr](https://github.com/jsdelivr/jsdelivr#usage), which supports on-the-fly minification: https://cdn.jsdelivr.net/npm/plottable@3.1.1/plottable.min.js

**Comment by hellochar** [comment]
Closing - use jsDelivr (nice tip @MartinKolarik !) or a module bundler.
