### ISSUE TITLE
Regression in drag behavior with PanZoom after 3.4.1

### ISSUE THREAD

**Issue by aleburato** [palantir/plottable#3395]
## Bug report

Live example URL:

**WORKING (3.4.1)**
https://jsfiddle.net/aleburato/cdtarz12/2/

**BROKEN (3.5.1)**
https://jsfiddle.net/aleburato/0h93pbbt/8/

Steps to repro:
- Just try to drag on the lower mini-chart

### Expected behavior
The drag box is resized correctly and the main chart is updated accordingly

### Actual behavior
The main chart just pans as if you were dragging on it directly

**Comment by hellochar** [comment]
Thanks for the bug report @aleburato - this has been fixed in 3.5.2. I've updated your example by simply upgrading to **3.5.2**: https://jsfiddle.net/0h93pbbt/9/ Let us know if that works, cheers!

**Comment by aleburato** [comment]
Definitely. Loving Plottable AND Blueprint AND TSLint. You guys are a
constant stream of awesomeness.
