### ISSUE TITLE
stack bar label being cut off

### ISSUE THREAD

**Issue by sixinli** [palantir/plottable#3435]
## Bug report

Live example URL:
http://jsfiddle.net/2bzs9eoq/

### Expected behavior
label `23` to show up in full

### Actual behavior
label `23 gets cut off

### Context
only happen when the chart is small - if change size to 600*400 this is fine

### Environment

- Plottable version:3.6.1
- Browser name/version: chrome/63
- OS name/version:mac/10.12.6

**Comment by themadcreator** [comment]
In order to make room for the text above the label, you'll need to modify the y scale.

Try `yscale.padProportion(0.2)` which will add more padding above the stacked bars.
and try `yscale.snappingDomainEnabled(false)` which will prevent the domain from snapping to a "nice" value

**Comment by themadcreator** [comment]
We're not going to install a fix for this other than manually setting these values

**Comment by themadcreator** [comment]
see http://jsfiddle.net/2bzs9eoq/1/
