### ISSUE TITLE
Remove jquery from repository

### ISSUE THREAD

**Issue by adidahiya** [palantir/plottable#3436]
![image](https://user-images.githubusercontent.com/723999/35235546-7d9ccdb2-ff72-11e7-8f06-a92e586fa17a.png)

We don't need it.

**Comment by werrett** [comment]
+1 on this. The issue is Jquery is trez old and makes third-party request in a way that makes it vulnerable to cross-site scripting type attacks. More info:

https://github.com/jquery/jquery/issues/2432

**Comment by werrett** [comment]
@adidahiya Do you have an ETA for removing the dependency?

**Comment by adidahiya** [comment]
there is a PR open to resolve this https://github.com/palantir/plottable/pull/3439
