### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bnbarak** [palantir/plottable#3444]
# Bug report
## What
With Plottable version 3.7.0 and dataset size bigger than ~200,000, Plottable.js throws error when calling methods `entityNearest` or `entityNearestByXThenY` on a line chart.

## Error
```Uncaught RangeError: Maximum call stack size exceeded
    at EntityStore.addAll (VM94 plottable.js:17524)
    at Line.Plot._getEntityStore (VM94 plottable.js:727)
    at Line.Plot.entityNearest (VM94 plottable.js:783)
    at window.onload ((index):85)
```
Also see image:
![screen shot 2018-02-21 at 7 14 07 pm](https://user-images.githubusercontent.com/6034194/36513042-859fb02a-173b-11e8-8b1c-2790b24842f3.png)

## Example
Version 2.0 example (working): 
https://jsfiddle.net/mbzkx4eq/45/

Version: 3.7.0 (not working):
https://jsfiddle.net/mbzkx4eq/49/
## Other

Running on OSX 0.11.6 and Chrome 64.0.3282.167 (Official Build) (64-bit)

**Comment by gidim** [comment]
+1

**Comment by themadcreator** [comment]
I tried out the example using `3.8.1` and it appears to be fixed.

Also, in the example you're using x coordinates that are dates, but with a categorical scale. Try using a `Plottable.Scales.Time` instead
