### ISSUE TITLE
Plot boundaries

### ISSUE THREAD

**Issue by christopher-wolff-zz** [palantir/plottable#3484]
I would like to add a thin boundary line around a plot, just like the axis lines, but can't find a way to do this with the current API. I believe this would be a useful feature, especially for rectangle plots like this one: https://puu.sh/CRRuS/22c509210f.png. Otherwise there are some asymmetries in cells on the right and top boundaries.

**Comment by adidahiya** [comment]
Have you tried doing this with CSS? I was able to do this in the heatmap example:

![image](https://user-images.githubusercontent.com/723999/53842737-51a17900-3f6e-11e9-9b95-774f743d9fa7.png)

**Comment by christopher-wolff-zz** [comment]
Thanks for the solution!
