### ISSUE TITLE
Is plottable still maintained ?

### ISSUE THREAD

**Issue by lfaucheux** [palantir/plottable#3575]
Is plottable still maintained ? It looks like nothing "human" happened since November 12, 2020. Nothing serious at least?

**Comment by alvaroinfantedemoraes** [comment]
Hello, I don't think so. You can find some information on this thread:
https://github.com/palantir/plottable/issues/3537

Hope this helps you.

**Comment by lfaucheux** [comment]
It helps ! Thx.

**Comment by michael-yx-wu** [comment]
You may see the occasional bug fix for really critical problems, but we've otherwise shifted our charting dev efforts to an internal library.

**Comment by alvaroinfantedemoraes** [comment]
Thanks for your response.

**Comment by lfaucheux** [comment]
Actually, IMHO plottable's paradigme is so good that I decided to go with it anyway. And I do not regret my choice.
