### ISSUE TITLE
Drag Box Feature Request - Draggable Boxes

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#365]
From Robert Imig on the subject of Drag Boxes (PR #362):

> This is cool. Are you going to be able to drag the box around once you create the box? Or do you have to re-create it every time? Understand that might not be done now but hopefully we are thinking about it.

> One of the big use cases currently at a couple customers is to create the XDragBox you did below on chart and then slide that around to different times, and in a separate widget you see the contents of your sliding window.

**Comment by fent** [comment]
isn't this closed via #1303?

**Comment by jtlan** [comment]
#1303 only covers resizing.

**Comment by aicioara** [comment]
Code here to make it resizable. http://jsfiddle.net/pg7kb0m1/1/ Still needs to be movable
