### ISSUE TITLE
Ticks without values aren't deleted

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#416]
If you have ticks visible, occasionally there won't be room to fit the value associated with that tick onto the axis.  In that case, the tick should be deleted.

Repro:

1. go to http://jsfiddle.net/5YZ9u/207/ (contrived data, should reproduce error reliably)
2. notice that the top tick still shows up, without a value next to it.

Edit: Updated JSFiddle

![image](https://cloud.githubusercontent.com/assets/7527733/2989108/9e727f16-dc60-11e3-99f6-1135d7092aed.png)

**Comment by jtlan** [comment]
@bluong the `_hideEndTickLabels()` and `_hideOverlappingTickLabels()` calls will still cause this, since they only hide the labels.

**Comment by crmorford** [comment]
I haven't seen anything that looks bad recently. I think this just looked extra bad when we had uneven tick labels.
