### ISSUE TITLE
Option to only show integers on an axis

### ISSUE THREAD

**Issue by crmorford** [palantir/plottable#454]
Repro:
1. go to SLATE-67

We need an option to only show integers on an axis. 
This is distinct from formatting. 
Imagine ticks that are .2 apart from each other. Right now, plottable would show (for example) 11.6, 11.8, 12, 12.2 and 12.4. With formatting, I could round those to integers, but then I would get 5 '12s' in a row on an axis.

**Comment by jfrankl** [comment]
I'm trying to figure out how to do this. Did anyone figure it out?

**Comment by jfrankl** [comment]
Just got it. This example helped: http://plottablejs.org/examples/bump/

```yScale.tickGenerator(Plottable.Scales.TickGenerators.integerTickGenerator());```
