### ISSUE TITLE
Interactions should have disable() and enable() calls

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#696]
There should be some mechanism by which Interactions can be temporarily disabled.
We might also consider having some mechanism to disconnect Interactions.

**Comment by jtlan** [comment]
The fact that `Interaction`s have different architectures internally is screwing this up. As it stands, each `Interaction` would need a separate implementation of this feature. It might still be worth doing that for now, and then redoing it later.

**Comment by crmorford** [comment]
Hey, I noticed the milestone for this keeps getting pushed back. I'm going to assign it for real next week. How long do you expect this to take?

**Comment by jtlan** [comment]
@crmorford This is dependent on the `Dispatcher` refactors I'm currently working on.

By the way, what's a good API here?

```Typescript
// separate calls
public enable(): AbstractInteraction;
public disable(): AbstractInteraction;
```

or

```Typescript
// getter-setter
public enabled(): boolean;
public enabled(doEnable: boolean): AbstractInteraction;
```

**Comment by crmorford** [comment]
the getter-setter matches what I'm used to in Plottable. I prefer that.
