### ISSUE TITLE
PanZoomInteraction needs to be re-written

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#753]
It's implementation is very hacky right now and doesn't play nicely with special scales (e.g. ModifiedLog). 
The new version should be able to take null as an argument to a scale to pan/zoom on only one scale, like with gridlines.

Arguably it should be able to take an array of x/y scales, in which case it will pan/zoom them all at the same time, this would be useful for the case where you have, e.g., multiple y axes over the same plot

Also, it should have some maximum/minimum zoom level to prevent you from zooming insanely far and breaking things

**Comment by jtlan** [comment]
--> #1502 and #1581 .
