### ISSUE TITLE
Add ability to set interpolation mode on Line and Area Plots

### ISSUE THREAD

**Issue by rayshan** [palantir/plottable#757]
E.g. `d3.svg.area().interpolate("cardinal")`

Perhaps have `Plottable.Plot.Area()` take an options object?

Same for line as well.

**Comment by cmslewis** [comment]
+1 for making this a thing! What's the status here?

**Comment by optikfluffel** [comment]
+1

**Comment by LukeSheard** [comment]
+1 Has #1793 Solved this yet?

**Comment by rcchen** [comment]
Hi all, we've been working on stabilizing the API and getting a 1.0.0 release out the door. It's very close to being done now, and line/area interpolation should be landing shortly after that, so check back in a week or two.

That being said, we definitely welcome pull requests. If anyone wants to take a shot at getting #1793 working with the 1.0.0 release candidates, feel free to give it a shot :smiley:

**Comment by aicioara** [comment]
@rcchen what is the status of this?
