### ISSUE TITLE
Plottable.Core.KeyEventListener sets an un-namespaced listener on entire document

### ISSUE THREAD

**Issue by danmane** [palantir/plottable#837]
this causes a quicktest failure (key_interaction.js, pressing 'a' only resets the domain for the right test, and has no effect on the left, #782) and is a bad idea generally.

steps:
 - [ ] - Namespace it to Plottable so that it doesnt conflict w/ other libs
 - [ ] - namespace it on a per-branch basis to solve the quicktest problem.

**Comment by jtlan** [comment]
Update: Attaching key event listeners to `<svg>`s:
- Just works in IE9
- Only works in Chrome if you set the `tabindex` attribute on the `<svg>`
- Doesn't work in Firefox :(

**Comment by jtlan** [comment]
Fix from #1654: now sets a single `Dispatcher.Key` per `document`.
