### ISSUE TITLE
Order the class variables

### ISSUE THREAD

**Issue by bluong** [palantir/plottable#890]
Right now the class variables are ordered somewhat arbitrarily.  While we may want to come up with an order eventually (alphabetical helps with diff conflicts, canonical helps with clarity), we can start by moving the class variables.  I am personally a fan of static then non-static with each having the order of public, protected, then private.  I feel this puts a lot more clarity into a state of an object / what an object's variables are

**Comment by aicioara** [comment]
This has been discussed during the `v1.0.0` refactor. The change is huge, hard to automate and git conflict friendly. Not fixing.

**Comment by aicioara** [comment]
Reference https://github.com/palantir/plottable/issues/1942
