### ISSUE TITLE
Default Domainer strategies for plots are not being tested

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#951]
`Plot.VerticalBar` includes 0 in y and doesn't pad. `Plot.HorizontalBar` does the same in x. `Plot.Area` has some sort of special logic. None of this is being checked.

**Comment by crmorford** [comment]
@jtlan ^^ Are NewStylePlots standard now?

**Comment by bluong** [comment]
Yes

**Comment by aicioara** [comment]
We no longer have domainers, hence closing. The included baselines are tested.
