### ISSUE TITLE
API Point needed for Clustered, and Stacked bar alignment

### ISSUE THREAD

**Issue by terekim** [palantir/plottable#958]
for clustered and stacked bar plots with numeric axes, that need to be aligned.

![screen shot 2014-09-03 at 4 34 13 pm](https://cloud.githubusercontent.com/assets/8551049/4143034/dea28b08-33c2-11e4-87a4-a615cd9b20dc.png)

fiddle: http://jsfiddle.net/tkim/dg5frr38/28/

(@jtlan) updated fiddle: http://jsfiddle.net/6heLjyxw/

**Comment by crmorford** [comment]
fixed it
