### ISSUE TITLE
Quicktests should support asynchronous data loading

### ISSUE THREAD

**Issue by jtlan** [palantir/plottable#963]
Currently, each quicktest js file includes a `makeData()` call, which is assumed to be synchronous. What if I want to load a CSV?

A better structure would be that `makeData()` takes a callback, that is called with the data when the data is done loading.

... we should probably use a promise library or something on our quicktest page.

**Comment by aicioara** [comment]
Closed in https://github.com/palantir/plottable/pull/1278
